#include "DRVTags.h"

LIO_Driver_Struct           LIO_Driver_Instance;
Modbus_Master_Driver_Struct Modbus_Master_Driver_Instances[1];

void declare_and_init_drvtags(){

	IEC_DT time_temp;
	time_temp.tv_sec = 0;
	time_temp.tv_nsec = 0;

	LIO_Driver_Instance.Options.ChatterFilterCount = 2;
	LIO_Driver_Instance.Options.ChatterFilterBaseTimeMs = 1000;
	LIO_Driver_Instance.Options.ChatterFilterFreezeTimeMs =  10000;
	LIO_Driver_Instance.Options.IOScan = 100;
	strcpy(LIO_Driver_Instance.Options.TagConfiguration, "Value-Status-DT");

	LIO_Driver_Instance.number_of_tags = 48;
	LIO_Driver_Instance.Tags = (LIO_driverTag*) malloc(48 * sizeof(*LIO_Driver_Instance.Tags));
	strcpy(LIO_Driver_Instance.Tags[0].Name, "DITag0" );
	LIO_Driver_Instance.Tags[0].Type = 1;
	LIO_Driver_Instance.Tags[0].Init =  0;
	LIO_Driver_Instance.Tags[0].Address = 0;
	LIO_Driver_Instance.Tags[0].Range = 0;
	LIO_Driver_Instance.Tags[0].Deadband = 0;
	LIO_Driver_Instance.Tags[0].TagIndex = 0;
	LIO_Driver_Instance.Tags[0].TagValue = 0;
	LIO_Driver_Instance.Tags[0].OldTagValue = 0;
	LIO_Driver_Instance.Tags[0].TagStatus = 1;
	LIO_Driver_Instance.Tags[0].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[0].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[1].Name, "DITag1" );
	LIO_Driver_Instance.Tags[1].Type = 1;
	LIO_Driver_Instance.Tags[1].Init =  0;
	LIO_Driver_Instance.Tags[1].Address = 1;
	LIO_Driver_Instance.Tags[1].Range = 0;
	LIO_Driver_Instance.Tags[1].Deadband = 0;
	LIO_Driver_Instance.Tags[1].TagIndex = 1;
	LIO_Driver_Instance.Tags[1].TagValue = 0;
	LIO_Driver_Instance.Tags[1].OldTagValue = 0;
	LIO_Driver_Instance.Tags[1].TagStatus = 1;
	LIO_Driver_Instance.Tags[1].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[1].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[2].Name, "DITag2" );
	LIO_Driver_Instance.Tags[2].Type = 1;
	LIO_Driver_Instance.Tags[2].Init =  0;
	LIO_Driver_Instance.Tags[2].Address = 2;
	LIO_Driver_Instance.Tags[2].Range = 0;
	LIO_Driver_Instance.Tags[2].Deadband = 0;
	LIO_Driver_Instance.Tags[2].TagIndex = 2;
	LIO_Driver_Instance.Tags[2].TagValue = 0;
	LIO_Driver_Instance.Tags[2].OldTagValue = 0;
	LIO_Driver_Instance.Tags[2].TagStatus = 1;
	LIO_Driver_Instance.Tags[2].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[2].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[3].Name, "DITag3" );
	LIO_Driver_Instance.Tags[3].Type = 1;
	LIO_Driver_Instance.Tags[3].Init =  0;
	LIO_Driver_Instance.Tags[3].Address = 3;
	LIO_Driver_Instance.Tags[3].Range = 0;
	LIO_Driver_Instance.Tags[3].Deadband = 0;
	LIO_Driver_Instance.Tags[3].TagIndex = 3;
	LIO_Driver_Instance.Tags[3].TagValue = 0;
	LIO_Driver_Instance.Tags[3].OldTagValue = 0;
	LIO_Driver_Instance.Tags[3].TagStatus = 1;
	LIO_Driver_Instance.Tags[3].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[3].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[4].Name, "DITag4" );
	LIO_Driver_Instance.Tags[4].Type = 1;
	LIO_Driver_Instance.Tags[4].Init =  0;
	LIO_Driver_Instance.Tags[4].Address = 4;
	LIO_Driver_Instance.Tags[4].Range = 0;
	LIO_Driver_Instance.Tags[4].Deadband = 0;
	LIO_Driver_Instance.Tags[4].TagIndex = 4;
	LIO_Driver_Instance.Tags[4].TagValue = 0;
	LIO_Driver_Instance.Tags[4].OldTagValue = 0;
	LIO_Driver_Instance.Tags[4].TagStatus = 1;
	LIO_Driver_Instance.Tags[4].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[4].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[5].Name, "DITag5" );
	LIO_Driver_Instance.Tags[5].Type = 1;
	LIO_Driver_Instance.Tags[5].Init =  0;
	LIO_Driver_Instance.Tags[5].Address = 5;
	LIO_Driver_Instance.Tags[5].Range = 0;
	LIO_Driver_Instance.Tags[5].Deadband = 0;
	LIO_Driver_Instance.Tags[5].TagIndex = 5;
	LIO_Driver_Instance.Tags[5].TagValue = 0;
	LIO_Driver_Instance.Tags[5].OldTagValue = 0;
	LIO_Driver_Instance.Tags[5].TagStatus = 1;
	LIO_Driver_Instance.Tags[5].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[5].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[6].Name, "DITag6" );
	LIO_Driver_Instance.Tags[6].Type = 1;
	LIO_Driver_Instance.Tags[6].Init =  0;
	LIO_Driver_Instance.Tags[6].Address = 6;
	LIO_Driver_Instance.Tags[6].Range = 0;
	LIO_Driver_Instance.Tags[6].Deadband = 0;
	LIO_Driver_Instance.Tags[6].TagIndex = 6;
	LIO_Driver_Instance.Tags[6].TagValue = 0;
	LIO_Driver_Instance.Tags[6].OldTagValue = 0;
	LIO_Driver_Instance.Tags[6].TagStatus = 1;
	LIO_Driver_Instance.Tags[6].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[6].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[7].Name, "DITag7" );
	LIO_Driver_Instance.Tags[7].Type = 1;
	LIO_Driver_Instance.Tags[7].Init =  0;
	LIO_Driver_Instance.Tags[7].Address = 7;
	LIO_Driver_Instance.Tags[7].Range = 0;
	LIO_Driver_Instance.Tags[7].Deadband = 0;
	LIO_Driver_Instance.Tags[7].TagIndex = 7;
	LIO_Driver_Instance.Tags[7].TagValue = 0;
	LIO_Driver_Instance.Tags[7].OldTagValue = 0;
	LIO_Driver_Instance.Tags[7].TagStatus = 1;
	LIO_Driver_Instance.Tags[7].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[7].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[8].Name, "DOTag0" );
	LIO_Driver_Instance.Tags[8].Type = 10;
	LIO_Driver_Instance.Tags[8].Init =  0;
	LIO_Driver_Instance.Tags[8].Address = 0;
	LIO_Driver_Instance.Tags[8].Range = 0;
	LIO_Driver_Instance.Tags[8].Deadband = 0;
	LIO_Driver_Instance.Tags[8].TagIndex = 8;
	LIO_Driver_Instance.Tags[8].TagValue = 0;
	LIO_Driver_Instance.Tags[8].OldTagValue = 0;
	LIO_Driver_Instance.Tags[8].TagStatus = 1;
	LIO_Driver_Instance.Tags[8].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[8].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[9].Name, "DOTag1" );
	LIO_Driver_Instance.Tags[9].Type = 10;
	LIO_Driver_Instance.Tags[9].Init =  0;
	LIO_Driver_Instance.Tags[9].Address = 1;
	LIO_Driver_Instance.Tags[9].Range = 0;
	LIO_Driver_Instance.Tags[9].Deadband = 0;
	LIO_Driver_Instance.Tags[9].TagIndex = 9;
	LIO_Driver_Instance.Tags[9].TagValue = 0;
	LIO_Driver_Instance.Tags[9].OldTagValue = 0;
	LIO_Driver_Instance.Tags[9].TagStatus = 1;
	LIO_Driver_Instance.Tags[9].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[9].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[10].Name, "DOTag2" );
	LIO_Driver_Instance.Tags[10].Type = 10;
	LIO_Driver_Instance.Tags[10].Init =  0;
	LIO_Driver_Instance.Tags[10].Address = 2;
	LIO_Driver_Instance.Tags[10].Range = 0;
	LIO_Driver_Instance.Tags[10].Deadband = 0;
	LIO_Driver_Instance.Tags[10].TagIndex = 10;
	LIO_Driver_Instance.Tags[10].TagValue = 0;
	LIO_Driver_Instance.Tags[10].OldTagValue = 0;
	LIO_Driver_Instance.Tags[10].TagStatus = 1;
	LIO_Driver_Instance.Tags[10].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[10].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[11].Name, "DOTag3" );
	LIO_Driver_Instance.Tags[11].Type = 10;
	LIO_Driver_Instance.Tags[11].Init =  0;
	LIO_Driver_Instance.Tags[11].Address = 3;
	LIO_Driver_Instance.Tags[11].Range = 0;
	LIO_Driver_Instance.Tags[11].Deadband = 0;
	LIO_Driver_Instance.Tags[11].TagIndex = 11;
	LIO_Driver_Instance.Tags[11].TagValue = 0;
	LIO_Driver_Instance.Tags[11].OldTagValue = 0;
	LIO_Driver_Instance.Tags[11].TagStatus = 1;
	LIO_Driver_Instance.Tags[11].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[11].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[12].Name, "AITag0" );
	LIO_Driver_Instance.Tags[12].Type = 2;
	LIO_Driver_Instance.Tags[12].Init =  0;
	LIO_Driver_Instance.Tags[12].Address = 0;
	LIO_Driver_Instance.Tags[12].Range = 4;
	LIO_Driver_Instance.Tags[12].Deadband = 1;
	LIO_Driver_Instance.Tags[12].TagIndex = 12;
	LIO_Driver_Instance.Tags[12].TagValue = 0;
	LIO_Driver_Instance.Tags[12].OldTagValue = 0;
	LIO_Driver_Instance.Tags[12].TagStatus = 1;
	LIO_Driver_Instance.Tags[12].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[12].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[13].Name, "AITag1" );
	LIO_Driver_Instance.Tags[13].Type = 2;
	LIO_Driver_Instance.Tags[13].Init =  0;
	LIO_Driver_Instance.Tags[13].Address = 1;
	LIO_Driver_Instance.Tags[13].Range = 4;
	LIO_Driver_Instance.Tags[13].Deadband = 1;
	LIO_Driver_Instance.Tags[13].TagIndex = 13;
	LIO_Driver_Instance.Tags[13].TagValue = 0;
	LIO_Driver_Instance.Tags[13].OldTagValue = 0;
	LIO_Driver_Instance.Tags[13].TagStatus = 1;
	LIO_Driver_Instance.Tags[13].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[13].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[14].Name, "AITag2" );
	LIO_Driver_Instance.Tags[14].Type = 2;
	LIO_Driver_Instance.Tags[14].Init =  0;
	LIO_Driver_Instance.Tags[14].Address = 2;
	LIO_Driver_Instance.Tags[14].Range = 4;
	LIO_Driver_Instance.Tags[14].Deadband = 1;
	LIO_Driver_Instance.Tags[14].TagIndex = 14;
	LIO_Driver_Instance.Tags[14].TagValue = 0;
	LIO_Driver_Instance.Tags[14].OldTagValue = 0;
	LIO_Driver_Instance.Tags[14].TagStatus = 1;
	LIO_Driver_Instance.Tags[14].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[14].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[15].Name, "AITag3" );
	LIO_Driver_Instance.Tags[15].Type = 2;
	LIO_Driver_Instance.Tags[15].Init =  0;
	LIO_Driver_Instance.Tags[15].Address = 3;
	LIO_Driver_Instance.Tags[15].Range = 4;
	LIO_Driver_Instance.Tags[15].Deadband = 1;
	LIO_Driver_Instance.Tags[15].TagIndex = 15;
	LIO_Driver_Instance.Tags[15].TagValue = 0;
	LIO_Driver_Instance.Tags[15].OldTagValue = 0;
	LIO_Driver_Instance.Tags[15].TagStatus = 1;
	LIO_Driver_Instance.Tags[15].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[15].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[16].Name, "AOTag0" );
	LIO_Driver_Instance.Tags[16].Type = 11;
	LIO_Driver_Instance.Tags[16].Init =  0;
	LIO_Driver_Instance.Tags[16].Address = 0;
	LIO_Driver_Instance.Tags[16].Range = 0;
	LIO_Driver_Instance.Tags[16].Deadband = 0;
	LIO_Driver_Instance.Tags[16].TagIndex = 16;
	LIO_Driver_Instance.Tags[16].TagValue = 0;
	LIO_Driver_Instance.Tags[16].OldTagValue = 0;
	LIO_Driver_Instance.Tags[16].TagStatus = 1;
	LIO_Driver_Instance.Tags[16].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[16].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[17].Name, "CNTTag0" );
	LIO_Driver_Instance.Tags[17].Type = 3;
	LIO_Driver_Instance.Tags[17].Init =  0;
	LIO_Driver_Instance.Tags[17].Address = 0;
	LIO_Driver_Instance.Tags[17].Range = 0;
	LIO_Driver_Instance.Tags[17].Deadband = 0;
	LIO_Driver_Instance.Tags[17].TagIndex = 17;
	LIO_Driver_Instance.Tags[17].TagValue = 0;
	LIO_Driver_Instance.Tags[17].OldTagValue = 0;
	LIO_Driver_Instance.Tags[17].TagStatus = 1;
	LIO_Driver_Instance.Tags[17].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[17].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[18].Name, "CNTTag1" );
	LIO_Driver_Instance.Tags[18].Type = 3;
	LIO_Driver_Instance.Tags[18].Init =  0;
	LIO_Driver_Instance.Tags[18].Address = 1;
	LIO_Driver_Instance.Tags[18].Range = 0;
	LIO_Driver_Instance.Tags[18].Deadband = 0;
	LIO_Driver_Instance.Tags[18].TagIndex = 18;
	LIO_Driver_Instance.Tags[18].TagValue = 0;
	LIO_Driver_Instance.Tags[18].OldTagValue = 0;
	LIO_Driver_Instance.Tags[18].TagStatus = 1;
	LIO_Driver_Instance.Tags[18].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[18].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[19].Name, "CNTTag2" );
	LIO_Driver_Instance.Tags[19].Type = 3;
	LIO_Driver_Instance.Tags[19].Init =  0;
	LIO_Driver_Instance.Tags[19].Address = 2;
	LIO_Driver_Instance.Tags[19].Range = 0;
	LIO_Driver_Instance.Tags[19].Deadband = 0;
	LIO_Driver_Instance.Tags[19].TagIndex = 19;
	LIO_Driver_Instance.Tags[19].TagValue = 0;
	LIO_Driver_Instance.Tags[19].OldTagValue = 0;
	LIO_Driver_Instance.Tags[19].TagStatus = 1;
	LIO_Driver_Instance.Tags[19].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[19].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[20].Name, "CNTTag3" );
	LIO_Driver_Instance.Tags[20].Type = 3;
	LIO_Driver_Instance.Tags[20].Init =  0;
	LIO_Driver_Instance.Tags[20].Address = 3;
	LIO_Driver_Instance.Tags[20].Range = 0;
	LIO_Driver_Instance.Tags[20].Deadband = 0;
	LIO_Driver_Instance.Tags[20].TagIndex = 20;
	LIO_Driver_Instance.Tags[20].TagValue = 0;
	LIO_Driver_Instance.Tags[20].OldTagValue = 0;
	LIO_Driver_Instance.Tags[20].TagStatus = 1;
	LIO_Driver_Instance.Tags[20].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[20].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[21].Name, "SENTag0" );
	LIO_Driver_Instance.Tags[21].Type = 4;
	LIO_Driver_Instance.Tags[21].Init =  0;
	LIO_Driver_Instance.Tags[21].Address = 0;
	LIO_Driver_Instance.Tags[21].Range = 0;
	LIO_Driver_Instance.Tags[21].Deadband = 0;
	LIO_Driver_Instance.Tags[21].TagIndex = 21;
	LIO_Driver_Instance.Tags[21].TagValue = 0;
	LIO_Driver_Instance.Tags[21].OldTagValue = 0;
	LIO_Driver_Instance.Tags[21].TagStatus = 1;
	LIO_Driver_Instance.Tags[21].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[21].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[22].Name, "SENTag1" );
	LIO_Driver_Instance.Tags[22].Type = 4;
	LIO_Driver_Instance.Tags[22].Init =  0;
	LIO_Driver_Instance.Tags[22].Address = 1;
	LIO_Driver_Instance.Tags[22].Range = 0;
	LIO_Driver_Instance.Tags[22].Deadband = 0;
	LIO_Driver_Instance.Tags[22].TagIndex = 22;
	LIO_Driver_Instance.Tags[22].TagValue = 0;
	LIO_Driver_Instance.Tags[22].OldTagValue = 0;
	LIO_Driver_Instance.Tags[22].TagStatus = 1;
	LIO_Driver_Instance.Tags[22].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[22].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[23].Name, "Reset" );
	LIO_Driver_Instance.Tags[23].Type = 201;
	LIO_Driver_Instance.Tags[23].Init =  0;
	LIO_Driver_Instance.Tags[23].Address = 0;
	LIO_Driver_Instance.Tags[23].Range = 0;
	LIO_Driver_Instance.Tags[23].Deadband = 0;
	LIO_Driver_Instance.Tags[23].TagIndex = 23;
	LIO_Driver_Instance.Tags[23].TagValue = 0;
	LIO_Driver_Instance.Tags[23].OldTagValue = 0;
	LIO_Driver_Instance.Tags[23].TagStatus = 1;
	LIO_Driver_Instance.Tags[23].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[23].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[24].Name, "CPU_Usage" );
	LIO_Driver_Instance.Tags[24].Type = 200;
	LIO_Driver_Instance.Tags[24].Init =  0;
	LIO_Driver_Instance.Tags[24].Address = 1;
	LIO_Driver_Instance.Tags[24].Range = 0;
	LIO_Driver_Instance.Tags[24].Deadband = 0;
	LIO_Driver_Instance.Tags[24].TagIndex = 24;
	LIO_Driver_Instance.Tags[24].TagValue = 0;
	LIO_Driver_Instance.Tags[24].OldTagValue = 0;
	LIO_Driver_Instance.Tags[24].TagStatus = 1;
	LIO_Driver_Instance.Tags[24].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[24].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[25].Name, "Total_RAM" );
	LIO_Driver_Instance.Tags[25].Type = 200;
	LIO_Driver_Instance.Tags[25].Init =  0;
	LIO_Driver_Instance.Tags[25].Address = 2;
	LIO_Driver_Instance.Tags[25].Range = 0;
	LIO_Driver_Instance.Tags[25].Deadband = 0;
	LIO_Driver_Instance.Tags[25].TagIndex = 25;
	LIO_Driver_Instance.Tags[25].TagValue = 0;
	LIO_Driver_Instance.Tags[25].OldTagValue = 0;
	LIO_Driver_Instance.Tags[25].TagStatus = 1;
	LIO_Driver_Instance.Tags[25].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[25].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[26].Name, "FreeSpace_RAM" );
	LIO_Driver_Instance.Tags[26].Type = 200;
	LIO_Driver_Instance.Tags[26].Init =  0;
	LIO_Driver_Instance.Tags[26].Address = 3;
	LIO_Driver_Instance.Tags[26].Range = 0;
	LIO_Driver_Instance.Tags[26].Deadband = 0;
	LIO_Driver_Instance.Tags[26].TagIndex = 26;
	LIO_Driver_Instance.Tags[26].TagValue = 0;
	LIO_Driver_Instance.Tags[26].OldTagValue = 0;
	LIO_Driver_Instance.Tags[26].TagStatus = 1;
	LIO_Driver_Instance.Tags[26].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[26].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[27].Name, "Used_RAM" );
	LIO_Driver_Instance.Tags[27].Type = 200;
	LIO_Driver_Instance.Tags[27].Init =  0;
	LIO_Driver_Instance.Tags[27].Address = 4;
	LIO_Driver_Instance.Tags[27].Range = 0;
	LIO_Driver_Instance.Tags[27].Deadband = 0;
	LIO_Driver_Instance.Tags[27].TagIndex = 27;
	LIO_Driver_Instance.Tags[27].TagValue = 0;
	LIO_Driver_Instance.Tags[27].OldTagValue = 0;
	LIO_Driver_Instance.Tags[27].TagStatus = 1;
	LIO_Driver_Instance.Tags[27].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[27].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[28].Name, "Total_Flash" );
	LIO_Driver_Instance.Tags[28].Type = 200;
	LIO_Driver_Instance.Tags[28].Init =  0;
	LIO_Driver_Instance.Tags[28].Address = 5;
	LIO_Driver_Instance.Tags[28].Range = 0;
	LIO_Driver_Instance.Tags[28].Deadband = 0;
	LIO_Driver_Instance.Tags[28].TagIndex = 28;
	LIO_Driver_Instance.Tags[28].TagValue = 0;
	LIO_Driver_Instance.Tags[28].OldTagValue = 0;
	LIO_Driver_Instance.Tags[28].TagStatus = 1;
	LIO_Driver_Instance.Tags[28].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[28].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[29].Name, "FreeSpace_Flash" );
	LIO_Driver_Instance.Tags[29].Type = 200;
	LIO_Driver_Instance.Tags[29].Init =  0;
	LIO_Driver_Instance.Tags[29].Address = 6;
	LIO_Driver_Instance.Tags[29].Range = 0;
	LIO_Driver_Instance.Tags[29].Deadband = 0;
	LIO_Driver_Instance.Tags[29].TagIndex = 29;
	LIO_Driver_Instance.Tags[29].TagValue = 0;
	LIO_Driver_Instance.Tags[29].OldTagValue = 0;
	LIO_Driver_Instance.Tags[29].TagStatus = 1;
	LIO_Driver_Instance.Tags[29].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[29].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[30].Name, "Used_Flash" );
	LIO_Driver_Instance.Tags[30].Type = 200;
	LIO_Driver_Instance.Tags[30].Init =  0;
	LIO_Driver_Instance.Tags[30].Address = 7;
	LIO_Driver_Instance.Tags[30].Range = 0;
	LIO_Driver_Instance.Tags[30].Deadband = 0;
	LIO_Driver_Instance.Tags[30].TagIndex = 30;
	LIO_Driver_Instance.Tags[30].TagValue = 0;
	LIO_Driver_Instance.Tags[30].OldTagValue = 0;
	LIO_Driver_Instance.Tags[30].TagStatus = 1;
	LIO_Driver_Instance.Tags[30].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[30].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[31].Name, "Total_SDCard" );
	LIO_Driver_Instance.Tags[31].Type = 200;
	LIO_Driver_Instance.Tags[31].Init =  0;
	LIO_Driver_Instance.Tags[31].Address = 8;
	LIO_Driver_Instance.Tags[31].Range = 0;
	LIO_Driver_Instance.Tags[31].Deadband = 0;
	LIO_Driver_Instance.Tags[31].TagIndex = 31;
	LIO_Driver_Instance.Tags[31].TagValue = 0;
	LIO_Driver_Instance.Tags[31].OldTagValue = 0;
	LIO_Driver_Instance.Tags[31].TagStatus = 1;
	LIO_Driver_Instance.Tags[31].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[31].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[32].Name, "FreeSpace_SDCard" );
	LIO_Driver_Instance.Tags[32].Type = 200;
	LIO_Driver_Instance.Tags[32].Init =  0;
	LIO_Driver_Instance.Tags[32].Address = 9;
	LIO_Driver_Instance.Tags[32].Range = 0;
	LIO_Driver_Instance.Tags[32].Deadband = 0;
	LIO_Driver_Instance.Tags[32].TagIndex = 32;
	LIO_Driver_Instance.Tags[32].TagValue = 0;
	LIO_Driver_Instance.Tags[32].OldTagValue = 0;
	LIO_Driver_Instance.Tags[32].TagStatus = 1;
	LIO_Driver_Instance.Tags[32].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[32].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[33].Name, "Used_SDCard" );
	LIO_Driver_Instance.Tags[33].Type = 200;
	LIO_Driver_Instance.Tags[33].Init =  0;
	LIO_Driver_Instance.Tags[33].Address = 10;
	LIO_Driver_Instance.Tags[33].Range = 0;
	LIO_Driver_Instance.Tags[33].Deadband = 0;
	LIO_Driver_Instance.Tags[33].TagIndex = 33;
	LIO_Driver_Instance.Tags[33].TagValue = 0;
	LIO_Driver_Instance.Tags[33].OldTagValue = 0;
	LIO_Driver_Instance.Tags[33].TagStatus = 1;
	LIO_Driver_Instance.Tags[33].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[33].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[34].Name, "Total_NVRAM" );
	LIO_Driver_Instance.Tags[34].Type = 200;
	LIO_Driver_Instance.Tags[34].Init =  0;
	LIO_Driver_Instance.Tags[34].Address = 11;
	LIO_Driver_Instance.Tags[34].Range = 0;
	LIO_Driver_Instance.Tags[34].Deadband = 0;
	LIO_Driver_Instance.Tags[34].TagIndex = 34;
	LIO_Driver_Instance.Tags[34].TagValue = 0;
	LIO_Driver_Instance.Tags[34].OldTagValue = 0;
	LIO_Driver_Instance.Tags[34].TagStatus = 1;
	LIO_Driver_Instance.Tags[34].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[34].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[35].Name, "FreeSpace_NVRAM" );
	LIO_Driver_Instance.Tags[35].Type = 200;
	LIO_Driver_Instance.Tags[35].Init =  0;
	LIO_Driver_Instance.Tags[35].Address = 12;
	LIO_Driver_Instance.Tags[35].Range = 0;
	LIO_Driver_Instance.Tags[35].Deadband = 0;
	LIO_Driver_Instance.Tags[35].TagIndex = 35;
	LIO_Driver_Instance.Tags[35].TagValue = 0;
	LIO_Driver_Instance.Tags[35].OldTagValue = 0;
	LIO_Driver_Instance.Tags[35].TagStatus = 1;
	LIO_Driver_Instance.Tags[35].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[35].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[36].Name, "Used_NVRAM" );
	LIO_Driver_Instance.Tags[36].Type = 200;
	LIO_Driver_Instance.Tags[36].Init =  0;
	LIO_Driver_Instance.Tags[36].Address = 13;
	LIO_Driver_Instance.Tags[36].Range = 0;
	LIO_Driver_Instance.Tags[36].Deadband = 0;
	LIO_Driver_Instance.Tags[36].TagIndex = 36;
	LIO_Driver_Instance.Tags[36].TagValue = 0;
	LIO_Driver_Instance.Tags[36].OldTagValue = 0;
	LIO_Driver_Instance.Tags[36].TagStatus = 1;
	LIO_Driver_Instance.Tags[36].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[36].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[37].Name, "CANBUS_Status" );
	LIO_Driver_Instance.Tags[37].Type = 200;
	LIO_Driver_Instance.Tags[37].Init =  0;
	LIO_Driver_Instance.Tags[37].Address = 14;
	LIO_Driver_Instance.Tags[37].Range = 0;
	LIO_Driver_Instance.Tags[37].Deadband = 0;
	LIO_Driver_Instance.Tags[37].TagIndex = 37;
	LIO_Driver_Instance.Tags[37].TagValue = 0;
	LIO_Driver_Instance.Tags[37].OldTagValue = 0;
	LIO_Driver_Instance.Tags[37].TagStatus = 1;
	LIO_Driver_Instance.Tags[37].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[37].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[38].Name, "Buzzer" );
	LIO_Driver_Instance.Tags[38].Type = 201;
	LIO_Driver_Instance.Tags[38].Init =  0;
	LIO_Driver_Instance.Tags[38].Address = 15;
	LIO_Driver_Instance.Tags[38].Range = 0;
	LIO_Driver_Instance.Tags[38].Deadband = 0;
	LIO_Driver_Instance.Tags[38].TagIndex = 38;
	LIO_Driver_Instance.Tags[38].TagValue = 0;
	LIO_Driver_Instance.Tags[38].OldTagValue = 0;
	LIO_Driver_Instance.Tags[38].TagStatus = 1;
	LIO_Driver_Instance.Tags[38].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[38].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[39].Name, "3GModemON" );
	LIO_Driver_Instance.Tags[39].Type = 201;
	LIO_Driver_Instance.Tags[39].Init =  0;
	LIO_Driver_Instance.Tags[39].Address = 16;
	LIO_Driver_Instance.Tags[39].Range = 0;
	LIO_Driver_Instance.Tags[39].Deadband = 0;
	LIO_Driver_Instance.Tags[39].TagIndex = 39;
	LIO_Driver_Instance.Tags[39].TagValue = 0;
	LIO_Driver_Instance.Tags[39].OldTagValue = 0;
	LIO_Driver_Instance.Tags[39].TagStatus = 1;
	LIO_Driver_Instance.Tags[39].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[39].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[40].Name, "3GModemSignallevel" );
	LIO_Driver_Instance.Tags[40].Type = 200;
	LIO_Driver_Instance.Tags[40].Init =  0;
	LIO_Driver_Instance.Tags[40].Address = 17;
	LIO_Driver_Instance.Tags[40].Range = 0;
	LIO_Driver_Instance.Tags[40].Deadband = 0;
	LIO_Driver_Instance.Tags[40].TagIndex = 40;
	LIO_Driver_Instance.Tags[40].TagValue = 0;
	LIO_Driver_Instance.Tags[40].OldTagValue = 0;
	LIO_Driver_Instance.Tags[40].TagStatus = 1;
	LIO_Driver_Instance.Tags[40].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[40].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[41].Name, "3GConnected" );
	LIO_Driver_Instance.Tags[41].Type = 200;
	LIO_Driver_Instance.Tags[41].Init =  0;
	LIO_Driver_Instance.Tags[41].Address = 18;
	LIO_Driver_Instance.Tags[41].Range = 0;
	LIO_Driver_Instance.Tags[41].Deadband = 0;
	LIO_Driver_Instance.Tags[41].TagIndex = 41;
	LIO_Driver_Instance.Tags[41].TagValue = 0;
	LIO_Driver_Instance.Tags[41].OldTagValue = 0;
	LIO_Driver_Instance.Tags[41].TagStatus = 1;
	LIO_Driver_Instance.Tags[41].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[41].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[42].Name, "3GModemSecIP1" );
	LIO_Driver_Instance.Tags[42].Type = 200;
	LIO_Driver_Instance.Tags[42].Init =  0;
	LIO_Driver_Instance.Tags[42].Address = 19;
	LIO_Driver_Instance.Tags[42].Range = 0;
	LIO_Driver_Instance.Tags[42].Deadband = 0;
	LIO_Driver_Instance.Tags[42].TagIndex = 42;
	LIO_Driver_Instance.Tags[42].TagValue = 0;
	LIO_Driver_Instance.Tags[42].OldTagValue = 0;
	LIO_Driver_Instance.Tags[42].TagStatus = 1;
	LIO_Driver_Instance.Tags[42].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[42].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[43].Name, "3GModemSecIP2" );
	LIO_Driver_Instance.Tags[43].Type = 200;
	LIO_Driver_Instance.Tags[43].Init =  0;
	LIO_Driver_Instance.Tags[43].Address = 20;
	LIO_Driver_Instance.Tags[43].Range = 0;
	LIO_Driver_Instance.Tags[43].Deadband = 0;
	LIO_Driver_Instance.Tags[43].TagIndex = 43;
	LIO_Driver_Instance.Tags[43].TagValue = 0;
	LIO_Driver_Instance.Tags[43].OldTagValue = 0;
	LIO_Driver_Instance.Tags[43].TagStatus = 1;
	LIO_Driver_Instance.Tags[43].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[43].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[44].Name, "3GModemSecIP3" );
	LIO_Driver_Instance.Tags[44].Type = 200;
	LIO_Driver_Instance.Tags[44].Init =  0;
	LIO_Driver_Instance.Tags[44].Address = 21;
	LIO_Driver_Instance.Tags[44].Range = 0;
	LIO_Driver_Instance.Tags[44].Deadband = 0;
	LIO_Driver_Instance.Tags[44].TagIndex = 44;
	LIO_Driver_Instance.Tags[44].TagValue = 0;
	LIO_Driver_Instance.Tags[44].OldTagValue = 0;
	LIO_Driver_Instance.Tags[44].TagStatus = 1;
	LIO_Driver_Instance.Tags[44].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[44].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[45].Name, "3GModemSecIP4" );
	LIO_Driver_Instance.Tags[45].Type = 200;
	LIO_Driver_Instance.Tags[45].Init =  0;
	LIO_Driver_Instance.Tags[45].Address = 22;
	LIO_Driver_Instance.Tags[45].Range = 0;
	LIO_Driver_Instance.Tags[45].Deadband = 0;
	LIO_Driver_Instance.Tags[45].TagIndex = 45;
	LIO_Driver_Instance.Tags[45].TagValue = 0;
	LIO_Driver_Instance.Tags[45].OldTagValue = 0;
	LIO_Driver_Instance.Tags[45].TagStatus = 1;
	LIO_Driver_Instance.Tags[45].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[45].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[46].Name, "Logic_Processing_Time" );
	LIO_Driver_Instance.Tags[46].Type = 200;
	LIO_Driver_Instance.Tags[46].Init =  0;
	LIO_Driver_Instance.Tags[46].Address = 23;
	LIO_Driver_Instance.Tags[46].Range = 0;
	LIO_Driver_Instance.Tags[46].Deadband = 0;
	LIO_Driver_Instance.Tags[46].TagIndex = 46;
	LIO_Driver_Instance.Tags[46].TagValue = 0;
	LIO_Driver_Instance.Tags[46].OldTagValue = 0;
	LIO_Driver_Instance.Tags[46].TagStatus = 1;
	LIO_Driver_Instance.Tags[46].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[46].TagValueDT = time_temp;

	strcpy(LIO_Driver_Instance.Tags[47].Name, "First_Scan" );
	LIO_Driver_Instance.Tags[47].Type = 200;
	LIO_Driver_Instance.Tags[47].Init =  0;
	LIO_Driver_Instance.Tags[47].Address = 24;
	LIO_Driver_Instance.Tags[47].Range = 0;
	LIO_Driver_Instance.Tags[47].Deadband = 0;
	LIO_Driver_Instance.Tags[47].TagIndex = 47;
	LIO_Driver_Instance.Tags[47].TagValue = 0;
	LIO_Driver_Instance.Tags[47].OldTagValue = 0;
	LIO_Driver_Instance.Tags[47].TagStatus = 1;
	LIO_Driver_Instance.Tags[47].OldTagStatus = 1;
	LIO_Driver_Instance.Tags[47].TagValueDT = time_temp;

	Modbus_Master_Driver_Instances[0].Options.Disable = false;
	strcpy(Modbus_Master_Driver_Instances[0].Options.COMPort, "3");
	Modbus_Master_Driver_Instances[0].Options.BaudRate = 9600;
	Modbus_Master_Driver_Instances[0].Options.DataBit = 8;
	Modbus_Master_Driver_Instances[0].Options.Instance = 1;
	Modbus_Master_Driver_Instances[0].Options.StopBit = 1;
	Modbus_Master_Driver_Instances[0].Options.Parity = 'N';
	strcpy(Modbus_Master_Driver_Instances[0].Options.WakeUpString, "");
	Modbus_Master_Driver_Instances[0].Options.DelayBetweenPolls = 200;
	Modbus_Master_Driver_Instances[0].Options.ContPoll = 0;
	Modbus_Master_Driver_Instances[0].Options.ByteFormat = 1;
	Modbus_Master_Driver_Instances[0].Options.WriteByChange = 1;
	Modbus_Master_Driver_Instances[0].Options.DiagMode = 0;
	strcpy(Modbus_Master_Driver_Instances[0].Options.PhysicalLayer, "TCP");

	Modbus_Master_Driver_Instances[0].number_of_modbus_blocks = 1;
	Modbus_Master_Driver_Instances[0].Blocks = (ModbusBlocks*)malloc(1 * sizeof(*Modbus_Master_Driver_Instances[0].Blocks));
	strcpy(Modbus_Master_Driver_Instances[0].Blocks[0].DeviceName, "pumpag1");
	Modbus_Master_Driver_Instances[0].Blocks[0].SlaveID = 5;
	strcpy(Modbus_Master_Driver_Instances[0].Blocks[0].IP, "192.168.1.248");
	Modbus_Master_Driver_Instances[0].Blocks[0].SocketPort = 502;
	strcpy(Modbus_Master_Driver_Instances[0].Blocks[0].Name, "p1var1");
	Modbus_Master_Driver_Instances[0].Blocks[0].Type = 1;
	Modbus_Master_Driver_Instances[0].Blocks[0].StartAdd = 0;
	Modbus_Master_Driver_Instances[0].Blocks[0].Count = 10;
	Modbus_Master_Driver_Instances[0].Blocks[0].Timeout = 2000;
	Modbus_Master_Driver_Instances[0].Blocks[0].Enable = true;
	Modbus_Master_Driver_Instances[0].Blocks[0].FirstTagIndex = 0;
	Modbus_Master_Driver_Instances[0].Blocks[0].LastTagIndex = 14;

	Modbus_Master_Driver_Instances[0].number_of_tags = 15;
	Modbus_Master_Driver_Instances[0].Tags = (Modbus_master_driverTag*) malloc(15 * sizeof(*Modbus_Master_Driver_Instances[0].Tags));
	strcpy(Modbus_Master_Driver_Instances[0].Tags[0].Name, "Tag0");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[0].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[0].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[0].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[0].Address = 0;
	Modbus_Master_Driver_Instances[0].Tags[0].TagIndex = 0;
	Modbus_Master_Driver_Instances[0].Tags[0].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[0].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[0].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[0].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[0].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[1].Name, "Tag1");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[1].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[1].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[1].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[1].Address = 1;
	Modbus_Master_Driver_Instances[0].Tags[1].TagIndex = 1;
	Modbus_Master_Driver_Instances[0].Tags[1].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[1].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[1].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[1].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[1].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[2].Name, "Tag2");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[2].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[2].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[2].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[2].Address = 2;
	Modbus_Master_Driver_Instances[0].Tags[2].TagIndex = 2;
	Modbus_Master_Driver_Instances[0].Tags[2].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[2].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[2].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[2].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[2].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[3].Name, "Tag3");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[3].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[3].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[3].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[3].Address = 3;
	Modbus_Master_Driver_Instances[0].Tags[3].TagIndex = 3;
	Modbus_Master_Driver_Instances[0].Tags[3].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[3].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[3].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[3].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[3].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[4].Name, "Tag4");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[4].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[4].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[4].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[4].Address = 4;
	Modbus_Master_Driver_Instances[0].Tags[4].TagIndex = 4;
	Modbus_Master_Driver_Instances[0].Tags[4].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[4].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[4].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[4].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[4].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[5].Name, "Tag5");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[5].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[5].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[5].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[5].Address = 5;
	Modbus_Master_Driver_Instances[0].Tags[5].TagIndex = 5;
	Modbus_Master_Driver_Instances[0].Tags[5].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[5].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[5].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[5].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[5].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[6].Name, "Tag6");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[6].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[6].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[6].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[6].Address = 6;
	Modbus_Master_Driver_Instances[0].Tags[6].TagIndex = 6;
	Modbus_Master_Driver_Instances[0].Tags[6].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[6].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[6].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[6].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[6].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[7].Name, "Tag7");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[7].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[7].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[7].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[7].Address = 7;
	Modbus_Master_Driver_Instances[0].Tags[7].TagIndex = 7;
	Modbus_Master_Driver_Instances[0].Tags[7].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[7].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[7].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[7].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[7].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[8].Name, "Tag8");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[8].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[8].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[8].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[8].Address = 8;
	Modbus_Master_Driver_Instances[0].Tags[8].TagIndex = 8;
	Modbus_Master_Driver_Instances[0].Tags[8].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[8].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[8].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[8].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[8].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[9].Name, "Tag9");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[9].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[9].Type = 1;
	Modbus_Master_Driver_Instances[0].Tags[9].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[9].Address = 9;
	Modbus_Master_Driver_Instances[0].Tags[9].TagIndex = 9;
	Modbus_Master_Driver_Instances[0].Tags[9].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[9].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[9].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[9].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[9].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[10].Name, "OnLine");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[10].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[10].Type = 201;
	Modbus_Master_Driver_Instances[0].Tags[10].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[10].Address = 0;
	Modbus_Master_Driver_Instances[0].Tags[10].TagIndex = 10;
	Modbus_Master_Driver_Instances[0].Tags[10].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[10].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[10].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[10].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[10].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[11].Name, "SendNum");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[11].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[11].Type = 201;
	Modbus_Master_Driver_Instances[0].Tags[11].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[11].Address = 1;
	Modbus_Master_Driver_Instances[0].Tags[11].TagIndex = 11;
	Modbus_Master_Driver_Instances[0].Tags[11].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[11].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[11].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[11].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[11].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[12].Name, "RecNum");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[12].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[12].Type = 201;
	Modbus_Master_Driver_Instances[0].Tags[12].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[12].Address = 2;
	Modbus_Master_Driver_Instances[0].Tags[12].TagIndex = 12;
	Modbus_Master_Driver_Instances[0].Tags[12].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[12].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[12].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[12].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[12].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[13].Name, "Error");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[13].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[13].Type = 201;
	Modbus_Master_Driver_Instances[0].Tags[13].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[13].Address = 3;
	Modbus_Master_Driver_Instances[0].Tags[13].TagIndex = 13;
	Modbus_Master_Driver_Instances[0].Tags[13].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[13].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[13].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[13].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[13].TagValueDT = time_temp;

	strcpy(Modbus_Master_Driver_Instances[0].Tags[14].Name, "Poll");
	strcpy(Modbus_Master_Driver_Instances[0].Tags[14].BlockName, "p1var1");
	Modbus_Master_Driver_Instances[0].Tags[14].Type = 202;
	Modbus_Master_Driver_Instances[0].Tags[14].Init =  0;
	Modbus_Master_Driver_Instances[0].Tags[14].Address = 4;
	Modbus_Master_Driver_Instances[0].Tags[14].TagIndex = 14;
	Modbus_Master_Driver_Instances[0].Tags[14].TagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[14].OldTagValue = 0;
	Modbus_Master_Driver_Instances[0].Tags[14].TagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[14].OldTagStatus = 1;
	Modbus_Master_Driver_Instances[0].Tags[14].TagValueDT = time_temp;

}
