#include "ladder.h"


void setDRVTagsFromVars(){
	LIO_Driver_Instance.Tags[8].TagValue = __GET_VAR(RES0__LIO_DOTAG0,);
	LIO_Driver_Instance.Tags[8].TagStatus = __GET_VAR(RES0__LIO_DOTAG0_STATUS,);
	LIO_Driver_Instance.Tags[8].TagValueDT = __GET_VAR(RES0__LIO_DOTAG0_DT,);
	LIO_Driver_Instance.Tags[9].TagValue = __GET_VAR(RES0__LIO_DOTAG1,);
	LIO_Driver_Instance.Tags[9].TagStatus = __GET_VAR(RES0__LIO_DOTAG1_STATUS,);
	LIO_Driver_Instance.Tags[9].TagValueDT = __GET_VAR(RES0__LIO_DOTAG1_DT,);
	LIO_Driver_Instance.Tags[10].TagValue = __GET_VAR(RES0__LIO_DOTAG2,);
	LIO_Driver_Instance.Tags[10].TagStatus = __GET_VAR(RES0__LIO_DOTAG2_STATUS,);
	LIO_Driver_Instance.Tags[10].TagValueDT = __GET_VAR(RES0__LIO_DOTAG2_DT,);
	LIO_Driver_Instance.Tags[11].TagValue = __GET_VAR(RES0__LIO_DOTAG3,);
	LIO_Driver_Instance.Tags[11].TagStatus = __GET_VAR(RES0__LIO_DOTAG3_STATUS,);
	LIO_Driver_Instance.Tags[11].TagValueDT = __GET_VAR(RES0__LIO_DOTAG3_DT,);
	LIO_Driver_Instance.Tags[16].TagValue = __GET_VAR(RES0__LIO_AOTAG0,);
	LIO_Driver_Instance.Tags[16].TagStatus = __GET_VAR(RES0__LIO_AOTAG0_STATUS,);
	LIO_Driver_Instance.Tags[16].TagValueDT = __GET_VAR(RES0__LIO_AOTAG0_DT,);
	LIO_Driver_Instance.Tags[23].TagValue = __GET_VAR(RES0__LIO_RESET,);
	LIO_Driver_Instance.Tags[23].TagStatus = __GET_VAR(RES0__LIO_RESET_STATUS,);
	LIO_Driver_Instance.Tags[23].TagValueDT = __GET_VAR(RES0__LIO_RESET_DT,);
	LIO_Driver_Instance.Tags[38].TagValue = __GET_VAR(RES0__LIO_BUZZER,);
	LIO_Driver_Instance.Tags[38].TagStatus = __GET_VAR(RES0__LIO_BUZZER_STATUS,);
	LIO_Driver_Instance.Tags[38].TagValueDT = __GET_VAR(RES0__LIO_BUZZER_DT,);
	LIO_Driver_Instance.Tags[39].TagValue = __GET_VAR(RES0__LIO_3GMODEMON,);
	LIO_Driver_Instance.Tags[39].TagStatus = __GET_VAR(RES0__LIO_3GMODEMON_STATUS,);
	LIO_Driver_Instance.Tags[39].TagValueDT = __GET_VAR(RES0__LIO_3GMODEMON_DT,);
	Modbus_Master_Driver_Instances[0].Tags[14].TagValue = __GET_VAR(RES0__RIO_P1VAR1_POLL,);
}
void setVarsFromDRVTags(){
	__SET_VAR(,RES0__LIO_DITAG0,,LIO_Driver_Instance.Tags[0].TagValue);
	__SET_VAR(,RES0__LIO_DITAG0_STATUS,,LIO_Driver_Instance.Tags[0].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG0_DT,,LIO_Driver_Instance.Tags[0].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG1,,LIO_Driver_Instance.Tags[1].TagValue);
	__SET_VAR(,RES0__LIO_DITAG1_STATUS,,LIO_Driver_Instance.Tags[1].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG1_DT,,LIO_Driver_Instance.Tags[1].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG2,,LIO_Driver_Instance.Tags[2].TagValue);
	__SET_VAR(,RES0__LIO_DITAG2_STATUS,,LIO_Driver_Instance.Tags[2].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG2_DT,,LIO_Driver_Instance.Tags[2].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG3,,LIO_Driver_Instance.Tags[3].TagValue);
	__SET_VAR(,RES0__LIO_DITAG3_STATUS,,LIO_Driver_Instance.Tags[3].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG3_DT,,LIO_Driver_Instance.Tags[3].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG4,,LIO_Driver_Instance.Tags[4].TagValue);
	__SET_VAR(,RES0__LIO_DITAG4_STATUS,,LIO_Driver_Instance.Tags[4].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG4_DT,,LIO_Driver_Instance.Tags[4].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG5,,LIO_Driver_Instance.Tags[5].TagValue);
	__SET_VAR(,RES0__LIO_DITAG5_STATUS,,LIO_Driver_Instance.Tags[5].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG5_DT,,LIO_Driver_Instance.Tags[5].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG6,,LIO_Driver_Instance.Tags[6].TagValue);
	__SET_VAR(,RES0__LIO_DITAG6_STATUS,,LIO_Driver_Instance.Tags[6].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG6_DT,,LIO_Driver_Instance.Tags[6].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG7,,LIO_Driver_Instance.Tags[7].TagValue);
	__SET_VAR(,RES0__LIO_DITAG7_STATUS,,LIO_Driver_Instance.Tags[7].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG7_DT,,LIO_Driver_Instance.Tags[7].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG0,,LIO_Driver_Instance.Tags[12].TagValue);
	__SET_VAR(,RES0__LIO_AITAG0_STATUS,,LIO_Driver_Instance.Tags[12].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG0_DT,,LIO_Driver_Instance.Tags[12].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG1,,LIO_Driver_Instance.Tags[13].TagValue);
	__SET_VAR(,RES0__LIO_AITAG1_STATUS,,LIO_Driver_Instance.Tags[13].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG1_DT,,LIO_Driver_Instance.Tags[13].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG2,,LIO_Driver_Instance.Tags[14].TagValue);
	__SET_VAR(,RES0__LIO_AITAG2_STATUS,,LIO_Driver_Instance.Tags[14].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG2_DT,,LIO_Driver_Instance.Tags[14].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG3,,LIO_Driver_Instance.Tags[15].TagValue);
	__SET_VAR(,RES0__LIO_AITAG3_STATUS,,LIO_Driver_Instance.Tags[15].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG3_DT,,LIO_Driver_Instance.Tags[15].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG0,,LIO_Driver_Instance.Tags[17].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG0_STATUS,,LIO_Driver_Instance.Tags[17].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG0_DT,,LIO_Driver_Instance.Tags[17].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG1,,LIO_Driver_Instance.Tags[18].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG1_STATUS,,LIO_Driver_Instance.Tags[18].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG1_DT,,LIO_Driver_Instance.Tags[18].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG2,,LIO_Driver_Instance.Tags[19].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG2_STATUS,,LIO_Driver_Instance.Tags[19].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG2_DT,,LIO_Driver_Instance.Tags[19].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG3,,LIO_Driver_Instance.Tags[20].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG3_STATUS,,LIO_Driver_Instance.Tags[20].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG3_DT,,LIO_Driver_Instance.Tags[20].TagValueDT);
	__SET_VAR(,RES0__LIO_SENTAG0,,LIO_Driver_Instance.Tags[21].TagValue);
	__SET_VAR(,RES0__LIO_SENTAG0_STATUS,,LIO_Driver_Instance.Tags[21].TagStatus);
	__SET_VAR(,RES0__LIO_SENTAG0_DT,,LIO_Driver_Instance.Tags[21].TagValueDT);
	__SET_VAR(,RES0__LIO_SENTAG1,,LIO_Driver_Instance.Tags[22].TagValue);
	__SET_VAR(,RES0__LIO_SENTAG1_STATUS,,LIO_Driver_Instance.Tags[22].TagStatus);
	__SET_VAR(,RES0__LIO_SENTAG1_DT,,LIO_Driver_Instance.Tags[22].TagValueDT);
	__SET_VAR(,RES0__LIO_CPU_USAGE,,LIO_Driver_Instance.Tags[24].TagValue);
	__SET_VAR(,RES0__LIO_CPU_USAGE_STATUS,,LIO_Driver_Instance.Tags[24].TagStatus);
	__SET_VAR(,RES0__LIO_CPU_USAGE_DT,,LIO_Driver_Instance.Tags[24].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_RAM,,LIO_Driver_Instance.Tags[25].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_RAM_STATUS,,LIO_Driver_Instance.Tags[25].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_RAM_DT,,LIO_Driver_Instance.Tags[25].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_RAM,,LIO_Driver_Instance.Tags[26].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_RAM_STATUS,,LIO_Driver_Instance.Tags[26].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_RAM_DT,,LIO_Driver_Instance.Tags[26].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_RAM,,LIO_Driver_Instance.Tags[27].TagValue);
	__SET_VAR(,RES0__LIO_USED_RAM_STATUS,,LIO_Driver_Instance.Tags[27].TagStatus);
	__SET_VAR(,RES0__LIO_USED_RAM_DT,,LIO_Driver_Instance.Tags[27].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_FLASH,,LIO_Driver_Instance.Tags[28].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_FLASH_STATUS,,LIO_Driver_Instance.Tags[28].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_FLASH_DT,,LIO_Driver_Instance.Tags[28].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_FLASH,,LIO_Driver_Instance.Tags[29].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_FLASH_STATUS,,LIO_Driver_Instance.Tags[29].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_FLASH_DT,,LIO_Driver_Instance.Tags[29].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_FLASH,,LIO_Driver_Instance.Tags[30].TagValue);
	__SET_VAR(,RES0__LIO_USED_FLASH_STATUS,,LIO_Driver_Instance.Tags[30].TagStatus);
	__SET_VAR(,RES0__LIO_USED_FLASH_DT,,LIO_Driver_Instance.Tags[30].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_SDCARD,,LIO_Driver_Instance.Tags[31].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_SDCARD_STATUS,,LIO_Driver_Instance.Tags[31].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_SDCARD_DT,,LIO_Driver_Instance.Tags[31].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_SDCARD,,LIO_Driver_Instance.Tags[32].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_SDCARD_STATUS,,LIO_Driver_Instance.Tags[32].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_SDCARD_DT,,LIO_Driver_Instance.Tags[32].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_SDCARD,,LIO_Driver_Instance.Tags[33].TagValue);
	__SET_VAR(,RES0__LIO_USED_SDCARD_STATUS,,LIO_Driver_Instance.Tags[33].TagStatus);
	__SET_VAR(,RES0__LIO_USED_SDCARD_DT,,LIO_Driver_Instance.Tags[33].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_NVRAM,,LIO_Driver_Instance.Tags[34].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_NVRAM_STATUS,,LIO_Driver_Instance.Tags[34].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_NVRAM_DT,,LIO_Driver_Instance.Tags[34].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_NVRAM,,LIO_Driver_Instance.Tags[35].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_NVRAM_STATUS,,LIO_Driver_Instance.Tags[35].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_NVRAM_DT,,LIO_Driver_Instance.Tags[35].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_NVRAM,,LIO_Driver_Instance.Tags[36].TagValue);
	__SET_VAR(,RES0__LIO_USED_NVRAM_STATUS,,LIO_Driver_Instance.Tags[36].TagStatus);
	__SET_VAR(,RES0__LIO_USED_NVRAM_DT,,LIO_Driver_Instance.Tags[36].TagValueDT);
	__SET_VAR(,RES0__LIO_CANBUS_STATUS,,LIO_Driver_Instance.Tags[37].TagValue);
	__SET_VAR(,RES0__LIO_CANBUS_STATUS_STATUS,,LIO_Driver_Instance.Tags[37].TagStatus);
	__SET_VAR(,RES0__LIO_CANBUS_STATUS_DT,,LIO_Driver_Instance.Tags[37].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL,,LIO_Driver_Instance.Tags[40].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL_STATUS,,LIO_Driver_Instance.Tags[40].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL_DT,,LIO_Driver_Instance.Tags[40].TagValueDT);
	__SET_VAR(,RES0__LIO_3GCONNECTED,,LIO_Driver_Instance.Tags[41].TagValue);
	__SET_VAR(,RES0__LIO_3GCONNECTED_STATUS,,LIO_Driver_Instance.Tags[41].TagStatus);
	__SET_VAR(,RES0__LIO_3GCONNECTED_DT,,LIO_Driver_Instance.Tags[41].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP1,,LIO_Driver_Instance.Tags[42].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP1_STATUS,,LIO_Driver_Instance.Tags[42].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP1_DT,,LIO_Driver_Instance.Tags[42].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP2,,LIO_Driver_Instance.Tags[43].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP2_STATUS,,LIO_Driver_Instance.Tags[43].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP2_DT,,LIO_Driver_Instance.Tags[43].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP3,,LIO_Driver_Instance.Tags[44].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP3_STATUS,,LIO_Driver_Instance.Tags[44].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP3_DT,,LIO_Driver_Instance.Tags[44].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP4,,LIO_Driver_Instance.Tags[45].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP4_STATUS,,LIO_Driver_Instance.Tags[45].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP4_DT,,LIO_Driver_Instance.Tags[45].TagValueDT);
	__SET_VAR(,RES0__LIO_LOGIC_PROCESSING_TIME,,LIO_Driver_Instance.Tags[46].TagValue);
	__SET_VAR(,RES0__LIO_LOGIC_PROCESSING_TIME_STATUS,,LIO_Driver_Instance.Tags[46].TagStatus);
	__SET_VAR(,RES0__LIO_LOGIC_PROCESSING_TIME_DT,,LIO_Driver_Instance.Tags[46].TagValueDT);
	__SET_VAR(,RES0__LIO_FIRST_SCAN,,LIO_Driver_Instance.Tags[47].TagValue);
	__SET_VAR(,RES0__LIO_FIRST_SCAN_STATUS,,LIO_Driver_Instance.Tags[47].TagStatus);
	__SET_VAR(,RES0__LIO_FIRST_SCAN_DT,,LIO_Driver_Instance.Tags[47].TagValueDT);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG0,,Modbus_Master_Driver_Instances[0].Tags[0].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG1,,Modbus_Master_Driver_Instances[0].Tags[1].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG2,,Modbus_Master_Driver_Instances[0].Tags[2].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3,,Modbus_Master_Driver_Instances[0].Tags[3].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG4,,Modbus_Master_Driver_Instances[0].Tags[4].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG5,,Modbus_Master_Driver_Instances[0].Tags[5].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG6,,Modbus_Master_Driver_Instances[0].Tags[6].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG7,,Modbus_Master_Driver_Instances[0].Tags[7].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG8,,Modbus_Master_Driver_Instances[0].Tags[8].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG9,,Modbus_Master_Driver_Instances[0].Tags[9].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[10].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[11].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[12].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_ERROR,,Modbus_Master_Driver_Instances[0].Tags[13].TagValue);
}
