#include "ladder.h"


void setDRVTagsFromVars(){
	LIO_Driver_Instance.Tags[8].TagValue = __GET_VAR(RES0__LIO_DOTAG0,);
	LIO_Driver_Instance.Tags[8].TagStatus = __GET_VAR(RES0__LIO_DOTAG0_STATUS,);
	LIO_Driver_Instance.Tags[8].TagValueDT = __GET_VAR(RES0__LIO_DOTAG0_DT,);
	LIO_Driver_Instance.Tags[9].TagValue = __GET_VAR(RES0__LIO_DOTAG1,);
	LIO_Driver_Instance.Tags[9].TagStatus = __GET_VAR(RES0__LIO_DOTAG1_STATUS,);
	LIO_Driver_Instance.Tags[9].TagValueDT = __GET_VAR(RES0__LIO_DOTAG1_DT,);
	LIO_Driver_Instance.Tags[10].TagValue = __GET_VAR(RES0__LIO_DOTAG2,);
	LIO_Driver_Instance.Tags[10].TagStatus = __GET_VAR(RES0__LIO_DOTAG2_STATUS,);
	LIO_Driver_Instance.Tags[10].TagValueDT = __GET_VAR(RES0__LIO_DOTAG2_DT,);
	LIO_Driver_Instance.Tags[11].TagValue = __GET_VAR(RES0__LIO_DOTAG3,);
	LIO_Driver_Instance.Tags[11].TagStatus = __GET_VAR(RES0__LIO_DOTAG3_STATUS,);
	LIO_Driver_Instance.Tags[11].TagValueDT = __GET_VAR(RES0__LIO_DOTAG3_DT,);
	LIO_Driver_Instance.Tags[16].TagValue = __GET_VAR(RES0__LIO_AOTAG0,);
	LIO_Driver_Instance.Tags[16].TagStatus = __GET_VAR(RES0__LIO_AOTAG0_STATUS,);
	LIO_Driver_Instance.Tags[16].TagValueDT = __GET_VAR(RES0__LIO_AOTAG0_DT,);
	LIO_Driver_Instance.Tags[23].TagValue = __GET_VAR(RES0__LIO_RESET,);
	LIO_Driver_Instance.Tags[23].TagStatus = __GET_VAR(RES0__LIO_RESET_STATUS,);
	LIO_Driver_Instance.Tags[23].TagValueDT = __GET_VAR(RES0__LIO_RESET_DT,);
	LIO_Driver_Instance.Tags[38].TagValue = __GET_VAR(RES0__LIO_BUZZER,);
	LIO_Driver_Instance.Tags[38].TagStatus = __GET_VAR(RES0__LIO_BUZZER_STATUS,);
	LIO_Driver_Instance.Tags[38].TagValueDT = __GET_VAR(RES0__LIO_BUZZER_DT,);
	LIO_Driver_Instance.Tags[39].TagValue = __GET_VAR(RES0__LIO_3GMODEMON,);
	LIO_Driver_Instance.Tags[39].TagStatus = __GET_VAR(RES0__LIO_3GMODEMON_STATUS,);
	LIO_Driver_Instance.Tags[39].TagValueDT = __GET_VAR(RES0__LIO_3GMODEMON_DT,);
	DNP_Slave_Driver_Instances[0].Tags[1].TagValue = __GET_VAR(RES0__DNP_ALARMAC,);
	DNP_Slave_Driver_Instances[0].Tags[1].TagStatus = __GET_VAR(RES0__DNP_ALARMAC_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[1].TagValueDT = __GET_VAR(RES0__DNP_ALARMAC_DT,);
	DNP_Slave_Driver_Instances[0].Tags[2].TagValue = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[2].TagStatus = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[2].TagValueDT = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[3].TagValue = __GET_VAR(RES0__DNP_DC24V,);
	DNP_Slave_Driver_Instances[0].Tags[3].TagStatus = __GET_VAR(RES0__DNP_DC24V_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[3].TagValueDT = __GET_VAR(RES0__DNP_DC24V_DT,);
	DNP_Slave_Driver_Instances[0].Tags[4].TagValue = __GET_VAR(RES0__DNP_FAULTPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[4].TagStatus = __GET_VAR(RES0__DNP_FAULTPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[4].TagValueDT = __GET_VAR(RES0__DNP_FAULTPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[5].TagValue = __GET_VAR(RES0__DNP_ONPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[5].TagStatus = __GET_VAR(RES0__DNP_ONPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[5].TagValueDT = __GET_VAR(RES0__DNP_ONPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[6].TagValue = __GET_VAR(RES0__DNP_AUTOPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[6].TagStatus = __GET_VAR(RES0__DNP_AUTOPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[6].TagValueDT = __GET_VAR(RES0__DNP_AUTOPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[7].TagValue = __GET_VAR(RES0__DNP_FAULTPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[7].TagStatus = __GET_VAR(RES0__DNP_FAULTPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[7].TagValueDT = __GET_VAR(RES0__DNP_FAULTPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[8].TagValue = __GET_VAR(RES0__DNP_ONPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[8].TagStatus = __GET_VAR(RES0__DNP_ONPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[8].TagValueDT = __GET_VAR(RES0__DNP_ONPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[9].TagValue = __GET_VAR(RES0__DNP_AUTOPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[9].TagStatus = __GET_VAR(RES0__DNP_AUTOPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[9].TagValueDT = __GET_VAR(RES0__DNP_AUTOPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[10].TagValue = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[10].TagStatus = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[10].TagValueDT = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[11].TagValue = __GET_VAR(RES0__DNP_FAULTPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[11].TagStatus = __GET_VAR(RES0__DNP_FAULTPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[11].TagValueDT = __GET_VAR(RES0__DNP_FAULTPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[12].TagValue = __GET_VAR(RES0__DNP_ONPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[12].TagStatus = __GET_VAR(RES0__DNP_ONPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[12].TagValueDT = __GET_VAR(RES0__DNP_ONPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[13].TagValue = __GET_VAR(RES0__DNP_AUTOPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[13].TagStatus = __GET_VAR(RES0__DNP_AUTOPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[13].TagValueDT = __GET_VAR(RES0__DNP_AUTOPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[14].TagValue = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[14].TagStatus = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[14].TagValueDT = __GET_VAR(RES0__DNP_SUBSCADAPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[15].TagValue = __GET_VAR(RES0__DNP_ROOMWATERALARM,);
	DNP_Slave_Driver_Instances[0].Tags[15].TagStatus = __GET_VAR(RES0__DNP_ROOMWATERALARM_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[15].TagValueDT = __GET_VAR(RES0__DNP_ROOMWATERALARM_DT,);
	DNP_Slave_Driver_Instances[0].Tags[16].TagValue = __GET_VAR(RES0__DNP_TANKHIALARM,);
	DNP_Slave_Driver_Instances[0].Tags[16].TagStatus = __GET_VAR(RES0__DNP_TANKHIALARM_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[16].TagValueDT = __GET_VAR(RES0__DNP_TANKHIALARM_DT,);
	DNP_Slave_Driver_Instances[0].Tags[17].TagValue = __GET_VAR(RES0__DNP_TANKLOWALARM,);
	DNP_Slave_Driver_Instances[0].Tags[17].TagStatus = __GET_VAR(RES0__DNP_TANKLOWALARM_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[17].TagValueDT = __GET_VAR(RES0__DNP_TANKLOWALARM_DT,);
	DNP_Slave_Driver_Instances[0].Tags[18].TagValue = __GET_VAR(RES0__DNP_PHIPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[18].TagStatus = __GET_VAR(RES0__DNP_PHIPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[18].TagValueDT = __GET_VAR(RES0__DNP_PHIPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[19].TagValue = __GET_VAR(RES0__DNP_PLOWPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[19].TagStatus = __GET_VAR(RES0__DNP_PLOWPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[19].TagValueDT = __GET_VAR(RES0__DNP_PLOWPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[20].TagValue = __GET_VAR(RES0__DNP_PHASE1PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[20].TagStatus = __GET_VAR(RES0__DNP_PHASE1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[20].TagValueDT = __GET_VAR(RES0__DNP_PHASE1PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[21].TagValue = __GET_VAR(RES0__DNP_PHASE2PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[21].TagStatus = __GET_VAR(RES0__DNP_PHASE2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[21].TagValueDT = __GET_VAR(RES0__DNP_PHASE2PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[22].TagValue = __GET_VAR(RES0__DNP_PHASE3PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[22].TagStatus = __GET_VAR(RES0__DNP_PHASE3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[22].TagValueDT = __GET_VAR(RES0__DNP_PHASE3PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[23].TagValue = __GET_VAR(RES0__DNP_PHIPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[23].TagStatus = __GET_VAR(RES0__DNP_PHIPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[23].TagValueDT = __GET_VAR(RES0__DNP_PHIPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[24].TagValue = __GET_VAR(RES0__DNP_PLOWPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[24].TagStatus = __GET_VAR(RES0__DNP_PLOWPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[24].TagValueDT = __GET_VAR(RES0__DNP_PLOWPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[25].TagValue = __GET_VAR(RES0__DNP_PHASE1PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[25].TagStatus = __GET_VAR(RES0__DNP_PHASE1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[25].TagValueDT = __GET_VAR(RES0__DNP_PHASE1PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[26].TagValue = __GET_VAR(RES0__DNP_PHASE2PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[26].TagStatus = __GET_VAR(RES0__DNP_PHASE2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[26].TagValueDT = __GET_VAR(RES0__DNP_PHASE2PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[27].TagValue = __GET_VAR(RES0__DNP_PHASE3PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[27].TagStatus = __GET_VAR(RES0__DNP_PHASE3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[27].TagValueDT = __GET_VAR(RES0__DNP_PHASE3PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[28].TagValue = __GET_VAR(RES0__DNP_PHIPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[28].TagStatus = __GET_VAR(RES0__DNP_PHIPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[28].TagValueDT = __GET_VAR(RES0__DNP_PHIPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[29].TagValue = __GET_VAR(RES0__DNP_PLOWPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[29].TagStatus = __GET_VAR(RES0__DNP_PLOWPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[29].TagValueDT = __GET_VAR(RES0__DNP_PLOWPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[30].TagValue = __GET_VAR(RES0__DNP_PHASE1PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[30].TagStatus = __GET_VAR(RES0__DNP_PHASE1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[30].TagValueDT = __GET_VAR(RES0__DNP_PHASE1PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[31].TagValue = __GET_VAR(RES0__DNP_PHASE2PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[31].TagStatus = __GET_VAR(RES0__DNP_PHASE2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[31].TagValueDT = __GET_VAR(RES0__DNP_PHASE2PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[32].TagValue = __GET_VAR(RES0__DNP_PHASE3PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[32].TagStatus = __GET_VAR(RES0__DNP_PHASE3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[32].TagValueDT = __GET_VAR(RES0__DNP_PHASE3PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[33].TagValue = __GET_VAR(RES0__DNP_PHITOTAL,);
	DNP_Slave_Driver_Instances[0].Tags[33].TagStatus = __GET_VAR(RES0__DNP_PHITOTAL_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[33].TagValueDT = __GET_VAR(RES0__DNP_PHITOTAL_DT,);
	DNP_Slave_Driver_Instances[0].Tags[34].TagValue = __GET_VAR(RES0__DNP_PLOWTOTAL,);
	DNP_Slave_Driver_Instances[0].Tags[34].TagStatus = __GET_VAR(RES0__DNP_PLOWTOTAL_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[34].TagValueDT = __GET_VAR(RES0__DNP_PLOWTOTAL_DT,);
	DNP_Slave_Driver_Instances[0].Tags[35].TagValue = __GET_VAR(RES0__DNP_FHITOTAL1,);
	DNP_Slave_Driver_Instances[0].Tags[35].TagStatus = __GET_VAR(RES0__DNP_FHITOTAL1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[35].TagValueDT = __GET_VAR(RES0__DNP_FHITOTAL1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[36].TagValue = __GET_VAR(RES0__DNP_FLOWTOTAL1,);
	DNP_Slave_Driver_Instances[0].Tags[36].TagStatus = __GET_VAR(RES0__DNP_FLOWTOTAL1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[36].TagValueDT = __GET_VAR(RES0__DNP_FLOWTOTAL1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[37].TagValue = __GET_VAR(RES0__DNP_FHITOTAL2,);
	DNP_Slave_Driver_Instances[0].Tags[37].TagStatus = __GET_VAR(RES0__DNP_FHITOTAL2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[37].TagValueDT = __GET_VAR(RES0__DNP_FHITOTAL2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[38].TagValue = __GET_VAR(RES0__DNP_FLOWTOTAL2,);
	DNP_Slave_Driver_Instances[0].Tags[38].TagStatus = __GET_VAR(RES0__DNP_FLOWTOTAL2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[38].TagValueDT = __GET_VAR(RES0__DNP_FLOWTOTAL2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[39].TagValue = __GET_VAR(RES0__DNP_PTPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[39].TagStatus = __GET_VAR(RES0__DNP_PTPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[39].TagValueDT = __GET_VAR(RES0__DNP_PTPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[40].TagValue = __GET_VAR(RES0__DNP_PTPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[40].TagStatus = __GET_VAR(RES0__DNP_PTPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[40].TagValueDT = __GET_VAR(RES0__DNP_PTPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[41].TagValue = __GET_VAR(RES0__DNP_PTPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[41].TagStatus = __GET_VAR(RES0__DNP_PTPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[41].TagValueDT = __GET_VAR(RES0__DNP_PTPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[42].TagValue = __GET_VAR(RES0__DNP_PTCOLLECTOR,);
	DNP_Slave_Driver_Instances[0].Tags[42].TagStatus = __GET_VAR(RES0__DNP_PTCOLLECTOR_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[42].TagValueDT = __GET_VAR(RES0__DNP_PTCOLLECTOR_DT,);
	DNP_Slave_Driver_Instances[0].Tags[43].TagValue = __GET_VAR(RES0__DNP_MALEVELMAINTANK,);
	DNP_Slave_Driver_Instances[0].Tags[43].TagStatus = __GET_VAR(RES0__DNP_MALEVELMAINTANK_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[43].TagValueDT = __GET_VAR(RES0__DNP_MALEVELMAINTANK_DT,);
	DNP_Slave_Driver_Instances[0].Tags[44].TagValue = __GET_VAR(RES0__DNP_MACHL,);
	DNP_Slave_Driver_Instances[0].Tags[44].TagStatus = __GET_VAR(RES0__DNP_MACHL_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[44].TagValueDT = __GET_VAR(RES0__DNP_MACHL_DT,);
	DNP_Slave_Driver_Instances[0].Tags[45].TagValue = __GET_VAR(RES0__DNP_MAWF1,);
	DNP_Slave_Driver_Instances[0].Tags[45].TagStatus = __GET_VAR(RES0__DNP_MAWF1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[45].TagValueDT = __GET_VAR(RES0__DNP_MAWF1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[46].TagValue = __GET_VAR(RES0__DNP_MAWF2,);
	DNP_Slave_Driver_Instances[0].Tags[46].TagStatus = __GET_VAR(RES0__DNP_MAWF2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[46].TagValueDT = __GET_VAR(RES0__DNP_MAWF2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[47].TagValue = __GET_VAR(RES0__DNP_I1PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[47].TagStatus = __GET_VAR(RES0__DNP_I1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[47].TagValueDT = __GET_VAR(RES0__DNP_I1PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[48].TagValue = __GET_VAR(RES0__DNP_I2PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[48].TagStatus = __GET_VAR(RES0__DNP_I2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[48].TagValueDT = __GET_VAR(RES0__DNP_I2PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[49].TagValue = __GET_VAR(RES0__DNP_I3PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[49].TagStatus = __GET_VAR(RES0__DNP_I3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[49].TagValueDT = __GET_VAR(RES0__DNP_I3PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[50].TagValue = __GET_VAR(RES0__DNP_V1PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[50].TagStatus = __GET_VAR(RES0__DNP_V1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[50].TagValueDT = __GET_VAR(RES0__DNP_V1PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[51].TagValue = __GET_VAR(RES0__DNP_V2PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[51].TagStatus = __GET_VAR(RES0__DNP_V2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[51].TagValueDT = __GET_VAR(RES0__DNP_V2PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[52].TagValue = __GET_VAR(RES0__DNP_V3PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[52].TagStatus = __GET_VAR(RES0__DNP_V3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[52].TagValueDT = __GET_VAR(RES0__DNP_V3PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[53].TagValue = __GET_VAR(RES0__DNP_V12PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[53].TagStatus = __GET_VAR(RES0__DNP_V12PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[53].TagValueDT = __GET_VAR(RES0__DNP_V12PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[54].TagValue = __GET_VAR(RES0__DNP_V23PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[54].TagStatus = __GET_VAR(RES0__DNP_V23PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[54].TagValueDT = __GET_VAR(RES0__DNP_V23PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[55].TagValue = __GET_VAR(RES0__DNP_V31PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[55].TagStatus = __GET_VAR(RES0__DNP_V31PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[55].TagValueDT = __GET_VAR(RES0__DNP_V31PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[56].TagValue = __GET_VAR(RES0__DNP_P1PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[56].TagStatus = __GET_VAR(RES0__DNP_P1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[56].TagValueDT = __GET_VAR(RES0__DNP_P1PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[57].TagValue = __GET_VAR(RES0__DNP_P2PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[57].TagStatus = __GET_VAR(RES0__DNP_P2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[57].TagValueDT = __GET_VAR(RES0__DNP_P2PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[58].TagValue = __GET_VAR(RES0__DNP_P3PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[58].TagStatus = __GET_VAR(RES0__DNP_P3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[58].TagValueDT = __GET_VAR(RES0__DNP_P3PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[59].TagValue = __GET_VAR(RES0__DNP_Q1PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[59].TagStatus = __GET_VAR(RES0__DNP_Q1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[59].TagValueDT = __GET_VAR(RES0__DNP_Q1PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[60].TagValue = __GET_VAR(RES0__DNP_Q2PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[60].TagStatus = __GET_VAR(RES0__DNP_Q2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[60].TagValueDT = __GET_VAR(RES0__DNP_Q2PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[61].TagValue = __GET_VAR(RES0__DNP_Q3PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[61].TagStatus = __GET_VAR(RES0__DNP_Q3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[61].TagValueDT = __GET_VAR(RES0__DNP_Q3PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[62].TagValue = __GET_VAR(RES0__DNP_S1PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[62].TagStatus = __GET_VAR(RES0__DNP_S1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[62].TagValueDT = __GET_VAR(RES0__DNP_S1PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[63].TagValue = __GET_VAR(RES0__DNP_S2PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[63].TagStatus = __GET_VAR(RES0__DNP_S2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[63].TagValueDT = __GET_VAR(RES0__DNP_S2PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[64].TagValue = __GET_VAR(RES0__DNP_S3PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[64].TagStatus = __GET_VAR(RES0__DNP_S3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[64].TagValueDT = __GET_VAR(RES0__DNP_S3PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[65].TagValue = __GET_VAR(RES0__DNP_PF1PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[65].TagStatus = __GET_VAR(RES0__DNP_PF1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[65].TagValueDT = __GET_VAR(RES0__DNP_PF1PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[66].TagValue = __GET_VAR(RES0__DNP_PF2PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[66].TagStatus = __GET_VAR(RES0__DNP_PF2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[66].TagValueDT = __GET_VAR(RES0__DNP_PF2PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[67].TagValue = __GET_VAR(RES0__DNP_PF3PUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[67].TagStatus = __GET_VAR(RES0__DNP_PF3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[67].TagValueDT = __GET_VAR(RES0__DNP_PF3PUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[68].TagValue = __GET_VAR(RES0__DNP_PAVPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[68].TagStatus = __GET_VAR(RES0__DNP_PAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[68].TagValueDT = __GET_VAR(RES0__DNP_PAVPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[69].TagValue = __GET_VAR(RES0__DNP_QAVPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[69].TagStatus = __GET_VAR(RES0__DNP_QAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[69].TagValueDT = __GET_VAR(RES0__DNP_QAVPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[70].TagValue = __GET_VAR(RES0__DNP_SAVPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[70].TagStatus = __GET_VAR(RES0__DNP_SAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[70].TagValueDT = __GET_VAR(RES0__DNP_SAVPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[71].TagValue = __GET_VAR(RES0__DNP_PFAVPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[71].TagStatus = __GET_VAR(RES0__DNP_PFAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[71].TagValueDT = __GET_VAR(RES0__DNP_PFAVPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[72].TagValue = __GET_VAR(RES0__DNP_FREQPUMPAG1,);
	DNP_Slave_Driver_Instances[0].Tags[72].TagStatus = __GET_VAR(RES0__DNP_FREQPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[72].TagValueDT = __GET_VAR(RES0__DNP_FREQPUMPAG1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[73].TagValue = __GET_VAR(RES0__DNP_I1PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[73].TagStatus = __GET_VAR(RES0__DNP_I1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[73].TagValueDT = __GET_VAR(RES0__DNP_I1PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[74].TagValue = __GET_VAR(RES0__DNP_I2PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[74].TagStatus = __GET_VAR(RES0__DNP_I2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[74].TagValueDT = __GET_VAR(RES0__DNP_I2PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[75].TagValue = __GET_VAR(RES0__DNP_I3PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[75].TagStatus = __GET_VAR(RES0__DNP_I3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[75].TagValueDT = __GET_VAR(RES0__DNP_I3PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[76].TagValue = __GET_VAR(RES0__DNP_V1PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[76].TagStatus = __GET_VAR(RES0__DNP_V1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[76].TagValueDT = __GET_VAR(RES0__DNP_V1PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[77].TagValue = __GET_VAR(RES0__DNP_V2PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[77].TagStatus = __GET_VAR(RES0__DNP_V2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[77].TagValueDT = __GET_VAR(RES0__DNP_V2PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[78].TagValue = __GET_VAR(RES0__DNP_V3PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[78].TagStatus = __GET_VAR(RES0__DNP_V3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[78].TagValueDT = __GET_VAR(RES0__DNP_V3PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[79].TagValue = __GET_VAR(RES0__DNP_V12PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[79].TagStatus = __GET_VAR(RES0__DNP_V12PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[79].TagValueDT = __GET_VAR(RES0__DNP_V12PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[80].TagValue = __GET_VAR(RES0__DNP_V23PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[80].TagStatus = __GET_VAR(RES0__DNP_V23PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[80].TagValueDT = __GET_VAR(RES0__DNP_V23PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[81].TagValue = __GET_VAR(RES0__DNP_V31PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[81].TagStatus = __GET_VAR(RES0__DNP_V31PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[81].TagValueDT = __GET_VAR(RES0__DNP_V31PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[82].TagValue = __GET_VAR(RES0__DNP_P1PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[82].TagStatus = __GET_VAR(RES0__DNP_P1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[82].TagValueDT = __GET_VAR(RES0__DNP_P1PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[83].TagValue = __GET_VAR(RES0__DNP_P2PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[83].TagStatus = __GET_VAR(RES0__DNP_P2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[83].TagValueDT = __GET_VAR(RES0__DNP_P2PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[84].TagValue = __GET_VAR(RES0__DNP_P3PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[84].TagStatus = __GET_VAR(RES0__DNP_P3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[84].TagValueDT = __GET_VAR(RES0__DNP_P3PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[85].TagValue = __GET_VAR(RES0__DNP_Q1PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[85].TagStatus = __GET_VAR(RES0__DNP_Q1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[85].TagValueDT = __GET_VAR(RES0__DNP_Q1PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[86].TagValue = __GET_VAR(RES0__DNP_Q2PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[86].TagStatus = __GET_VAR(RES0__DNP_Q2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[86].TagValueDT = __GET_VAR(RES0__DNP_Q2PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[87].TagValue = __GET_VAR(RES0__DNP_Q3PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[87].TagStatus = __GET_VAR(RES0__DNP_Q3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[87].TagValueDT = __GET_VAR(RES0__DNP_Q3PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[88].TagValue = __GET_VAR(RES0__DNP_S1PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[88].TagStatus = __GET_VAR(RES0__DNP_S1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[88].TagValueDT = __GET_VAR(RES0__DNP_S1PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[89].TagValue = __GET_VAR(RES0__DNP_S2PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[89].TagStatus = __GET_VAR(RES0__DNP_S2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[89].TagValueDT = __GET_VAR(RES0__DNP_S2PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[90].TagValue = __GET_VAR(RES0__DNP_S3PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[90].TagStatus = __GET_VAR(RES0__DNP_S3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[90].TagValueDT = __GET_VAR(RES0__DNP_S3PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[91].TagValue = __GET_VAR(RES0__DNP_PF1PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[91].TagStatus = __GET_VAR(RES0__DNP_PF1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[91].TagValueDT = __GET_VAR(RES0__DNP_PF1PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[92].TagValue = __GET_VAR(RES0__DNP_PF2PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[92].TagStatus = __GET_VAR(RES0__DNP_PF2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[92].TagValueDT = __GET_VAR(RES0__DNP_PF2PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[93].TagValue = __GET_VAR(RES0__DNP_PF3PUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[93].TagStatus = __GET_VAR(RES0__DNP_PF3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[93].TagValueDT = __GET_VAR(RES0__DNP_PF3PUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[94].TagValue = __GET_VAR(RES0__DNP_PAVPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[94].TagStatus = __GET_VAR(RES0__DNP_PAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[94].TagValueDT = __GET_VAR(RES0__DNP_PAVPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[95].TagValue = __GET_VAR(RES0__DNP_QAVPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[95].TagStatus = __GET_VAR(RES0__DNP_QAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[95].TagValueDT = __GET_VAR(RES0__DNP_QAVPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[96].TagValue = __GET_VAR(RES0__DNP_SAVPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[96].TagStatus = __GET_VAR(RES0__DNP_SAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[96].TagValueDT = __GET_VAR(RES0__DNP_SAVPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[97].TagValue = __GET_VAR(RES0__DNP_PFAVPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[97].TagStatus = __GET_VAR(RES0__DNP_PFAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[97].TagValueDT = __GET_VAR(RES0__DNP_PFAVPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[98].TagValue = __GET_VAR(RES0__DNP_FREQPUMPAG2,);
	DNP_Slave_Driver_Instances[0].Tags[98].TagStatus = __GET_VAR(RES0__DNP_FREQPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[98].TagValueDT = __GET_VAR(RES0__DNP_FREQPUMPAG2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[99].TagValue = __GET_VAR(RES0__DNP_I1PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[99].TagStatus = __GET_VAR(RES0__DNP_I1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[99].TagValueDT = __GET_VAR(RES0__DNP_I1PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[100].TagValue = __GET_VAR(RES0__DNP_I2PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[100].TagStatus = __GET_VAR(RES0__DNP_I2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[100].TagValueDT = __GET_VAR(RES0__DNP_I2PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[101].TagValue = __GET_VAR(RES0__DNP_I3PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[101].TagStatus = __GET_VAR(RES0__DNP_I3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[101].TagValueDT = __GET_VAR(RES0__DNP_I3PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[102].TagValue = __GET_VAR(RES0__DNP_V1PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[102].TagStatus = __GET_VAR(RES0__DNP_V1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[102].TagValueDT = __GET_VAR(RES0__DNP_V1PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[103].TagValue = __GET_VAR(RES0__DNP_V2PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[103].TagStatus = __GET_VAR(RES0__DNP_V2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[103].TagValueDT = __GET_VAR(RES0__DNP_V2PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[104].TagValue = __GET_VAR(RES0__DNP_V3PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[104].TagStatus = __GET_VAR(RES0__DNP_V3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[104].TagValueDT = __GET_VAR(RES0__DNP_V3PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[105].TagValue = __GET_VAR(RES0__DNP_V12PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[105].TagStatus = __GET_VAR(RES0__DNP_V12PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[105].TagValueDT = __GET_VAR(RES0__DNP_V12PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[106].TagValue = __GET_VAR(RES0__DNP_V23PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[106].TagStatus = __GET_VAR(RES0__DNP_V23PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[106].TagValueDT = __GET_VAR(RES0__DNP_V23PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[107].TagValue = __GET_VAR(RES0__DNP_V31PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[107].TagStatus = __GET_VAR(RES0__DNP_V31PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[107].TagValueDT = __GET_VAR(RES0__DNP_V31PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[108].TagValue = __GET_VAR(RES0__DNP_P1PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[108].TagStatus = __GET_VAR(RES0__DNP_P1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[108].TagValueDT = __GET_VAR(RES0__DNP_P1PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[109].TagValue = __GET_VAR(RES0__DNP_P2PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[109].TagStatus = __GET_VAR(RES0__DNP_P2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[109].TagValueDT = __GET_VAR(RES0__DNP_P2PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[110].TagValue = __GET_VAR(RES0__DNP_P3PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[110].TagStatus = __GET_VAR(RES0__DNP_P3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[110].TagValueDT = __GET_VAR(RES0__DNP_P3PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[111].TagValue = __GET_VAR(RES0__DNP_Q1PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[111].TagStatus = __GET_VAR(RES0__DNP_Q1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[111].TagValueDT = __GET_VAR(RES0__DNP_Q1PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[112].TagValue = __GET_VAR(RES0__DNP_Q2PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[112].TagStatus = __GET_VAR(RES0__DNP_Q2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[112].TagValueDT = __GET_VAR(RES0__DNP_Q2PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[113].TagValue = __GET_VAR(RES0__DNP_Q3PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[113].TagStatus = __GET_VAR(RES0__DNP_Q3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[113].TagValueDT = __GET_VAR(RES0__DNP_Q3PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[114].TagValue = __GET_VAR(RES0__DNP_S1PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[114].TagStatus = __GET_VAR(RES0__DNP_S1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[114].TagValueDT = __GET_VAR(RES0__DNP_S1PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[115].TagValue = __GET_VAR(RES0__DNP_S2PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[115].TagStatus = __GET_VAR(RES0__DNP_S2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[115].TagValueDT = __GET_VAR(RES0__DNP_S2PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[116].TagValue = __GET_VAR(RES0__DNP_S3PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[116].TagStatus = __GET_VAR(RES0__DNP_S3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[116].TagValueDT = __GET_VAR(RES0__DNP_S3PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[117].TagValue = __GET_VAR(RES0__DNP_PF1PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[117].TagStatus = __GET_VAR(RES0__DNP_PF1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[117].TagValueDT = __GET_VAR(RES0__DNP_PF1PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[118].TagValue = __GET_VAR(RES0__DNP_PF2PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[118].TagStatus = __GET_VAR(RES0__DNP_PF2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[118].TagValueDT = __GET_VAR(RES0__DNP_PF2PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[119].TagValue = __GET_VAR(RES0__DNP_PF3PUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[119].TagStatus = __GET_VAR(RES0__DNP_PF3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[119].TagValueDT = __GET_VAR(RES0__DNP_PF3PUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[120].TagValue = __GET_VAR(RES0__DNP_PAVPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[120].TagStatus = __GET_VAR(RES0__DNP_PAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[120].TagValueDT = __GET_VAR(RES0__DNP_PAVPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[121].TagValue = __GET_VAR(RES0__DNP_QAVPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[121].TagStatus = __GET_VAR(RES0__DNP_QAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[121].TagValueDT = __GET_VAR(RES0__DNP_QAVPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[122].TagValue = __GET_VAR(RES0__DNP_SAVPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[122].TagStatus = __GET_VAR(RES0__DNP_SAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[122].TagValueDT = __GET_VAR(RES0__DNP_SAVPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[123].TagValue = __GET_VAR(RES0__DNP_PFAVPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[123].TagStatus = __GET_VAR(RES0__DNP_PFAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[123].TagValueDT = __GET_VAR(RES0__DNP_PFAVPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[124].TagValue = __GET_VAR(RES0__DNP_FREQPUMPAG3,);
	DNP_Slave_Driver_Instances[0].Tags[124].TagStatus = __GET_VAR(RES0__DNP_FREQPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[124].TagValueDT = __GET_VAR(RES0__DNP_FREQPUMPAG3_DT,);
	DNP_Slave_Driver_Instances[0].Tags[131].TagValue = __GET_VAR(RES0__DNP_RS485WF1,);
	DNP_Slave_Driver_Instances[0].Tags[131].TagStatus = __GET_VAR(RES0__DNP_RS485WF1_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[131].TagValueDT = __GET_VAR(RES0__DNP_RS485WF1_DT,);
	DNP_Slave_Driver_Instances[0].Tags[132].TagValue = __GET_VAR(RES0__DNP_RS485WF2,);
	DNP_Slave_Driver_Instances[0].Tags[132].TagStatus = __GET_VAR(RES0__DNP_RS485WF2_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[132].TagValueDT = __GET_VAR(RES0__DNP_RS485WF2_DT,);
	DNP_Slave_Driver_Instances[0].Tags[133].TagValue = __GET_VAR(RES0__DNP_RS485LEVELMETER,);
	DNP_Slave_Driver_Instances[0].Tags[133].TagStatus = __GET_VAR(RES0__DNP_RS485LEVELMETER_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[133].TagValueDT = __GET_VAR(RES0__DNP_RS485LEVELMETER_DT,);
	DNP_Slave_Driver_Instances[0].Tags[134].TagValue = __GET_VAR(RES0__DNP_CL,);
	DNP_Slave_Driver_Instances[0].Tags[134].TagStatus = __GET_VAR(RES0__DNP_CL_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[134].TagValueDT = __GET_VAR(RES0__DNP_CL_DT,);
	DNP_Slave_Driver_Instances[0].Tags[135].TagValue = __GET_VAR(RES0__DNP_TU,);
	DNP_Slave_Driver_Instances[0].Tags[135].TagStatus = __GET_VAR(RES0__DNP_TU_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[135].TagValueDT = __GET_VAR(RES0__DNP_TU_DT,);
	DNP_Slave_Driver_Instances[0].Tags[136].TagValue = __GET_VAR(RES0__DNP_TH,);
	DNP_Slave_Driver_Instances[0].Tags[136].TagStatus = __GET_VAR(RES0__DNP_TH_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[136].TagValueDT = __GET_VAR(RES0__DNP_TH_DT,);
	DNP_Slave_Driver_Instances[0].Tags[137].TagValue = __GET_VAR(RES0__DNP_EC,);
	DNP_Slave_Driver_Instances[0].Tags[137].TagStatus = __GET_VAR(RES0__DNP_EC_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[137].TagValueDT = __GET_VAR(RES0__DNP_EC_DT,);
	DNP_Slave_Driver_Instances[0].Tags[138].TagValue = __GET_VAR(RES0__DNP_DITAG1000,);
	DNP_Slave_Driver_Instances[0].Tags[138].TagStatus = __GET_VAR(RES0__DNP_DITAG1000_STATUS,);
	DNP_Slave_Driver_Instances[0].Tags[138].TagValueDT = __GET_VAR(RES0__DNP_DITAG1000_DT,);
	DNP_Slave_Driver_Instances[1].Tags[0].TagValue = __GET_VAR(RES0__DNP2_OPENDOOR,);
	DNP_Slave_Driver_Instances[1].Tags[0].TagStatus = __GET_VAR(RES0__DNP2_OPENDOOR_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[1].TagValue = __GET_VAR(RES0__DNP2_ALARMAC,);
	DNP_Slave_Driver_Instances[1].Tags[1].TagStatus = __GET_VAR(RES0__DNP2_ALARMAC_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[2].TagValue = __GET_VAR(RES0__DNP2_SUBSCADAPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[2].TagStatus = __GET_VAR(RES0__DNP2_SUBSCADAPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[3].TagValue = __GET_VAR(RES0__DNP2_DC24V,);
	DNP_Slave_Driver_Instances[1].Tags[3].TagStatus = __GET_VAR(RES0__DNP2_DC24V_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[4].TagValue = __GET_VAR(RES0__DNP2_FAULTPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[4].TagStatus = __GET_VAR(RES0__DNP2_FAULTPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[5].TagValue = __GET_VAR(RES0__DNP2_ONPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[5].TagStatus = __GET_VAR(RES0__DNP2_ONPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[6].TagValue = __GET_VAR(RES0__DNP2_AUTOPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[6].TagStatus = __GET_VAR(RES0__DNP2_AUTOPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[7].TagValue = __GET_VAR(RES0__DNP2_FAULTPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[7].TagStatus = __GET_VAR(RES0__DNP2_FAULTPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[8].TagValue = __GET_VAR(RES0__DNP2_ONPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[8].TagStatus = __GET_VAR(RES0__DNP2_ONPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[9].TagValue = __GET_VAR(RES0__DNP2_AUTOPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[9].TagStatus = __GET_VAR(RES0__DNP2_AUTOPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[10].TagValue = __GET_VAR(RES0__DNP2_SUBSCADAPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[10].TagStatus = __GET_VAR(RES0__DNP2_SUBSCADAPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[11].TagValue = __GET_VAR(RES0__DNP2_FAULTPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[11].TagStatus = __GET_VAR(RES0__DNP2_FAULTPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[12].TagValue = __GET_VAR(RES0__DNP2_ONPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[12].TagStatus = __GET_VAR(RES0__DNP2_ONPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[13].TagValue = __GET_VAR(RES0__DNP2_AUTOPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[13].TagStatus = __GET_VAR(RES0__DNP2_AUTOPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[14].TagValue = __GET_VAR(RES0__DNP2_SUBSCADAPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[14].TagStatus = __GET_VAR(RES0__DNP2_SUBSCADAPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[15].TagValue = __GET_VAR(RES0__DNP2_ROOMWATERALARM,);
	DNP_Slave_Driver_Instances[1].Tags[15].TagStatus = __GET_VAR(RES0__DNP2_ROOMWATERALARM_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[16].TagValue = __GET_VAR(RES0__DNP2_TANKHIALARM,);
	DNP_Slave_Driver_Instances[1].Tags[16].TagStatus = __GET_VAR(RES0__DNP2_TANKHIALARM_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[17].TagValue = __GET_VAR(RES0__DNP2_TANKLOWALARM,);
	DNP_Slave_Driver_Instances[1].Tags[17].TagStatus = __GET_VAR(RES0__DNP2_TANKLOWALARM_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[18].TagValue = __GET_VAR(RES0__DNP2_PHIPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[18].TagStatus = __GET_VAR(RES0__DNP2_PHIPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[19].TagValue = __GET_VAR(RES0__DNP2_PLOWPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[19].TagStatus = __GET_VAR(RES0__DNP2_PLOWPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[20].TagValue = __GET_VAR(RES0__DNP2_PHASE1PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[20].TagStatus = __GET_VAR(RES0__DNP2_PHASE1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[21].TagValue = __GET_VAR(RES0__DNP2_PHASE2PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[21].TagStatus = __GET_VAR(RES0__DNP2_PHASE2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[22].TagValue = __GET_VAR(RES0__DNP2_PHASE3PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[22].TagStatus = __GET_VAR(RES0__DNP2_PHASE3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[23].TagValue = __GET_VAR(RES0__DNP2_PHIPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[23].TagStatus = __GET_VAR(RES0__DNP2_PHIPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[24].TagValue = __GET_VAR(RES0__DNP2_PLOWPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[24].TagStatus = __GET_VAR(RES0__DNP2_PLOWPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[25].TagValue = __GET_VAR(RES0__DNP2_PHASE1PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[25].TagStatus = __GET_VAR(RES0__DNP2_PHASE1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[26].TagValue = __GET_VAR(RES0__DNP2_PHASE2PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[26].TagStatus = __GET_VAR(RES0__DNP2_PHASE2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[27].TagValue = __GET_VAR(RES0__DNP2_PHASE3PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[27].TagStatus = __GET_VAR(RES0__DNP2_PHASE3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[28].TagValue = __GET_VAR(RES0__DNP2_PHIPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[28].TagStatus = __GET_VAR(RES0__DNP2_PHIPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[29].TagValue = __GET_VAR(RES0__DNP2_PLOWPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[29].TagStatus = __GET_VAR(RES0__DNP2_PLOWPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[30].TagValue = __GET_VAR(RES0__DNP2_PHASE1PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[30].TagStatus = __GET_VAR(RES0__DNP2_PHASE1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[31].TagValue = __GET_VAR(RES0__DNP2_PHASE2PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[31].TagStatus = __GET_VAR(RES0__DNP2_PHASE2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[32].TagValue = __GET_VAR(RES0__DNP2_PHASE3PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[32].TagStatus = __GET_VAR(RES0__DNP2_PHASE3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[33].TagValue = __GET_VAR(RES0__DNP2_PHITOTAL,);
	DNP_Slave_Driver_Instances[1].Tags[33].TagStatus = __GET_VAR(RES0__DNP2_PHITOTAL_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[34].TagValue = __GET_VAR(RES0__DNP2_PLOWTOTAL,);
	DNP_Slave_Driver_Instances[1].Tags[34].TagStatus = __GET_VAR(RES0__DNP2_PLOWTOTAL_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[35].TagValue = __GET_VAR(RES0__DNP2_FHITOTAL1,);
	DNP_Slave_Driver_Instances[1].Tags[35].TagStatus = __GET_VAR(RES0__DNP2_FHITOTAL1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[36].TagValue = __GET_VAR(RES0__DNP2_FLOWTOTAL1,);
	DNP_Slave_Driver_Instances[1].Tags[36].TagStatus = __GET_VAR(RES0__DNP2_FLOWTOTAL1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[37].TagValue = __GET_VAR(RES0__DNP2_FHITOTAL2,);
	DNP_Slave_Driver_Instances[1].Tags[37].TagStatus = __GET_VAR(RES0__DNP2_FHITOTAL2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[38].TagValue = __GET_VAR(RES0__DNP2_FLOWTOTAL2,);
	DNP_Slave_Driver_Instances[1].Tags[38].TagStatus = __GET_VAR(RES0__DNP2_FLOWTOTAL2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[39].TagValue = __GET_VAR(RES0__DNP2_PTPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[39].TagStatus = __GET_VAR(RES0__DNP2_PTPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[40].TagValue = __GET_VAR(RES0__DNP2_PTPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[40].TagStatus = __GET_VAR(RES0__DNP2_PTPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[41].TagValue = __GET_VAR(RES0__DNP2_PTPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[41].TagStatus = __GET_VAR(RES0__DNP2_PTPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[42].TagValue = __GET_VAR(RES0__DNP2_PTCOLLECTOR,);
	DNP_Slave_Driver_Instances[1].Tags[42].TagStatus = __GET_VAR(RES0__DNP2_PTCOLLECTOR_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[43].TagValue = __GET_VAR(RES0__DNP2_MALEVELMAINTANK,);
	DNP_Slave_Driver_Instances[1].Tags[43].TagStatus = __GET_VAR(RES0__DNP2_MALEVELMAINTANK_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[44].TagValue = __GET_VAR(RES0__DNP2_MACHL,);
	DNP_Slave_Driver_Instances[1].Tags[44].TagStatus = __GET_VAR(RES0__DNP2_MACHL_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[45].TagValue = __GET_VAR(RES0__DNP2_MAWF1,);
	DNP_Slave_Driver_Instances[1].Tags[45].TagStatus = __GET_VAR(RES0__DNP2_MAWF1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[46].TagValue = __GET_VAR(RES0__DNP2_MAWF2,);
	DNP_Slave_Driver_Instances[1].Tags[46].TagStatus = __GET_VAR(RES0__DNP2_MAWF2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[47].TagValue = __GET_VAR(RES0__DNP2_I1PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[47].TagStatus = __GET_VAR(RES0__DNP2_I1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[48].TagValue = __GET_VAR(RES0__DNP2_I2PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[48].TagStatus = __GET_VAR(RES0__DNP2_I2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[49].TagValue = __GET_VAR(RES0__DNP2_I3PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[49].TagStatus = __GET_VAR(RES0__DNP2_I3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[50].TagValue = __GET_VAR(RES0__DNP2_V1PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[50].TagStatus = __GET_VAR(RES0__DNP2_V1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[51].TagValue = __GET_VAR(RES0__DNP2_V2PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[51].TagStatus = __GET_VAR(RES0__DNP2_V2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[52].TagValue = __GET_VAR(RES0__DNP2_V3PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[52].TagStatus = __GET_VAR(RES0__DNP2_V3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[53].TagValue = __GET_VAR(RES0__DNP2_V12PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[53].TagStatus = __GET_VAR(RES0__DNP2_V12PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[54].TagValue = __GET_VAR(RES0__DNP2_V23PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[54].TagStatus = __GET_VAR(RES0__DNP2_V23PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[55].TagValue = __GET_VAR(RES0__DNP2_V31PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[55].TagStatus = __GET_VAR(RES0__DNP2_V31PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[56].TagValue = __GET_VAR(RES0__DNP2_P1PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[56].TagStatus = __GET_VAR(RES0__DNP2_P1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[57].TagValue = __GET_VAR(RES0__DNP2_P2PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[57].TagStatus = __GET_VAR(RES0__DNP2_P2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[58].TagValue = __GET_VAR(RES0__DNP2_P3PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[58].TagStatus = __GET_VAR(RES0__DNP2_P3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[59].TagValue = __GET_VAR(RES0__DNP2_Q1PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[59].TagStatus = __GET_VAR(RES0__DNP2_Q1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[60].TagValue = __GET_VAR(RES0__DNP2_Q2PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[60].TagStatus = __GET_VAR(RES0__DNP2_Q2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[61].TagValue = __GET_VAR(RES0__DNP2_Q3PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[61].TagStatus = __GET_VAR(RES0__DNP2_Q3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[62].TagValue = __GET_VAR(RES0__DNP2_S1PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[62].TagStatus = __GET_VAR(RES0__DNP2_S1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[63].TagValue = __GET_VAR(RES0__DNP2_S2PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[63].TagStatus = __GET_VAR(RES0__DNP2_S2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[64].TagValue = __GET_VAR(RES0__DNP2_S3PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[64].TagStatus = __GET_VAR(RES0__DNP2_S3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[65].TagValue = __GET_VAR(RES0__DNP2_PF1PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[65].TagStatus = __GET_VAR(RES0__DNP2_PF1PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[66].TagValue = __GET_VAR(RES0__DNP2_PF2PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[66].TagStatus = __GET_VAR(RES0__DNP2_PF2PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[67].TagValue = __GET_VAR(RES0__DNP2_PF3PUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[67].TagStatus = __GET_VAR(RES0__DNP2_PF3PUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[68].TagValue = __GET_VAR(RES0__DNP2_PAVPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[68].TagStatus = __GET_VAR(RES0__DNP2_PAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[69].TagValue = __GET_VAR(RES0__DNP2_QAVPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[69].TagStatus = __GET_VAR(RES0__DNP2_QAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[70].TagValue = __GET_VAR(RES0__DNP2_SAVPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[70].TagStatus = __GET_VAR(RES0__DNP2_SAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[71].TagValue = __GET_VAR(RES0__DNP2_PFAVPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[71].TagStatus = __GET_VAR(RES0__DNP2_PFAVPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[72].TagValue = __GET_VAR(RES0__DNP2_FREQPUMPAG1,);
	DNP_Slave_Driver_Instances[1].Tags[72].TagStatus = __GET_VAR(RES0__DNP2_FREQPUMPAG1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[73].TagValue = __GET_VAR(RES0__DNP2_I1PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[73].TagStatus = __GET_VAR(RES0__DNP2_I1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[74].TagValue = __GET_VAR(RES0__DNP2_I2PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[74].TagStatus = __GET_VAR(RES0__DNP2_I2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[75].TagValue = __GET_VAR(RES0__DNP2_I3PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[75].TagStatus = __GET_VAR(RES0__DNP2_I3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[76].TagValue = __GET_VAR(RES0__DNP2_V1PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[76].TagStatus = __GET_VAR(RES0__DNP2_V1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[77].TagValue = __GET_VAR(RES0__DNP2_V2PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[77].TagStatus = __GET_VAR(RES0__DNP2_V2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[78].TagValue = __GET_VAR(RES0__DNP2_V3PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[78].TagStatus = __GET_VAR(RES0__DNP2_V3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[79].TagValue = __GET_VAR(RES0__DNP2_V12PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[79].TagStatus = __GET_VAR(RES0__DNP2_V12PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[80].TagValue = __GET_VAR(RES0__DNP2_V23PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[80].TagStatus = __GET_VAR(RES0__DNP2_V23PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[81].TagValue = __GET_VAR(RES0__DNP2_V31PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[81].TagStatus = __GET_VAR(RES0__DNP2_V31PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[82].TagValue = __GET_VAR(RES0__DNP2_P1PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[82].TagStatus = __GET_VAR(RES0__DNP2_P1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[83].TagValue = __GET_VAR(RES0__DNP2_P2PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[83].TagStatus = __GET_VAR(RES0__DNP2_P2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[84].TagValue = __GET_VAR(RES0__DNP2_P3PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[84].TagStatus = __GET_VAR(RES0__DNP2_P3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[85].TagValue = __GET_VAR(RES0__DNP2_Q1PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[85].TagStatus = __GET_VAR(RES0__DNP2_Q1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[86].TagValue = __GET_VAR(RES0__DNP2_Q2PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[86].TagStatus = __GET_VAR(RES0__DNP2_Q2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[87].TagValue = __GET_VAR(RES0__DNP2_Q3PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[87].TagStatus = __GET_VAR(RES0__DNP2_Q3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[88].TagValue = __GET_VAR(RES0__DNP2_S1PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[88].TagStatus = __GET_VAR(RES0__DNP2_S1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[89].TagValue = __GET_VAR(RES0__DNP2_S2PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[89].TagStatus = __GET_VAR(RES0__DNP2_S2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[90].TagValue = __GET_VAR(RES0__DNP2_S3PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[90].TagStatus = __GET_VAR(RES0__DNP2_S3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[91].TagValue = __GET_VAR(RES0__DNP2_PF1PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[91].TagStatus = __GET_VAR(RES0__DNP2_PF1PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[92].TagValue = __GET_VAR(RES0__DNP2_PF2PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[92].TagStatus = __GET_VAR(RES0__DNP2_PF2PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[93].TagValue = __GET_VAR(RES0__DNP2_PF3PUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[93].TagStatus = __GET_VAR(RES0__DNP2_PF3PUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[94].TagValue = __GET_VAR(RES0__DNP2_PAVPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[94].TagStatus = __GET_VAR(RES0__DNP2_PAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[95].TagValue = __GET_VAR(RES0__DNP2_QAVPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[95].TagStatus = __GET_VAR(RES0__DNP2_QAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[96].TagValue = __GET_VAR(RES0__DNP2_SAVPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[96].TagStatus = __GET_VAR(RES0__DNP2_SAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[97].TagValue = __GET_VAR(RES0__DNP2_PFAVPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[97].TagStatus = __GET_VAR(RES0__DNP2_PFAVPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[98].TagValue = __GET_VAR(RES0__DNP2_FREQPUMPAG2,);
	DNP_Slave_Driver_Instances[1].Tags[98].TagStatus = __GET_VAR(RES0__DNP2_FREQPUMPAG2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[99].TagValue = __GET_VAR(RES0__DNP2_I1PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[99].TagStatus = __GET_VAR(RES0__DNP2_I1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[100].TagValue = __GET_VAR(RES0__DNP2_I2PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[100].TagStatus = __GET_VAR(RES0__DNP2_I2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[101].TagValue = __GET_VAR(RES0__DNP2_I3PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[101].TagStatus = __GET_VAR(RES0__DNP2_I3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[102].TagValue = __GET_VAR(RES0__DNP2_V1PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[102].TagStatus = __GET_VAR(RES0__DNP2_V1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[103].TagValue = __GET_VAR(RES0__DNP2_V2PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[103].TagStatus = __GET_VAR(RES0__DNP2_V2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[104].TagValue = __GET_VAR(RES0__DNP2_V3PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[104].TagStatus = __GET_VAR(RES0__DNP2_V3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[105].TagValue = __GET_VAR(RES0__DNP2_V12PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[105].TagStatus = __GET_VAR(RES0__DNP2_V12PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[106].TagValue = __GET_VAR(RES0__DNP2_V23PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[106].TagStatus = __GET_VAR(RES0__DNP2_V23PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[107].TagValue = __GET_VAR(RES0__DNP2_V31PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[107].TagStatus = __GET_VAR(RES0__DNP2_V31PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[108].TagValue = __GET_VAR(RES0__DNP2_P1PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[108].TagStatus = __GET_VAR(RES0__DNP2_P1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[109].TagValue = __GET_VAR(RES0__DNP2_P2PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[109].TagStatus = __GET_VAR(RES0__DNP2_P2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[110].TagValue = __GET_VAR(RES0__DNP2_P3PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[110].TagStatus = __GET_VAR(RES0__DNP2_P3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[111].TagValue = __GET_VAR(RES0__DNP2_Q1PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[111].TagStatus = __GET_VAR(RES0__DNP2_Q1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[112].TagValue = __GET_VAR(RES0__DNP2_Q2PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[112].TagStatus = __GET_VAR(RES0__DNP2_Q2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[113].TagValue = __GET_VAR(RES0__DNP2_Q3PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[113].TagStatus = __GET_VAR(RES0__DNP2_Q3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[114].TagValue = __GET_VAR(RES0__DNP2_S1PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[114].TagStatus = __GET_VAR(RES0__DNP2_S1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[115].TagValue = __GET_VAR(RES0__DNP2_S2PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[115].TagStatus = __GET_VAR(RES0__DNP2_S2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[116].TagValue = __GET_VAR(RES0__DNP2_S3PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[116].TagStatus = __GET_VAR(RES0__DNP2_S3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[117].TagValue = __GET_VAR(RES0__DNP2_PF1PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[117].TagStatus = __GET_VAR(RES0__DNP2_PF1PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[118].TagValue = __GET_VAR(RES0__DNP2_PF2PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[118].TagStatus = __GET_VAR(RES0__DNP2_PF2PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[119].TagValue = __GET_VAR(RES0__DNP2_PF3PUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[119].TagStatus = __GET_VAR(RES0__DNP2_PF3PUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[120].TagValue = __GET_VAR(RES0__DNP2_PAVPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[120].TagStatus = __GET_VAR(RES0__DNP2_PAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[121].TagValue = __GET_VAR(RES0__DNP2_QAVPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[121].TagStatus = __GET_VAR(RES0__DNP2_QAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[122].TagValue = __GET_VAR(RES0__DNP2_SAVPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[122].TagStatus = __GET_VAR(RES0__DNP2_SAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[123].TagValue = __GET_VAR(RES0__DNP2_PFAVPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[123].TagStatus = __GET_VAR(RES0__DNP2_PFAVPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[124].TagValue = __GET_VAR(RES0__DNP2_FREQPUMPAG3,);
	DNP_Slave_Driver_Instances[1].Tags[124].TagStatus = __GET_VAR(RES0__DNP2_FREQPUMPAG3_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[131].TagValue = __GET_VAR(RES0__DNP2_RS485WF1,);
	DNP_Slave_Driver_Instances[1].Tags[131].TagStatus = __GET_VAR(RES0__DNP2_RS485WF1_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[132].TagValue = __GET_VAR(RES0__DNP2_RS485WF2,);
	DNP_Slave_Driver_Instances[1].Tags[132].TagStatus = __GET_VAR(RES0__DNP2_RS485WF2_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[133].TagValue = __GET_VAR(RES0__DNP2_RS485LEVELMETER,);
	DNP_Slave_Driver_Instances[1].Tags[133].TagStatus = __GET_VAR(RES0__DNP2_RS485LEVELMETER_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[134].TagValue = __GET_VAR(RES0__DNP2_CL,);
	DNP_Slave_Driver_Instances[1].Tags[134].TagStatus = __GET_VAR(RES0__DNP2_CL_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[135].TagValue = __GET_VAR(RES0__DNP2_TU,);
	DNP_Slave_Driver_Instances[1].Tags[135].TagStatus = __GET_VAR(RES0__DNP2_TU_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[136].TagValue = __GET_VAR(RES0__DNP2_TH,);
	DNP_Slave_Driver_Instances[1].Tags[136].TagStatus = __GET_VAR(RES0__DNP2_TH_STATUS,);
	DNP_Slave_Driver_Instances[1].Tags[137].TagValue = __GET_VAR(RES0__DNP2_EC,);
	DNP_Slave_Driver_Instances[1].Tags[137].TagStatus = __GET_VAR(RES0__DNP2_EC_STATUS,);
	Modbus_Master_Driver_Instances[0].Tags[21].TagValue = __GET_VAR(RES0__RIO_P1VAR1_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[42].TagValue = __GET_VAR(RES0__RIO_P1VAR2_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[48].TagValue = __GET_VAR(RES0__RIO_P1VAR3_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[70].TagValue = __GET_VAR(RES0__RIO_P2VAR1_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[91].TagValue = __GET_VAR(RES0__RIO_P2VAR2_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[97].TagValue = __GET_VAR(RES0__RIO_P2VAR3_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[119].TagValue = __GET_VAR(RES0__RIO_P3VAR1_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[140].TagValue = __GET_VAR(RES0__RIO_P3VAR2_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[146].TagValue = __GET_VAR(RES0__RIO_P3VAR3_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[159].TagValue = __GET_VAR(RES0__RIO_DI9_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[168].TagValue = __GET_VAR(RES0__RIO_AI5_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[169].TagValue = __GET_VAR(RES0__RIO_DO5_TAG0,);
	Modbus_Master_Driver_Instances[0].Tags[170].TagValue = __GET_VAR(RES0__RIO_DO5_TAG1,);
	Modbus_Master_Driver_Instances[0].Tags[171].TagValue = __GET_VAR(RES0__RIO_DO5_TAG2,);
	Modbus_Master_Driver_Instances[0].Tags[172].TagValue = __GET_VAR(RES0__RIO_DO5_TAG3,);
	Modbus_Master_Driver_Instances[0].Tags[177].TagValue = __GET_VAR(RES0__RIO_DO5_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[190].TagValue = __GET_VAR(RES0__RIO_DI17_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[196].TagValue = __GET_VAR(RES0__RIO_AI9_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[202].TagValue = __GET_VAR(RES0__RIO_LEVELTANK485_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[208].TagValue = __GET_VAR(RES0__RIO_FLOW_POLL,);
	Modbus_Master_Driver_Instances[0].Tags[229].TagValue = __GET_VAR(RES0__RIO_CL_POLL,);
	Modbus_Master_Driver_Instances[1].Tags[12].TagValue = __GET_VAR(RES0__RIO2_BLOCK1_POLL,);
	Modbus_Master_Driver_Instances[2].Tags[29].TagValue = __GET_VAR(RES0__ROI3_BLOCK1_POLL,);
}
void setVarsFromDRVTags(){
	__SET_VAR(,RES0__LIO_DITAG0,,LIO_Driver_Instance.Tags[0].TagValue);
	__SET_VAR(,RES0__LIO_DITAG0_STATUS,,LIO_Driver_Instance.Tags[0].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG0_DT,,LIO_Driver_Instance.Tags[0].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG1,,LIO_Driver_Instance.Tags[1].TagValue);
	__SET_VAR(,RES0__LIO_DITAG1_STATUS,,LIO_Driver_Instance.Tags[1].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG1_DT,,LIO_Driver_Instance.Tags[1].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG2,,LIO_Driver_Instance.Tags[2].TagValue);
	__SET_VAR(,RES0__LIO_DITAG2_STATUS,,LIO_Driver_Instance.Tags[2].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG2_DT,,LIO_Driver_Instance.Tags[2].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG3,,LIO_Driver_Instance.Tags[3].TagValue);
	__SET_VAR(,RES0__LIO_DITAG3_STATUS,,LIO_Driver_Instance.Tags[3].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG3_DT,,LIO_Driver_Instance.Tags[3].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG4,,LIO_Driver_Instance.Tags[4].TagValue);
	__SET_VAR(,RES0__LIO_DITAG4_STATUS,,LIO_Driver_Instance.Tags[4].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG4_DT,,LIO_Driver_Instance.Tags[4].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG5,,LIO_Driver_Instance.Tags[5].TagValue);
	__SET_VAR(,RES0__LIO_DITAG5_STATUS,,LIO_Driver_Instance.Tags[5].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG5_DT,,LIO_Driver_Instance.Tags[5].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG6,,LIO_Driver_Instance.Tags[6].TagValue);
	__SET_VAR(,RES0__LIO_DITAG6_STATUS,,LIO_Driver_Instance.Tags[6].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG6_DT,,LIO_Driver_Instance.Tags[6].TagValueDT);
	__SET_VAR(,RES0__LIO_DITAG7,,LIO_Driver_Instance.Tags[7].TagValue);
	__SET_VAR(,RES0__LIO_DITAG7_STATUS,,LIO_Driver_Instance.Tags[7].TagStatus);
	__SET_VAR(,RES0__LIO_DITAG7_DT,,LIO_Driver_Instance.Tags[7].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG0,,LIO_Driver_Instance.Tags[12].TagValue);
	__SET_VAR(,RES0__LIO_AITAG0_STATUS,,LIO_Driver_Instance.Tags[12].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG0_DT,,LIO_Driver_Instance.Tags[12].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG1,,LIO_Driver_Instance.Tags[13].TagValue);
	__SET_VAR(,RES0__LIO_AITAG1_STATUS,,LIO_Driver_Instance.Tags[13].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG1_DT,,LIO_Driver_Instance.Tags[13].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG2,,LIO_Driver_Instance.Tags[14].TagValue);
	__SET_VAR(,RES0__LIO_AITAG2_STATUS,,LIO_Driver_Instance.Tags[14].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG2_DT,,LIO_Driver_Instance.Tags[14].TagValueDT);
	__SET_VAR(,RES0__LIO_AITAG3,,LIO_Driver_Instance.Tags[15].TagValue);
	__SET_VAR(,RES0__LIO_AITAG3_STATUS,,LIO_Driver_Instance.Tags[15].TagStatus);
	__SET_VAR(,RES0__LIO_AITAG3_DT,,LIO_Driver_Instance.Tags[15].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG0,,LIO_Driver_Instance.Tags[17].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG0_STATUS,,LIO_Driver_Instance.Tags[17].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG0_DT,,LIO_Driver_Instance.Tags[17].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG1,,LIO_Driver_Instance.Tags[18].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG1_STATUS,,LIO_Driver_Instance.Tags[18].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG1_DT,,LIO_Driver_Instance.Tags[18].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG2,,LIO_Driver_Instance.Tags[19].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG2_STATUS,,LIO_Driver_Instance.Tags[19].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG2_DT,,LIO_Driver_Instance.Tags[19].TagValueDT);
	__SET_VAR(,RES0__LIO_CNTTAG3,,LIO_Driver_Instance.Tags[20].TagValue);
	__SET_VAR(,RES0__LIO_CNTTAG3_STATUS,,LIO_Driver_Instance.Tags[20].TagStatus);
	__SET_VAR(,RES0__LIO_CNTTAG3_DT,,LIO_Driver_Instance.Tags[20].TagValueDT);
	__SET_VAR(,RES0__LIO_SENTAG0,,LIO_Driver_Instance.Tags[21].TagValue);
	__SET_VAR(,RES0__LIO_SENTAG0_STATUS,,LIO_Driver_Instance.Tags[21].TagStatus);
	__SET_VAR(,RES0__LIO_SENTAG0_DT,,LIO_Driver_Instance.Tags[21].TagValueDT);
	__SET_VAR(,RES0__LIO_SENTAG1,,LIO_Driver_Instance.Tags[22].TagValue);
	__SET_VAR(,RES0__LIO_SENTAG1_STATUS,,LIO_Driver_Instance.Tags[22].TagStatus);
	__SET_VAR(,RES0__LIO_SENTAG1_DT,,LIO_Driver_Instance.Tags[22].TagValueDT);
	__SET_VAR(,RES0__LIO_CPU_USAGE,,LIO_Driver_Instance.Tags[24].TagValue);
	__SET_VAR(,RES0__LIO_CPU_USAGE_STATUS,,LIO_Driver_Instance.Tags[24].TagStatus);
	__SET_VAR(,RES0__LIO_CPU_USAGE_DT,,LIO_Driver_Instance.Tags[24].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_RAM,,LIO_Driver_Instance.Tags[25].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_RAM_STATUS,,LIO_Driver_Instance.Tags[25].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_RAM_DT,,LIO_Driver_Instance.Tags[25].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_RAM,,LIO_Driver_Instance.Tags[26].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_RAM_STATUS,,LIO_Driver_Instance.Tags[26].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_RAM_DT,,LIO_Driver_Instance.Tags[26].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_RAM,,LIO_Driver_Instance.Tags[27].TagValue);
	__SET_VAR(,RES0__LIO_USED_RAM_STATUS,,LIO_Driver_Instance.Tags[27].TagStatus);
	__SET_VAR(,RES0__LIO_USED_RAM_DT,,LIO_Driver_Instance.Tags[27].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_FLASH,,LIO_Driver_Instance.Tags[28].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_FLASH_STATUS,,LIO_Driver_Instance.Tags[28].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_FLASH_DT,,LIO_Driver_Instance.Tags[28].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_FLASH,,LIO_Driver_Instance.Tags[29].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_FLASH_STATUS,,LIO_Driver_Instance.Tags[29].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_FLASH_DT,,LIO_Driver_Instance.Tags[29].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_FLASH,,LIO_Driver_Instance.Tags[30].TagValue);
	__SET_VAR(,RES0__LIO_USED_FLASH_STATUS,,LIO_Driver_Instance.Tags[30].TagStatus);
	__SET_VAR(,RES0__LIO_USED_FLASH_DT,,LIO_Driver_Instance.Tags[30].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_SDCARD,,LIO_Driver_Instance.Tags[31].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_SDCARD_STATUS,,LIO_Driver_Instance.Tags[31].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_SDCARD_DT,,LIO_Driver_Instance.Tags[31].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_SDCARD,,LIO_Driver_Instance.Tags[32].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_SDCARD_STATUS,,LIO_Driver_Instance.Tags[32].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_SDCARD_DT,,LIO_Driver_Instance.Tags[32].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_SDCARD,,LIO_Driver_Instance.Tags[33].TagValue);
	__SET_VAR(,RES0__LIO_USED_SDCARD_STATUS,,LIO_Driver_Instance.Tags[33].TagStatus);
	__SET_VAR(,RES0__LIO_USED_SDCARD_DT,,LIO_Driver_Instance.Tags[33].TagValueDT);
	__SET_VAR(,RES0__LIO_TOTAL_NVRAM,,LIO_Driver_Instance.Tags[34].TagValue);
	__SET_VAR(,RES0__LIO_TOTAL_NVRAM_STATUS,,LIO_Driver_Instance.Tags[34].TagStatus);
	__SET_VAR(,RES0__LIO_TOTAL_NVRAM_DT,,LIO_Driver_Instance.Tags[34].TagValueDT);
	__SET_VAR(,RES0__LIO_FREESPACE_NVRAM,,LIO_Driver_Instance.Tags[35].TagValue);
	__SET_VAR(,RES0__LIO_FREESPACE_NVRAM_STATUS,,LIO_Driver_Instance.Tags[35].TagStatus);
	__SET_VAR(,RES0__LIO_FREESPACE_NVRAM_DT,,LIO_Driver_Instance.Tags[35].TagValueDT);
	__SET_VAR(,RES0__LIO_USED_NVRAM,,LIO_Driver_Instance.Tags[36].TagValue);
	__SET_VAR(,RES0__LIO_USED_NVRAM_STATUS,,LIO_Driver_Instance.Tags[36].TagStatus);
	__SET_VAR(,RES0__LIO_USED_NVRAM_DT,,LIO_Driver_Instance.Tags[36].TagValueDT);
	__SET_VAR(,RES0__LIO_CANBUS_STATUS,,LIO_Driver_Instance.Tags[37].TagValue);
	__SET_VAR(,RES0__LIO_CANBUS_STATUS_STATUS,,LIO_Driver_Instance.Tags[37].TagStatus);
	__SET_VAR(,RES0__LIO_CANBUS_STATUS_DT,,LIO_Driver_Instance.Tags[37].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL,,LIO_Driver_Instance.Tags[40].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL_STATUS,,LIO_Driver_Instance.Tags[40].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL_DT,,LIO_Driver_Instance.Tags[40].TagValueDT);
	__SET_VAR(,RES0__LIO_3GCONNECTED,,LIO_Driver_Instance.Tags[41].TagValue);
	__SET_VAR(,RES0__LIO_3GCONNECTED_STATUS,,LIO_Driver_Instance.Tags[41].TagStatus);
	__SET_VAR(,RES0__LIO_3GCONNECTED_DT,,LIO_Driver_Instance.Tags[41].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP1,,LIO_Driver_Instance.Tags[42].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP1_STATUS,,LIO_Driver_Instance.Tags[42].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP1_DT,,LIO_Driver_Instance.Tags[42].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP2,,LIO_Driver_Instance.Tags[43].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP2_STATUS,,LIO_Driver_Instance.Tags[43].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP2_DT,,LIO_Driver_Instance.Tags[43].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP3,,LIO_Driver_Instance.Tags[44].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP3_STATUS,,LIO_Driver_Instance.Tags[44].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP3_DT,,LIO_Driver_Instance.Tags[44].TagValueDT);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP4,,LIO_Driver_Instance.Tags[45].TagValue);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP4_STATUS,,LIO_Driver_Instance.Tags[45].TagStatus);
	__SET_VAR(,RES0__LIO_3GMODEMSECIP4_DT,,LIO_Driver_Instance.Tags[45].TagValueDT);
	__SET_VAR(,RES0__LIO_LOGIC_PROCESSING_TIME,,LIO_Driver_Instance.Tags[46].TagValue);
	__SET_VAR(,RES0__LIO_LOGIC_PROCESSING_TIME_STATUS,,LIO_Driver_Instance.Tags[46].TagStatus);
	__SET_VAR(,RES0__LIO_LOGIC_PROCESSING_TIME_DT,,LIO_Driver_Instance.Tags[46].TagValueDT);
	__SET_VAR(,RES0__LIO_FIRST_SCAN,,LIO_Driver_Instance.Tags[47].TagValue);
	__SET_VAR(,RES0__LIO_FIRST_SCAN_STATUS,,LIO_Driver_Instance.Tags[47].TagStatus);
	__SET_VAR(,RES0__LIO_FIRST_SCAN_DT,,LIO_Driver_Instance.Tags[47].TagValueDT);
	__SET_VAR(,RES0__DNP_OPENDOOR,,DNP_Slave_Driver_Instances[0].Tags[0].TagValue);
	__SET_VAR(,RES0__DNP_OPENDOOR_STATUS,,DNP_Slave_Driver_Instances[0].Tags[0].TagStatus);
	__SET_VAR(,RES0__DNP_OPENDOOR_DT,,DNP_Slave_Driver_Instances[0].Tags[0].TagValueDT);
	__SET_VAR(,RES0__DNP_STOPPUMPAG1,,DNP_Slave_Driver_Instances[0].Tags[125].TagValue);
	__SET_VAR(,RES0__DNP_STOPPUMPAG1_STATUS,,DNP_Slave_Driver_Instances[0].Tags[125].TagStatus);
	__SET_VAR(,RES0__DNP_STOPPUMPAG1_DT,,DNP_Slave_Driver_Instances[0].Tags[125].TagValueDT);
	__SET_VAR(,RES0__DNP_STOPPUMPAG2,,DNP_Slave_Driver_Instances[0].Tags[126].TagValue);
	__SET_VAR(,RES0__DNP_STOPPUMPAG2_STATUS,,DNP_Slave_Driver_Instances[0].Tags[126].TagStatus);
	__SET_VAR(,RES0__DNP_STOPPUMPAG2_DT,,DNP_Slave_Driver_Instances[0].Tags[126].TagValueDT);
	__SET_VAR(,RES0__DNP_STOPPUMPAG3,,DNP_Slave_Driver_Instances[0].Tags[127].TagValue);
	__SET_VAR(,RES0__DNP_STOPPUMPAG3_STATUS,,DNP_Slave_Driver_Instances[0].Tags[127].TagStatus);
	__SET_VAR(,RES0__DNP_STOPPUMPAG3_DT,,DNP_Slave_Driver_Instances[0].Tags[127].TagValueDT);
	__SET_VAR(,RES0__DNP_STARTPUMPAG1,,DNP_Slave_Driver_Instances[0].Tags[128].TagValue);
	__SET_VAR(,RES0__DNP_STARTPUMPAG1_STATUS,,DNP_Slave_Driver_Instances[0].Tags[128].TagStatus);
	__SET_VAR(,RES0__DNP_STARTPUMPAG1_DT,,DNP_Slave_Driver_Instances[0].Tags[128].TagValueDT);
	__SET_VAR(,RES0__DNP_STARTPUMPAG2,,DNP_Slave_Driver_Instances[0].Tags[129].TagValue);
	__SET_VAR(,RES0__DNP_STARTPUMPAG2_STATUS,,DNP_Slave_Driver_Instances[0].Tags[129].TagStatus);
	__SET_VAR(,RES0__DNP_STARTPUMPAG2_DT,,DNP_Slave_Driver_Instances[0].Tags[129].TagValueDT);
	__SET_VAR(,RES0__DNP_STARTPUMPAG3,,DNP_Slave_Driver_Instances[0].Tags[130].TagValue);
	__SET_VAR(,RES0__DNP_STARTPUMPAG3_STATUS,,DNP_Slave_Driver_Instances[0].Tags[130].TagStatus);
	__SET_VAR(,RES0__DNP_STARTPUMPAG3_DT,,DNP_Slave_Driver_Instances[0].Tags[130].TagValueDT);
	__SET_VAR(,RES0__DNP2_STOPPUMPAG1,,DNP_Slave_Driver_Instances[1].Tags[125].TagValue);
	__SET_VAR(,RES0__DNP2_STOPPUMPAG1_STATUS,,DNP_Slave_Driver_Instances[1].Tags[125].TagStatus);
	__SET_VAR(,RES0__DNP2_STOPPUMPAG2,,DNP_Slave_Driver_Instances[1].Tags[126].TagValue);
	__SET_VAR(,RES0__DNP2_STOPPUMPAG2_STATUS,,DNP_Slave_Driver_Instances[1].Tags[126].TagStatus);
	__SET_VAR(,RES0__DNP2_STOPPUMPAG3,,DNP_Slave_Driver_Instances[1].Tags[127].TagValue);
	__SET_VAR(,RES0__DNP2_STOPPUMPAG3_STATUS,,DNP_Slave_Driver_Instances[1].Tags[127].TagStatus);
	__SET_VAR(,RES0__DNP2_STARTPUMPAG1,,DNP_Slave_Driver_Instances[1].Tags[128].TagValue);
	__SET_VAR(,RES0__DNP2_STARTPUMPAG1_STATUS,,DNP_Slave_Driver_Instances[1].Tags[128].TagStatus);
	__SET_VAR(,RES0__DNP2_STARTPUMPAG2,,DNP_Slave_Driver_Instances[1].Tags[129].TagValue);
	__SET_VAR(,RES0__DNP2_STARTPUMPAG2_STATUS,,DNP_Slave_Driver_Instances[1].Tags[129].TagStatus);
	__SET_VAR(,RES0__DNP2_STARTPUMPAG3,,DNP_Slave_Driver_Instances[1].Tags[130].TagValue);
	__SET_VAR(,RES0__DNP2_STARTPUMPAG3_STATUS,,DNP_Slave_Driver_Instances[1].Tags[130].TagStatus);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG2999,,Modbus_Master_Driver_Instances[0].Tags[0].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3001,,Modbus_Master_Driver_Instances[0].Tags[1].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3003,,Modbus_Master_Driver_Instances[0].Tags[2].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3005,,Modbus_Master_Driver_Instances[0].Tags[3].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3007,,Modbus_Master_Driver_Instances[0].Tags[4].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3009,,Modbus_Master_Driver_Instances[0].Tags[5].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3011,,Modbus_Master_Driver_Instances[0].Tags[6].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3013,,Modbus_Master_Driver_Instances[0].Tags[7].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3015,,Modbus_Master_Driver_Instances[0].Tags[8].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3017,,Modbus_Master_Driver_Instances[0].Tags[9].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3019,,Modbus_Master_Driver_Instances[0].Tags[10].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3021,,Modbus_Master_Driver_Instances[0].Tags[11].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3023,,Modbus_Master_Driver_Instances[0].Tags[12].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3025,,Modbus_Master_Driver_Instances[0].Tags[13].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3027,,Modbus_Master_Driver_Instances[0].Tags[14].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3029,,Modbus_Master_Driver_Instances[0].Tags[15].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_TAG3031,,Modbus_Master_Driver_Instances[0].Tags[16].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[17].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[18].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[19].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR1_ERROR,,Modbus_Master_Driver_Instances[0].Tags[20].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3053,,Modbus_Master_Driver_Instances[0].Tags[22].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3055,,Modbus_Master_Driver_Instances[0].Tags[23].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3057,,Modbus_Master_Driver_Instances[0].Tags[24].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3059,,Modbus_Master_Driver_Instances[0].Tags[25].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3061,,Modbus_Master_Driver_Instances[0].Tags[26].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3063,,Modbus_Master_Driver_Instances[0].Tags[27].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3065,,Modbus_Master_Driver_Instances[0].Tags[28].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3067,,Modbus_Master_Driver_Instances[0].Tags[29].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3069,,Modbus_Master_Driver_Instances[0].Tags[30].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3071,,Modbus_Master_Driver_Instances[0].Tags[31].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3073,,Modbus_Master_Driver_Instances[0].Tags[32].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3075,,Modbus_Master_Driver_Instances[0].Tags[33].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3077,,Modbus_Master_Driver_Instances[0].Tags[34].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3079,,Modbus_Master_Driver_Instances[0].Tags[35].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3081,,Modbus_Master_Driver_Instances[0].Tags[36].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_TAG3083,,Modbus_Master_Driver_Instances[0].Tags[37].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[38].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[39].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[40].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR2_ERROR,,Modbus_Master_Driver_Instances[0].Tags[41].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR3_TAG3109,,Modbus_Master_Driver_Instances[0].Tags[43].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR3_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[44].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR3_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[45].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR3_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[46].TagValue);
	__SET_VAR(,RES0__RIO_P1VAR3_ERROR,,Modbus_Master_Driver_Instances[0].Tags[47].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG2999,,Modbus_Master_Driver_Instances[0].Tags[49].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3001,,Modbus_Master_Driver_Instances[0].Tags[50].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3003,,Modbus_Master_Driver_Instances[0].Tags[51].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3005,,Modbus_Master_Driver_Instances[0].Tags[52].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3007,,Modbus_Master_Driver_Instances[0].Tags[53].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3009,,Modbus_Master_Driver_Instances[0].Tags[54].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3011,,Modbus_Master_Driver_Instances[0].Tags[55].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3013,,Modbus_Master_Driver_Instances[0].Tags[56].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3015,,Modbus_Master_Driver_Instances[0].Tags[57].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3017,,Modbus_Master_Driver_Instances[0].Tags[58].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3019,,Modbus_Master_Driver_Instances[0].Tags[59].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3021,,Modbus_Master_Driver_Instances[0].Tags[60].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3023,,Modbus_Master_Driver_Instances[0].Tags[61].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3025,,Modbus_Master_Driver_Instances[0].Tags[62].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3027,,Modbus_Master_Driver_Instances[0].Tags[63].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3029,,Modbus_Master_Driver_Instances[0].Tags[64].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_TAG3031,,Modbus_Master_Driver_Instances[0].Tags[65].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[66].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[67].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[68].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR1_ERROR,,Modbus_Master_Driver_Instances[0].Tags[69].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3053,,Modbus_Master_Driver_Instances[0].Tags[71].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3055,,Modbus_Master_Driver_Instances[0].Tags[72].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3057,,Modbus_Master_Driver_Instances[0].Tags[73].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3059,,Modbus_Master_Driver_Instances[0].Tags[74].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3061,,Modbus_Master_Driver_Instances[0].Tags[75].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3063,,Modbus_Master_Driver_Instances[0].Tags[76].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3065,,Modbus_Master_Driver_Instances[0].Tags[77].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3067,,Modbus_Master_Driver_Instances[0].Tags[78].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3069,,Modbus_Master_Driver_Instances[0].Tags[79].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3071,,Modbus_Master_Driver_Instances[0].Tags[80].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3073,,Modbus_Master_Driver_Instances[0].Tags[81].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3075,,Modbus_Master_Driver_Instances[0].Tags[82].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3077,,Modbus_Master_Driver_Instances[0].Tags[83].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3079,,Modbus_Master_Driver_Instances[0].Tags[84].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3081,,Modbus_Master_Driver_Instances[0].Tags[85].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_TAG3083,,Modbus_Master_Driver_Instances[0].Tags[86].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[87].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[88].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[89].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR2_ERROR,,Modbus_Master_Driver_Instances[0].Tags[90].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR3_TAG3109,,Modbus_Master_Driver_Instances[0].Tags[92].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR3_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[93].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR3_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[94].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR3_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[95].TagValue);
	__SET_VAR(,RES0__RIO_P2VAR3_ERROR,,Modbus_Master_Driver_Instances[0].Tags[96].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG2999,,Modbus_Master_Driver_Instances[0].Tags[98].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3001,,Modbus_Master_Driver_Instances[0].Tags[99].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3003,,Modbus_Master_Driver_Instances[0].Tags[100].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3005,,Modbus_Master_Driver_Instances[0].Tags[101].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3007,,Modbus_Master_Driver_Instances[0].Tags[102].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3009,,Modbus_Master_Driver_Instances[0].Tags[103].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3011,,Modbus_Master_Driver_Instances[0].Tags[104].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3013,,Modbus_Master_Driver_Instances[0].Tags[105].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3015,,Modbus_Master_Driver_Instances[0].Tags[106].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3017,,Modbus_Master_Driver_Instances[0].Tags[107].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3019,,Modbus_Master_Driver_Instances[0].Tags[108].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3021,,Modbus_Master_Driver_Instances[0].Tags[109].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3023,,Modbus_Master_Driver_Instances[0].Tags[110].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3025,,Modbus_Master_Driver_Instances[0].Tags[111].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3027,,Modbus_Master_Driver_Instances[0].Tags[112].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3029,,Modbus_Master_Driver_Instances[0].Tags[113].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_TAG3031,,Modbus_Master_Driver_Instances[0].Tags[114].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[115].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[116].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[117].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR1_ERROR,,Modbus_Master_Driver_Instances[0].Tags[118].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3053,,Modbus_Master_Driver_Instances[0].Tags[120].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3055,,Modbus_Master_Driver_Instances[0].Tags[121].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3057,,Modbus_Master_Driver_Instances[0].Tags[122].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3059,,Modbus_Master_Driver_Instances[0].Tags[123].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3061,,Modbus_Master_Driver_Instances[0].Tags[124].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3063,,Modbus_Master_Driver_Instances[0].Tags[125].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3065,,Modbus_Master_Driver_Instances[0].Tags[126].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3067,,Modbus_Master_Driver_Instances[0].Tags[127].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3069,,Modbus_Master_Driver_Instances[0].Tags[128].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3071,,Modbus_Master_Driver_Instances[0].Tags[129].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3073,,Modbus_Master_Driver_Instances[0].Tags[130].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3075,,Modbus_Master_Driver_Instances[0].Tags[131].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3077,,Modbus_Master_Driver_Instances[0].Tags[132].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3079,,Modbus_Master_Driver_Instances[0].Tags[133].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3081,,Modbus_Master_Driver_Instances[0].Tags[134].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_TAG3083,,Modbus_Master_Driver_Instances[0].Tags[135].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[136].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[137].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[138].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR2_ERROR,,Modbus_Master_Driver_Instances[0].Tags[139].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR3_TAG3109,,Modbus_Master_Driver_Instances[0].Tags[141].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR3_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[142].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR3_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[143].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR3_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[144].TagValue);
	__SET_VAR(,RES0__RIO_P3VAR3_ERROR,,Modbus_Master_Driver_Instances[0].Tags[145].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG0,,Modbus_Master_Driver_Instances[0].Tags[147].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG1,,Modbus_Master_Driver_Instances[0].Tags[148].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG2,,Modbus_Master_Driver_Instances[0].Tags[149].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG3,,Modbus_Master_Driver_Instances[0].Tags[150].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG4,,Modbus_Master_Driver_Instances[0].Tags[151].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG5,,Modbus_Master_Driver_Instances[0].Tags[152].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG6,,Modbus_Master_Driver_Instances[0].Tags[153].TagValue);
	__SET_VAR(,RES0__RIO_DI9_TAG7,,Modbus_Master_Driver_Instances[0].Tags[154].TagValue);
	__SET_VAR(,RES0__RIO_DI9_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[155].TagValue);
	__SET_VAR(,RES0__RIO_DI9_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[156].TagValue);
	__SET_VAR(,RES0__RIO_DI9_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[157].TagValue);
	__SET_VAR(,RES0__RIO_DI9_ERROR,,Modbus_Master_Driver_Instances[0].Tags[158].TagValue);
	__SET_VAR(,RES0__RIO_AI5_TAG0,,Modbus_Master_Driver_Instances[0].Tags[160].TagValue);
	__SET_VAR(,RES0__RIO_AI5_TAG1,,Modbus_Master_Driver_Instances[0].Tags[161].TagValue);
	__SET_VAR(,RES0__RIO_AI5_TAG2,,Modbus_Master_Driver_Instances[0].Tags[162].TagValue);
	__SET_VAR(,RES0__RIO_AI5_TAG3,,Modbus_Master_Driver_Instances[0].Tags[163].TagValue);
	__SET_VAR(,RES0__RIO_AI5_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[164].TagValue);
	__SET_VAR(,RES0__RIO_AI5_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[165].TagValue);
	__SET_VAR(,RES0__RIO_AI5_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[166].TagValue);
	__SET_VAR(,RES0__RIO_AI5_ERROR,,Modbus_Master_Driver_Instances[0].Tags[167].TagValue);
	__SET_VAR(,RES0__RIO_DO5_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[173].TagValue);
	__SET_VAR(,RES0__RIO_DO5_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[174].TagValue);
	__SET_VAR(,RES0__RIO_DO5_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[175].TagValue);
	__SET_VAR(,RES0__RIO_DO5_ERROR,,Modbus_Master_Driver_Instances[0].Tags[176].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG0,,Modbus_Master_Driver_Instances[0].Tags[178].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG1,,Modbus_Master_Driver_Instances[0].Tags[179].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG2,,Modbus_Master_Driver_Instances[0].Tags[180].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG3,,Modbus_Master_Driver_Instances[0].Tags[181].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG4,,Modbus_Master_Driver_Instances[0].Tags[182].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG5,,Modbus_Master_Driver_Instances[0].Tags[183].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG6,,Modbus_Master_Driver_Instances[0].Tags[184].TagValue);
	__SET_VAR(,RES0__RIO_DI17_TAG7,,Modbus_Master_Driver_Instances[0].Tags[185].TagValue);
	__SET_VAR(,RES0__RIO_DI17_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[186].TagValue);
	__SET_VAR(,RES0__RIO_DI17_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[187].TagValue);
	__SET_VAR(,RES0__RIO_DI17_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[188].TagValue);
	__SET_VAR(,RES0__RIO_DI17_ERROR,,Modbus_Master_Driver_Instances[0].Tags[189].TagValue);
	__SET_VAR(,RES0__RIO_AI9_TAG0,,Modbus_Master_Driver_Instances[0].Tags[191].TagValue);
	__SET_VAR(,RES0__RIO_AI9_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[192].TagValue);
	__SET_VAR(,RES0__RIO_AI9_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[193].TagValue);
	__SET_VAR(,RES0__RIO_AI9_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[194].TagValue);
	__SET_VAR(,RES0__RIO_AI9_ERROR,,Modbus_Master_Driver_Instances[0].Tags[195].TagValue);
	__SET_VAR(,RES0__RIO_LEVELTANK485_TAG30032,,Modbus_Master_Driver_Instances[0].Tags[197].TagValue);
	__SET_VAR(,RES0__RIO_LEVELTANK485_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[198].TagValue);
	__SET_VAR(,RES0__RIO_LEVELTANK485_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[199].TagValue);
	__SET_VAR(,RES0__RIO_LEVELTANK485_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[200].TagValue);
	__SET_VAR(,RES0__RIO_LEVELTANK485_ERROR,,Modbus_Master_Driver_Instances[0].Tags[201].TagValue);
	__SET_VAR(,RES0__RIO_FLOW_TAG4113,,Modbus_Master_Driver_Instances[0].Tags[203].TagValue);
	__SET_VAR(,RES0__RIO_FLOW_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[204].TagValue);
	__SET_VAR(,RES0__RIO_FLOW_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[205].TagValue);
	__SET_VAR(,RES0__RIO_FLOW_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[206].TagValue);
	__SET_VAR(,RES0__RIO_FLOW_ERROR,,Modbus_Master_Driver_Instances[0].Tags[207].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4000,,Modbus_Master_Driver_Instances[0].Tags[209].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4001,,Modbus_Master_Driver_Instances[0].Tags[210].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4002,,Modbus_Master_Driver_Instances[0].Tags[211].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4003,,Modbus_Master_Driver_Instances[0].Tags[212].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4004,,Modbus_Master_Driver_Instances[0].Tags[213].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4005,,Modbus_Master_Driver_Instances[0].Tags[214].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4006,,Modbus_Master_Driver_Instances[0].Tags[215].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4007,,Modbus_Master_Driver_Instances[0].Tags[216].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4008,,Modbus_Master_Driver_Instances[0].Tags[217].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4009,,Modbus_Master_Driver_Instances[0].Tags[218].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4010,,Modbus_Master_Driver_Instances[0].Tags[219].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4011,,Modbus_Master_Driver_Instances[0].Tags[220].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4012,,Modbus_Master_Driver_Instances[0].Tags[221].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4013,,Modbus_Master_Driver_Instances[0].Tags[222].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4014,,Modbus_Master_Driver_Instances[0].Tags[223].TagValue);
	__SET_VAR(,RES0__RIO_CL_TAG4015,,Modbus_Master_Driver_Instances[0].Tags[224].TagValue);
	__SET_VAR(,RES0__RIO_CL_ONLINE,,Modbus_Master_Driver_Instances[0].Tags[225].TagValue);
	__SET_VAR(,RES0__RIO_CL_SENDNUM,,Modbus_Master_Driver_Instances[0].Tags[226].TagValue);
	__SET_VAR(,RES0__RIO_CL_RECNUM,,Modbus_Master_Driver_Instances[0].Tags[227].TagValue);
	__SET_VAR(,RES0__RIO_CL_ERROR,,Modbus_Master_Driver_Instances[0].Tags[228].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG0,,Modbus_Master_Driver_Instances[1].Tags[0].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG1,,Modbus_Master_Driver_Instances[1].Tags[1].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG2,,Modbus_Master_Driver_Instances[1].Tags[2].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG3,,Modbus_Master_Driver_Instances[1].Tags[3].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG4,,Modbus_Master_Driver_Instances[1].Tags[4].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG5,,Modbus_Master_Driver_Instances[1].Tags[5].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG6,,Modbus_Master_Driver_Instances[1].Tags[6].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_TAG7,,Modbus_Master_Driver_Instances[1].Tags[7].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_ONLINE,,Modbus_Master_Driver_Instances[1].Tags[8].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_SENDNUM,,Modbus_Master_Driver_Instances[1].Tags[9].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_RECNUM,,Modbus_Master_Driver_Instances[1].Tags[10].TagValue);
	__SET_VAR(,RES0__RIO2_BLOCK1_ERROR,,Modbus_Master_Driver_Instances[1].Tags[11].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG0,,Modbus_Master_Driver_Instances[2].Tags[0].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG2,,Modbus_Master_Driver_Instances[2].Tags[1].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG4,,Modbus_Master_Driver_Instances[2].Tags[2].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG6,,Modbus_Master_Driver_Instances[2].Tags[3].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG8,,Modbus_Master_Driver_Instances[2].Tags[4].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG10,,Modbus_Master_Driver_Instances[2].Tags[5].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG12,,Modbus_Master_Driver_Instances[2].Tags[6].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG14,,Modbus_Master_Driver_Instances[2].Tags[7].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG16,,Modbus_Master_Driver_Instances[2].Tags[8].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG18,,Modbus_Master_Driver_Instances[2].Tags[9].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG20,,Modbus_Master_Driver_Instances[2].Tags[10].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG22,,Modbus_Master_Driver_Instances[2].Tags[11].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG24,,Modbus_Master_Driver_Instances[2].Tags[12].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG26,,Modbus_Master_Driver_Instances[2].Tags[13].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG28,,Modbus_Master_Driver_Instances[2].Tags[14].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG30,,Modbus_Master_Driver_Instances[2].Tags[15].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG32,,Modbus_Master_Driver_Instances[2].Tags[16].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG34,,Modbus_Master_Driver_Instances[2].Tags[17].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG36,,Modbus_Master_Driver_Instances[2].Tags[18].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG38,,Modbus_Master_Driver_Instances[2].Tags[19].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG40,,Modbus_Master_Driver_Instances[2].Tags[20].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG42,,Modbus_Master_Driver_Instances[2].Tags[21].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG44,,Modbus_Master_Driver_Instances[2].Tags[22].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG46,,Modbus_Master_Driver_Instances[2].Tags[23].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_TAG48,,Modbus_Master_Driver_Instances[2].Tags[24].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_ONLINE,,Modbus_Master_Driver_Instances[2].Tags[25].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_SENDNUM,,Modbus_Master_Driver_Instances[2].Tags[26].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_RECNUM,,Modbus_Master_Driver_Instances[2].Tags[27].TagValue);
	__SET_VAR(,RES0__ROI3_BLOCK1_ERROR,,Modbus_Master_Driver_Instances[2].Tags[28].TagValue);
}
