#include "AMSLS.h"
#include "POUS.h"

extern __ARRAY_OF_LWORD_256 RES0__I;
extern __ARRAY_OF_LWORD_256 RES0__Q;
extern __ARRAY_OF_LWORD_256 RES0__M;
extern __IEC_BOOL_t RES0__SQLITE_TAG1;
extern __IEC_UDINT_t RES0__SQLITE_TAG1_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG1_DT;
extern __IEC_SINT_t RES0__SQLITE_TAG2;
extern __IEC_UDINT_t RES0__SQLITE_TAG2_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG2_DT;
extern __IEC_INT_t RES0__SQLITE_TAG3;
extern __IEC_UDINT_t RES0__SQLITE_TAG3_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG3_DT;
extern __IEC_DINT_t RES0__SQLITE_TAG4;
extern __IEC_UDINT_t RES0__SQLITE_TAG4_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG4_DT;
extern __IEC_LINT_t RES0__SQLITE_TAG5;
extern __IEC_UDINT_t RES0__SQLITE_TAG5_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG5_DT;
extern __IEC_USINT_t RES0__SQLITE_TAG6;
extern __IEC_UDINT_t RES0__SQLITE_TAG6_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG6_DT;
extern __IEC_UINT_t RES0__SQLITE_TAG7;
extern __IEC_UDINT_t RES0__SQLITE_TAG7_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG7_DT;
extern __IEC_UDINT_t RES0__SQLITE_TAG8;
extern __IEC_UDINT_t RES0__SQLITE_TAG8_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG8_DT;
extern __IEC_ULINT_t RES0__SQLITE_TAG9;
extern __IEC_UDINT_t RES0__SQLITE_TAG9_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG9_DT;
extern __IEC_REAL_t RES0__SQLITE_TAG10;
extern __IEC_UDINT_t RES0__SQLITE_TAG10_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG10_DT;
extern __IEC_LREAL_t RES0__SQLITE_TAG11;
extern __IEC_UDINT_t RES0__SQLITE_TAG11_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG11_DT;
extern __IEC_UINT_t RES0__SQLITE_TAG12;
extern __IEC_UDINT_t RES0__SQLITE_TAG12_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG12_DT;
extern __IEC_UINT_t RES0__SQLITE_TAG13;
extern __IEC_UDINT_t RES0__SQLITE_TAG13_STATUS;
extern __IEC_DT_t RES0__SQLITE_TAG13_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG0;
extern __IEC_UDINT_t RES0__LIO_DITAG0_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG0_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG1;
extern __IEC_UDINT_t RES0__LIO_DITAG1_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG1_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG2;
extern __IEC_UDINT_t RES0__LIO_DITAG2_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG2_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG3;
extern __IEC_UDINT_t RES0__LIO_DITAG3_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG3_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG4;
extern __IEC_UDINT_t RES0__LIO_DITAG4_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG4_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG5;
extern __IEC_UDINT_t RES0__LIO_DITAG5_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG5_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG6;
extern __IEC_UDINT_t RES0__LIO_DITAG6_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG6_DT;
extern __IEC_BOOL_t RES0__LIO_DITAG7;
extern __IEC_UDINT_t RES0__LIO_DITAG7_STATUS;
extern __IEC_DT_t RES0__LIO_DITAG7_DT;
extern __IEC_BOOL_t RES0__LIO_DOTAG0;
extern __IEC_UDINT_t RES0__LIO_DOTAG0_STATUS;
extern __IEC_DT_t RES0__LIO_DOTAG0_DT;
extern __IEC_BOOL_t RES0__LIO_DOTAG1;
extern __IEC_UDINT_t RES0__LIO_DOTAG1_STATUS;
extern __IEC_DT_t RES0__LIO_DOTAG1_DT;
extern __IEC_BOOL_t RES0__LIO_DOTAG2;
extern __IEC_UDINT_t RES0__LIO_DOTAG2_STATUS;
extern __IEC_DT_t RES0__LIO_DOTAG2_DT;
extern __IEC_BOOL_t RES0__LIO_DOTAG3;
extern __IEC_UDINT_t RES0__LIO_DOTAG3_STATUS;
extern __IEC_DT_t RES0__LIO_DOTAG3_DT;
extern __IEC_UINT_t RES0__LIO_AITAG0;
extern __IEC_UDINT_t RES0__LIO_AITAG0_STATUS;
extern __IEC_DT_t RES0__LIO_AITAG0_DT;
extern __IEC_UINT_t RES0__LIO_AITAG1;
extern __IEC_UDINT_t RES0__LIO_AITAG1_STATUS;
extern __IEC_DT_t RES0__LIO_AITAG1_DT;
extern __IEC_UINT_t RES0__LIO_AITAG2;
extern __IEC_UDINT_t RES0__LIO_AITAG2_STATUS;
extern __IEC_DT_t RES0__LIO_AITAG2_DT;
extern __IEC_UINT_t RES0__LIO_AITAG3;
extern __IEC_UDINT_t RES0__LIO_AITAG3_STATUS;
extern __IEC_DT_t RES0__LIO_AITAG3_DT;
extern __IEC_UINT_t RES0__LIO_AOTAG0;
extern __IEC_UDINT_t RES0__LIO_AOTAG0_STATUS;
extern __IEC_DT_t RES0__LIO_AOTAG0_DT;
extern __IEC_UDINT_t RES0__LIO_CNTTAG0;
extern __IEC_UDINT_t RES0__LIO_CNTTAG0_STATUS;
extern __IEC_DT_t RES0__LIO_CNTTAG0_DT;
extern __IEC_LINT_t RES0__LIO_CNTTAG0_CONTROL;
extern __IEC_UDINT_t RES0__LIO_CNTTAG1;
extern __IEC_UDINT_t RES0__LIO_CNTTAG1_STATUS;
extern __IEC_DT_t RES0__LIO_CNTTAG1_DT;
extern __IEC_LINT_t RES0__LIO_CNTTAG1_CONTROL;
extern __IEC_UDINT_t RES0__LIO_CNTTAG2;
extern __IEC_UDINT_t RES0__LIO_CNTTAG2_STATUS;
extern __IEC_DT_t RES0__LIO_CNTTAG2_DT;
extern __IEC_LINT_t RES0__LIO_CNTTAG2_CONTROL;
extern __IEC_UDINT_t RES0__LIO_CNTTAG3;
extern __IEC_UDINT_t RES0__LIO_CNTTAG3_STATUS;
extern __IEC_DT_t RES0__LIO_CNTTAG3_DT;
extern __IEC_LINT_t RES0__LIO_CNTTAG3_CONTROL;
extern __IEC_REAL_t RES0__LIO_SENTAG0;
extern __IEC_UDINT_t RES0__LIO_SENTAG0_STATUS;
extern __IEC_DT_t RES0__LIO_SENTAG0_DT;
extern __IEC_REAL_t RES0__LIO_SENTAG1;
extern __IEC_UDINT_t RES0__LIO_SENTAG1_STATUS;
extern __IEC_DT_t RES0__LIO_SENTAG1_DT;
extern __IEC_USINT_t RES0__LIO_RESET;
extern __IEC_UDINT_t RES0__LIO_RESET_STATUS;
extern __IEC_DT_t RES0__LIO_RESET_DT;
extern __IEC_REAL_t RES0__LIO_CPU_USAGE;
extern __IEC_UDINT_t RES0__LIO_CPU_USAGE_STATUS;
extern __IEC_DT_t RES0__LIO_CPU_USAGE_DT;
extern __IEC_REAL_t RES0__LIO_TOTAL_RAM;
extern __IEC_UDINT_t RES0__LIO_TOTAL_RAM_STATUS;
extern __IEC_DT_t RES0__LIO_TOTAL_RAM_DT;
extern __IEC_REAL_t RES0__LIO_FREESPACE_RAM;
extern __IEC_UDINT_t RES0__LIO_FREESPACE_RAM_STATUS;
extern __IEC_DT_t RES0__LIO_FREESPACE_RAM_DT;
extern __IEC_REAL_t RES0__LIO_USED_RAM;
extern __IEC_UDINT_t RES0__LIO_USED_RAM_STATUS;
extern __IEC_DT_t RES0__LIO_USED_RAM_DT;
extern __IEC_REAL_t RES0__LIO_TOTAL_FLASH;
extern __IEC_UDINT_t RES0__LIO_TOTAL_FLASH_STATUS;
extern __IEC_DT_t RES0__LIO_TOTAL_FLASH_DT;
extern __IEC_REAL_t RES0__LIO_FREESPACE_FLASH;
extern __IEC_UDINT_t RES0__LIO_FREESPACE_FLASH_STATUS;
extern __IEC_DT_t RES0__LIO_FREESPACE_FLASH_DT;
extern __IEC_REAL_t RES0__LIO_USED_FLASH;
extern __IEC_UDINT_t RES0__LIO_USED_FLASH_STATUS;
extern __IEC_DT_t RES0__LIO_USED_FLASH_DT;
extern __IEC_REAL_t RES0__LIO_TOTAL_SDCARD;
extern __IEC_UDINT_t RES0__LIO_TOTAL_SDCARD_STATUS;
extern __IEC_DT_t RES0__LIO_TOTAL_SDCARD_DT;
extern __IEC_REAL_t RES0__LIO_FREESPACE_SDCARD;
extern __IEC_UDINT_t RES0__LIO_FREESPACE_SDCARD_STATUS;
extern __IEC_DT_t RES0__LIO_FREESPACE_SDCARD_DT;
extern __IEC_REAL_t RES0__LIO_USED_SDCARD;
extern __IEC_UDINT_t RES0__LIO_USED_SDCARD_STATUS;
extern __IEC_DT_t RES0__LIO_USED_SDCARD_DT;
extern __IEC_REAL_t RES0__LIO_TOTAL_NVRAM;
extern __IEC_UDINT_t RES0__LIO_TOTAL_NVRAM_STATUS;
extern __IEC_DT_t RES0__LIO_TOTAL_NVRAM_DT;
extern __IEC_REAL_t RES0__LIO_FREESPACE_NVRAM;
extern __IEC_UDINT_t RES0__LIO_FREESPACE_NVRAM_STATUS;
extern __IEC_DT_t RES0__LIO_FREESPACE_NVRAM_DT;
extern __IEC_REAL_t RES0__LIO_USED_NVRAM;
extern __IEC_UDINT_t RES0__LIO_USED_NVRAM_STATUS;
extern __IEC_DT_t RES0__LIO_USED_NVRAM_DT;
extern __IEC_USINT_t RES0__LIO_CANBUS_STATUS;
extern __IEC_UDINT_t RES0__LIO_CANBUS_STATUS_STATUS;
extern __IEC_DT_t RES0__LIO_CANBUS_STATUS_DT;
extern __IEC_USINT_t RES0__LIO_BUZZER;
extern __IEC_UDINT_t RES0__LIO_BUZZER_STATUS;
extern __IEC_DT_t RES0__LIO_BUZZER_DT;
extern __IEC_USINT_t RES0__LIO_3GMODEMON;
extern __IEC_UDINT_t RES0__LIO_3GMODEMON_STATUS;
extern __IEC_DT_t RES0__LIO_3GMODEMON_DT;
extern __IEC_USINT_t RES0__LIO_3GMODEMSIGNALLEVEL;
extern __IEC_UDINT_t RES0__LIO_3GMODEMSIGNALLEVEL_STATUS;
extern __IEC_DT_t RES0__LIO_3GMODEMSIGNALLEVEL_DT;
extern __IEC_BOOL_t RES0__LIO_3GCONNECTED;
extern __IEC_UDINT_t RES0__LIO_3GCONNECTED_STATUS;
extern __IEC_DT_t RES0__LIO_3GCONNECTED_DT;
extern __IEC_USINT_t RES0__LIO_3GMODEMSECIP1;
extern __IEC_UDINT_t RES0__LIO_3GMODEMSECIP1_STATUS;
extern __IEC_DT_t RES0__LIO_3GMODEMSECIP1_DT;
extern __IEC_USINT_t RES0__LIO_3GMODEMSECIP2;
extern __IEC_UDINT_t RES0__LIO_3GMODEMSECIP2_STATUS;
extern __IEC_DT_t RES0__LIO_3GMODEMSECIP2_DT;
extern __IEC_USINT_t RES0__LIO_3GMODEMSECIP3;
extern __IEC_UDINT_t RES0__LIO_3GMODEMSECIP3_STATUS;
extern __IEC_DT_t RES0__LIO_3GMODEMSECIP3_DT;
extern __IEC_USINT_t RES0__LIO_3GMODEMSECIP4;
extern __IEC_UDINT_t RES0__LIO_3GMODEMSECIP4_STATUS;
extern __IEC_DT_t RES0__LIO_3GMODEMSECIP4_DT;
extern __IEC_REAL_t RES0__LIO_LOGIC_PROCESSING_TIME;
extern __IEC_UDINT_t RES0__LIO_LOGIC_PROCESSING_TIME_STATUS;
extern __IEC_DT_t RES0__LIO_LOGIC_PROCESSING_TIME_DT;
extern __IEC_BOOL_t RES0__LIO_FIRST_SCAN;
extern __IEC_UDINT_t RES0__LIO_FIRST_SCAN_STATUS;
extern __IEC_DT_t RES0__LIO_FIRST_SCAN_DT;
extern POU_2 RES0__INSTANCE_2;
var_t vars[] = {
{&(RES0__SQLITE_TAG1), BOOL_ENUM,"RES0__SQLITE_TAG1:BOOL_ENUM"},
{&(RES0__SQLITE_TAG1_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG1_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG1_DT), DT_ENUM,"RES0__SQLITE_TAG1_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG2), SINT_ENUM,"RES0__SQLITE_TAG2:SINT_ENUM"},
{&(RES0__SQLITE_TAG2_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG2_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG2_DT), DT_ENUM,"RES0__SQLITE_TAG2_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG3), INT_ENUM,"RES0__SQLITE_TAG3:INT_ENUM"},
{&(RES0__SQLITE_TAG3_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG3_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG3_DT), DT_ENUM,"RES0__SQLITE_TAG3_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG4), DINT_ENUM,"RES0__SQLITE_TAG4:DINT_ENUM"},
{&(RES0__SQLITE_TAG4_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG4_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG4_DT), DT_ENUM,"RES0__SQLITE_TAG4_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG5), LINT_ENUM,"RES0__SQLITE_TAG5:LINT_ENUM"},
{&(RES0__SQLITE_TAG5_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG5_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG5_DT), DT_ENUM,"RES0__SQLITE_TAG5_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG6), USINT_ENUM,"RES0__SQLITE_TAG6:USINT_ENUM"},
{&(RES0__SQLITE_TAG6_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG6_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG6_DT), DT_ENUM,"RES0__SQLITE_TAG6_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG7), UINT_ENUM,"RES0__SQLITE_TAG7:UINT_ENUM"},
{&(RES0__SQLITE_TAG7_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG7_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG7_DT), DT_ENUM,"RES0__SQLITE_TAG7_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG8), UDINT_ENUM,"RES0__SQLITE_TAG8:UDINT_ENUM"},
{&(RES0__SQLITE_TAG8_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG8_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG8_DT), DT_ENUM,"RES0__SQLITE_TAG8_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG9), ULINT_ENUM,"RES0__SQLITE_TAG9:ULINT_ENUM"},
{&(RES0__SQLITE_TAG9_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG9_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG9_DT), DT_ENUM,"RES0__SQLITE_TAG9_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG10), REAL_ENUM,"RES0__SQLITE_TAG10:REAL_ENUM"},
{&(RES0__SQLITE_TAG10_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG10_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG10_DT), DT_ENUM,"RES0__SQLITE_TAG10_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG11), LREAL_ENUM,"RES0__SQLITE_TAG11:LREAL_ENUM"},
{&(RES0__SQLITE_TAG11_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG11_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG11_DT), DT_ENUM,"RES0__SQLITE_TAG11_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG12), UINT_ENUM,"RES0__SQLITE_TAG12:UINT_ENUM"},
{&(RES0__SQLITE_TAG12_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG12_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG12_DT), DT_ENUM,"RES0__SQLITE_TAG12_DT:DT_ENUM"},
{&(RES0__SQLITE_TAG13), UINT_ENUM,"RES0__SQLITE_TAG13:UINT_ENUM"},
{&(RES0__SQLITE_TAG13_STATUS), UDINT_ENUM,"RES0__SQLITE_TAG13_STATUS:UDINT_ENUM"},
{&(RES0__SQLITE_TAG13_DT), DT_ENUM,"RES0__SQLITE_TAG13_DT:DT_ENUM"},
{&(RES0__LIO_DITAG0), BOOL_ENUM,"RES0__LIO_DITAG0:BOOL_ENUM"},
{&(RES0__LIO_DITAG0_STATUS), UDINT_ENUM,"RES0__LIO_DITAG0_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG0_DT), DT_ENUM,"RES0__LIO_DITAG0_DT:DT_ENUM"},
{&(RES0__LIO_DITAG1), BOOL_ENUM,"RES0__LIO_DITAG1:BOOL_ENUM"},
{&(RES0__LIO_DITAG1_STATUS), UDINT_ENUM,"RES0__LIO_DITAG1_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG1_DT), DT_ENUM,"RES0__LIO_DITAG1_DT:DT_ENUM"},
{&(RES0__LIO_DITAG2), BOOL_ENUM,"RES0__LIO_DITAG2:BOOL_ENUM"},
{&(RES0__LIO_DITAG2_STATUS), UDINT_ENUM,"RES0__LIO_DITAG2_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG2_DT), DT_ENUM,"RES0__LIO_DITAG2_DT:DT_ENUM"},
{&(RES0__LIO_DITAG3), BOOL_ENUM,"RES0__LIO_DITAG3:BOOL_ENUM"},
{&(RES0__LIO_DITAG3_STATUS), UDINT_ENUM,"RES0__LIO_DITAG3_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG3_DT), DT_ENUM,"RES0__LIO_DITAG3_DT:DT_ENUM"},
{&(RES0__LIO_DITAG4), BOOL_ENUM,"RES0__LIO_DITAG4:BOOL_ENUM"},
{&(RES0__LIO_DITAG4_STATUS), UDINT_ENUM,"RES0__LIO_DITAG4_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG4_DT), DT_ENUM,"RES0__LIO_DITAG4_DT:DT_ENUM"},
{&(RES0__LIO_DITAG5), BOOL_ENUM,"RES0__LIO_DITAG5:BOOL_ENUM"},
{&(RES0__LIO_DITAG5_STATUS), UDINT_ENUM,"RES0__LIO_DITAG5_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG5_DT), DT_ENUM,"RES0__LIO_DITAG5_DT:DT_ENUM"},
{&(RES0__LIO_DITAG6), BOOL_ENUM,"RES0__LIO_DITAG6:BOOL_ENUM"},
{&(RES0__LIO_DITAG6_STATUS), UDINT_ENUM,"RES0__LIO_DITAG6_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG6_DT), DT_ENUM,"RES0__LIO_DITAG6_DT:DT_ENUM"},
{&(RES0__LIO_DITAG7), BOOL_ENUM,"RES0__LIO_DITAG7:BOOL_ENUM"},
{&(RES0__LIO_DITAG7_STATUS), UDINT_ENUM,"RES0__LIO_DITAG7_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DITAG7_DT), DT_ENUM,"RES0__LIO_DITAG7_DT:DT_ENUM"},
{&(RES0__LIO_DOTAG0), BOOL_ENUM,"RES0__LIO_DOTAG0:BOOL_ENUM"},
{&(RES0__LIO_DOTAG0_STATUS), UDINT_ENUM,"RES0__LIO_DOTAG0_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DOTAG0_DT), DT_ENUM,"RES0__LIO_DOTAG0_DT:DT_ENUM"},
{&(RES0__LIO_DOTAG1), BOOL_ENUM,"RES0__LIO_DOTAG1:BOOL_ENUM"},
{&(RES0__LIO_DOTAG1_STATUS), UDINT_ENUM,"RES0__LIO_DOTAG1_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DOTAG1_DT), DT_ENUM,"RES0__LIO_DOTAG1_DT:DT_ENUM"},
{&(RES0__LIO_DOTAG2), BOOL_ENUM,"RES0__LIO_DOTAG2:BOOL_ENUM"},
{&(RES0__LIO_DOTAG2_STATUS), UDINT_ENUM,"RES0__LIO_DOTAG2_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DOTAG2_DT), DT_ENUM,"RES0__LIO_DOTAG2_DT:DT_ENUM"},
{&(RES0__LIO_DOTAG3), BOOL_ENUM,"RES0__LIO_DOTAG3:BOOL_ENUM"},
{&(RES0__LIO_DOTAG3_STATUS), UDINT_ENUM,"RES0__LIO_DOTAG3_STATUS:UDINT_ENUM"},
{&(RES0__LIO_DOTAG3_DT), DT_ENUM,"RES0__LIO_DOTAG3_DT:DT_ENUM"},
{&(RES0__LIO_AITAG0), UINT_ENUM,"RES0__LIO_AITAG0:UINT_ENUM"},
{&(RES0__LIO_AITAG0_STATUS), UDINT_ENUM,"RES0__LIO_AITAG0_STATUS:UDINT_ENUM"},
{&(RES0__LIO_AITAG0_DT), DT_ENUM,"RES0__LIO_AITAG0_DT:DT_ENUM"},
{&(RES0__LIO_AITAG1), UINT_ENUM,"RES0__LIO_AITAG1:UINT_ENUM"},
{&(RES0__LIO_AITAG1_STATUS), UDINT_ENUM,"RES0__LIO_AITAG1_STATUS:UDINT_ENUM"},
{&(RES0__LIO_AITAG1_DT), DT_ENUM,"RES0__LIO_AITAG1_DT:DT_ENUM"},
{&(RES0__LIO_AITAG2), UINT_ENUM,"RES0__LIO_AITAG2:UINT_ENUM"},
{&(RES0__LIO_AITAG2_STATUS), UDINT_ENUM,"RES0__LIO_AITAG2_STATUS:UDINT_ENUM"},
{&(RES0__LIO_AITAG2_DT), DT_ENUM,"RES0__LIO_AITAG2_DT:DT_ENUM"},
{&(RES0__LIO_AITAG3), UINT_ENUM,"RES0__LIO_AITAG3:UINT_ENUM"},
{&(RES0__LIO_AITAG3_STATUS), UDINT_ENUM,"RES0__LIO_AITAG3_STATUS:UDINT_ENUM"},
{&(RES0__LIO_AITAG3_DT), DT_ENUM,"RES0__LIO_AITAG3_DT:DT_ENUM"},
{&(RES0__LIO_AOTAG0), UINT_ENUM,"RES0__LIO_AOTAG0:UINT_ENUM"},
{&(RES0__LIO_AOTAG0_STATUS), UDINT_ENUM,"RES0__LIO_AOTAG0_STATUS:UDINT_ENUM"},
{&(RES0__LIO_AOTAG0_DT), DT_ENUM,"RES0__LIO_AOTAG0_DT:DT_ENUM"},
{&(RES0__LIO_CNTTAG0), UDINT_ENUM,"RES0__LIO_CNTTAG0:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG0_STATUS), UDINT_ENUM,"RES0__LIO_CNTTAG0_STATUS:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG0_DT), DT_ENUM,"RES0__LIO_CNTTAG0_DT:DT_ENUM"},
{&(RES0__LIO_CNTTAG0_CONTROL), LINT_ENUM,"RES0__LIO_CNTTAG0_CONTROL:LINT_ENUM"},
{&(RES0__LIO_CNTTAG1), UDINT_ENUM,"RES0__LIO_CNTTAG1:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG1_STATUS), UDINT_ENUM,"RES0__LIO_CNTTAG1_STATUS:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG1_DT), DT_ENUM,"RES0__LIO_CNTTAG1_DT:DT_ENUM"},
{&(RES0__LIO_CNTTAG1_CONTROL), LINT_ENUM,"RES0__LIO_CNTTAG1_CONTROL:LINT_ENUM"},
{&(RES0__LIO_CNTTAG2), UDINT_ENUM,"RES0__LIO_CNTTAG2:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG2_STATUS), UDINT_ENUM,"RES0__LIO_CNTTAG2_STATUS:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG2_DT), DT_ENUM,"RES0__LIO_CNTTAG2_DT:DT_ENUM"},
{&(RES0__LIO_CNTTAG2_CONTROL), LINT_ENUM,"RES0__LIO_CNTTAG2_CONTROL:LINT_ENUM"},
{&(RES0__LIO_CNTTAG3), UDINT_ENUM,"RES0__LIO_CNTTAG3:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG3_STATUS), UDINT_ENUM,"RES0__LIO_CNTTAG3_STATUS:UDINT_ENUM"},
{&(RES0__LIO_CNTTAG3_DT), DT_ENUM,"RES0__LIO_CNTTAG3_DT:DT_ENUM"},
{&(RES0__LIO_CNTTAG3_CONTROL), LINT_ENUM,"RES0__LIO_CNTTAG3_CONTROL:LINT_ENUM"},
{&(RES0__LIO_SENTAG0), REAL_ENUM,"RES0__LIO_SENTAG0:REAL_ENUM"},
{&(RES0__LIO_SENTAG0_STATUS), UDINT_ENUM,"RES0__LIO_SENTAG0_STATUS:UDINT_ENUM"},
{&(RES0__LIO_SENTAG0_DT), DT_ENUM,"RES0__LIO_SENTAG0_DT:DT_ENUM"},
{&(RES0__LIO_SENTAG1), REAL_ENUM,"RES0__LIO_SENTAG1:REAL_ENUM"},
{&(RES0__LIO_SENTAG1_STATUS), UDINT_ENUM,"RES0__LIO_SENTAG1_STATUS:UDINT_ENUM"},
{&(RES0__LIO_SENTAG1_DT), DT_ENUM,"RES0__LIO_SENTAG1_DT:DT_ENUM"},
{&(RES0__LIO_RESET), USINT_ENUM,"RES0__LIO_RESET:USINT_ENUM"},
{&(RES0__LIO_RESET_STATUS), UDINT_ENUM,"RES0__LIO_RESET_STATUS:UDINT_ENUM"},
{&(RES0__LIO_RESET_DT), DT_ENUM,"RES0__LIO_RESET_DT:DT_ENUM"},
{&(RES0__LIO_CPU_USAGE), REAL_ENUM,"RES0__LIO_CPU_USAGE:REAL_ENUM"},
{&(RES0__LIO_CPU_USAGE_STATUS), UDINT_ENUM,"RES0__LIO_CPU_USAGE_STATUS:UDINT_ENUM"},
{&(RES0__LIO_CPU_USAGE_DT), DT_ENUM,"RES0__LIO_CPU_USAGE_DT:DT_ENUM"},
{&(RES0__LIO_TOTAL_RAM), REAL_ENUM,"RES0__LIO_TOTAL_RAM:REAL_ENUM"},
{&(RES0__LIO_TOTAL_RAM_STATUS), UDINT_ENUM,"RES0__LIO_TOTAL_RAM_STATUS:UDINT_ENUM"},
{&(RES0__LIO_TOTAL_RAM_DT), DT_ENUM,"RES0__LIO_TOTAL_RAM_DT:DT_ENUM"},
{&(RES0__LIO_FREESPACE_RAM), REAL_ENUM,"RES0__LIO_FREESPACE_RAM:REAL_ENUM"},
{&(RES0__LIO_FREESPACE_RAM_STATUS), UDINT_ENUM,"RES0__LIO_FREESPACE_RAM_STATUS:UDINT_ENUM"},
{&(RES0__LIO_FREESPACE_RAM_DT), DT_ENUM,"RES0__LIO_FREESPACE_RAM_DT:DT_ENUM"},
{&(RES0__LIO_USED_RAM), REAL_ENUM,"RES0__LIO_USED_RAM:REAL_ENUM"},
{&(RES0__LIO_USED_RAM_STATUS), UDINT_ENUM,"RES0__LIO_USED_RAM_STATUS:UDINT_ENUM"},
{&(RES0__LIO_USED_RAM_DT), DT_ENUM,"RES0__LIO_USED_RAM_DT:DT_ENUM"},
{&(RES0__LIO_TOTAL_FLASH), REAL_ENUM,"RES0__LIO_TOTAL_FLASH:REAL_ENUM"},
{&(RES0__LIO_TOTAL_FLASH_STATUS), UDINT_ENUM,"RES0__LIO_TOTAL_FLASH_STATUS:UDINT_ENUM"},
{&(RES0__LIO_TOTAL_FLASH_DT), DT_ENUM,"RES0__LIO_TOTAL_FLASH_DT:DT_ENUM"},
{&(RES0__LIO_FREESPACE_FLASH), REAL_ENUM,"RES0__LIO_FREESPACE_FLASH:REAL_ENUM"},
{&(RES0__LIO_FREESPACE_FLASH_STATUS), UDINT_ENUM,"RES0__LIO_FREESPACE_FLASH_STATUS:UDINT_ENUM"},
{&(RES0__LIO_FREESPACE_FLASH_DT), DT_ENUM,"RES0__LIO_FREESPACE_FLASH_DT:DT_ENUM"},
{&(RES0__LIO_USED_FLASH), REAL_ENUM,"RES0__LIO_USED_FLASH:REAL_ENUM"},
{&(RES0__LIO_USED_FLASH_STATUS), UDINT_ENUM,"RES0__LIO_USED_FLASH_STATUS:UDINT_ENUM"},
{&(RES0__LIO_USED_FLASH_DT), DT_ENUM,"RES0__LIO_USED_FLASH_DT:DT_ENUM"},
{&(RES0__LIO_TOTAL_SDCARD), REAL_ENUM,"RES0__LIO_TOTAL_SDCARD:REAL_ENUM"},
{&(RES0__LIO_TOTAL_SDCARD_STATUS), UDINT_ENUM,"RES0__LIO_TOTAL_SDCARD_STATUS:UDINT_ENUM"},
{&(RES0__LIO_TOTAL_SDCARD_DT), DT_ENUM,"RES0__LIO_TOTAL_SDCARD_DT:DT_ENUM"},
{&(RES0__LIO_FREESPACE_SDCARD), REAL_ENUM,"RES0__LIO_FREESPACE_SDCARD:REAL_ENUM"},
{&(RES0__LIO_FREESPACE_SDCARD_STATUS), UDINT_ENUM,"RES0__LIO_FREESPACE_SDCARD_STATUS:UDINT_ENUM"},
{&(RES0__LIO_FREESPACE_SDCARD_DT), DT_ENUM,"RES0__LIO_FREESPACE_SDCARD_DT:DT_ENUM"},
{&(RES0__LIO_USED_SDCARD), REAL_ENUM,"RES0__LIO_USED_SDCARD:REAL_ENUM"},
{&(RES0__LIO_USED_SDCARD_STATUS), UDINT_ENUM,"RES0__LIO_USED_SDCARD_STATUS:UDINT_ENUM"},
{&(RES0__LIO_USED_SDCARD_DT), DT_ENUM,"RES0__LIO_USED_SDCARD_DT:DT_ENUM"},
{&(RES0__LIO_TOTAL_NVRAM), REAL_ENUM,"RES0__LIO_TOTAL_NVRAM:REAL_ENUM"},
{&(RES0__LIO_TOTAL_NVRAM_STATUS), UDINT_ENUM,"RES0__LIO_TOTAL_NVRAM_STATUS:UDINT_ENUM"},
{&(RES0__LIO_TOTAL_NVRAM_DT), DT_ENUM,"RES0__LIO_TOTAL_NVRAM_DT:DT_ENUM"},
{&(RES0__LIO_FREESPACE_NVRAM), REAL_ENUM,"RES0__LIO_FREESPACE_NVRAM:REAL_ENUM"},
{&(RES0__LIO_FREESPACE_NVRAM_STATUS), UDINT_ENUM,"RES0__LIO_FREESPACE_NVRAM_STATUS:UDINT_ENUM"},
{&(RES0__LIO_FREESPACE_NVRAM_DT), DT_ENUM,"RES0__LIO_FREESPACE_NVRAM_DT:DT_ENUM"},
{&(RES0__LIO_USED_NVRAM), REAL_ENUM,"RES0__LIO_USED_NVRAM:REAL_ENUM"},
{&(RES0__LIO_USED_NVRAM_STATUS), UDINT_ENUM,"RES0__LIO_USED_NVRAM_STATUS:UDINT_ENUM"},
{&(RES0__LIO_USED_NVRAM_DT), DT_ENUM,"RES0__LIO_USED_NVRAM_DT:DT_ENUM"},
{&(RES0__LIO_CANBUS_STATUS), USINT_ENUM,"RES0__LIO_CANBUS_STATUS:USINT_ENUM"},
{&(RES0__LIO_CANBUS_STATUS_STATUS), UDINT_ENUM,"RES0__LIO_CANBUS_STATUS_STATUS:UDINT_ENUM"},
{&(RES0__LIO_CANBUS_STATUS_DT), DT_ENUM,"RES0__LIO_CANBUS_STATUS_DT:DT_ENUM"},
{&(RES0__LIO_BUZZER), USINT_ENUM,"RES0__LIO_BUZZER:USINT_ENUM"},
{&(RES0__LIO_BUZZER_STATUS), UDINT_ENUM,"RES0__LIO_BUZZER_STATUS:UDINT_ENUM"},
{&(RES0__LIO_BUZZER_DT), DT_ENUM,"RES0__LIO_BUZZER_DT:DT_ENUM"},
{&(RES0__LIO_3GMODEMON), USINT_ENUM,"RES0__LIO_3GMODEMON:USINT_ENUM"},
{&(RES0__LIO_3GMODEMON_STATUS), UDINT_ENUM,"RES0__LIO_3GMODEMON_STATUS:UDINT_ENUM"},
{&(RES0__LIO_3GMODEMON_DT), DT_ENUM,"RES0__LIO_3GMODEMON_DT:DT_ENUM"},
{&(RES0__LIO_3GMODEMSIGNALLEVEL), USINT_ENUM,"RES0__LIO_3GMODEMSIGNALLEVEL:USINT_ENUM"},
{&(RES0__LIO_3GMODEMSIGNALLEVEL_STATUS), UDINT_ENUM,"RES0__LIO_3GMODEMSIGNALLEVEL_STATUS:UDINT_ENUM"},
{&(RES0__LIO_3GMODEMSIGNALLEVEL_DT), DT_ENUM,"RES0__LIO_3GMODEMSIGNALLEVEL_DT:DT_ENUM"},
{&(RES0__LIO_3GCONNECTED), BOOL_ENUM,"RES0__LIO_3GCONNECTED:BOOL_ENUM"},
{&(RES0__LIO_3GCONNECTED_STATUS), UDINT_ENUM,"RES0__LIO_3GCONNECTED_STATUS:UDINT_ENUM"},
{&(RES0__LIO_3GCONNECTED_DT), DT_ENUM,"RES0__LIO_3GCONNECTED_DT:DT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP1), USINT_ENUM,"RES0__LIO_3GMODEMSECIP1:USINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP1_STATUS), UDINT_ENUM,"RES0__LIO_3GMODEMSECIP1_STATUS:UDINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP1_DT), DT_ENUM,"RES0__LIO_3GMODEMSECIP1_DT:DT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP2), USINT_ENUM,"RES0__LIO_3GMODEMSECIP2:USINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP2_STATUS), UDINT_ENUM,"RES0__LIO_3GMODEMSECIP2_STATUS:UDINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP2_DT), DT_ENUM,"RES0__LIO_3GMODEMSECIP2_DT:DT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP3), USINT_ENUM,"RES0__LIO_3GMODEMSECIP3:USINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP3_STATUS), UDINT_ENUM,"RES0__LIO_3GMODEMSECIP3_STATUS:UDINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP3_DT), DT_ENUM,"RES0__LIO_3GMODEMSECIP3_DT:DT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP4), USINT_ENUM,"RES0__LIO_3GMODEMSECIP4:USINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP4_STATUS), UDINT_ENUM,"RES0__LIO_3GMODEMSECIP4_STATUS:UDINT_ENUM"},
{&(RES0__LIO_3GMODEMSECIP4_DT), DT_ENUM,"RES0__LIO_3GMODEMSECIP4_DT:DT_ENUM"},
{&(RES0__LIO_LOGIC_PROCESSING_TIME), REAL_ENUM,"RES0__LIO_LOGIC_PROCESSING_TIME:REAL_ENUM"},
{&(RES0__LIO_LOGIC_PROCESSING_TIME_STATUS), UDINT_ENUM,"RES0__LIO_LOGIC_PROCESSING_TIME_STATUS:UDINT_ENUM"},
{&(RES0__LIO_LOGIC_PROCESSING_TIME_DT), DT_ENUM,"RES0__LIO_LOGIC_PROCESSING_TIME_DT:DT_ENUM"},
{&(RES0__LIO_FIRST_SCAN), BOOL_ENUM,"RES0__LIO_FIRST_SCAN:BOOL_ENUM"},
{&(RES0__LIO_FIRST_SCAN_STATUS), UDINT_ENUM,"RES0__LIO_FIRST_SCAN_STATUS:UDINT_ENUM"},
{&(RES0__LIO_FIRST_SCAN_DT), DT_ENUM,"RES0__LIO_FIRST_SCAN_DT:DT_ENUM"},
{&(RES0__INSTANCE_2.V_TON1.EN), BOOL_ENUM,"RES0__INSTANCE_2.V_TON1.EN:BOOL_ENUM"},
{&(RES0__INSTANCE_2.V_TON1.ENO), BOOL_ENUM,"RES0__INSTANCE_2.V_TON1.ENO:BOOL_ENUM"},
{&(RES0__INSTANCE_2.V_TON1.IN), BOOL_ENUM,"RES0__INSTANCE_2.V_TON1.IN:BOOL_ENUM"},
{&(RES0__INSTANCE_2.V_TON1.PT), TIME_ENUM,"RES0__INSTANCE_2.V_TON1.PT:TIME_ENUM"},
{&(RES0__INSTANCE_2.V_TON1.Q), BOOL_ENUM,"RES0__INSTANCE_2.V_TON1.Q:BOOL_ENUM"},
{&(RES0__INSTANCE_2.V_TON1.ET), TIME_ENUM,"RES0__INSTANCE_2.V_TON1.ET:TIME_ENUM"},
{&(RES0__INSTANCE_2.V_TON1.CURRENT_TIME), TIME_ENUM,"RES0__INSTANCE_2.V_TON1.CURRENT_TIME:TIME_ENUM"}
};
int spiFile=0;

void sig_handler(int signum){
LS_DeInit();
saveVarToRamdisk(&vars, varsArraySize);
printf("Local Variables Saved\n");
exit(1);}

int main(int argc, char* argv[]){
LS_Init();
int reatinInFlash_Minutes = 0;
if (argc == 2)
reatinInFlash_Minutes = atoi(argv[1]);
MainLogic(reatinInFlash_Minutes);}

void MainLogic(int reatinInFlash_Minutes)
{
signal(SIGTERM, sig_handler);
RES0_init__();
bIndexPtr = &bIndex;
bIndexPtr_retain = &bIndex_retain;
varsArraySize= sizeof(vars)/sizeof(var_t);
if(reatinInFlash_Minutes == 0) spiFile = initSPI_main();
if(initRetainVariables(spiFile,&vars,varsArraySize)) InitDRVFromRetainVar();
initVarFromRamdisk(&vars,varsArraySize);
RES0__LIO_FIRST_SCAN.value = true;
MainLogic_Init();

while (1)
{
tickManager();
clock_t tStart = clock();
FillTimeVar();
SetVarFromDRV();
InterruptManager();
RES0_run__(tick);
SetDRVFromVar();
saveRetainVariables(spiFile,reatinInFlash_Minutes,&vars,varsArraySize);
RES0__LIO_FIRST_SCAN.value = false;
logicProcessingTime = (double)(clock() - tStart)/CLOCKS_PER_SEC;
RES0__LIO_LOGIC_PROCESSING_TIME.value = logicProcessingTime;
sleepTime = (100 * 1e3) - (logicProcessingTime * 1e6);
sleepManager();
}
}
void *mntServer()
{
while (1)
{
analyzeBuffer(&vars,varsArraySize);
makeBuffer(&vars,varsArraySize);
usleep(100 * 1000);
}
}
void SetDRVFromVar()
{
amsDRVTags[0].TagValue[8]= __GET_VAR(RES0__LIO_DOTAG0,);
amsDRVTags[0].TagValue[9]= __GET_VAR(RES0__LIO_DOTAG1,);
amsDRVTags[0].TagValue[10]= __GET_VAR(RES0__LIO_DOTAG2,);
amsDRVTags[0].TagValue[11]= __GET_VAR(RES0__LIO_DOTAG3,);
amsDRVTags[0].TagValue[16]= __GET_VAR(RES0__LIO_AOTAG0,);
amsDRVTags[0].TagControl[17]= __GET_VAR(RES0__LIO_CNTTAG0_CONTROL,);
amsDRVTags[0].TagControl[18]= __GET_VAR(RES0__LIO_CNTTAG1_CONTROL,);
amsDRVTags[0].TagControl[19]= __GET_VAR(RES0__LIO_CNTTAG2_CONTROL,);
amsDRVTags[0].TagControl[20]= __GET_VAR(RES0__LIO_CNTTAG3_CONTROL,);
amsDRVTags[0].TagValue[23]= __GET_VAR(RES0__LIO_RESET,);
amsDRVTags[0].TagValue[38]= __GET_VAR(RES0__LIO_BUZZER,);
amsDRVTags[0].TagValue[39]= __GET_VAR(RES0__LIO_3GMODEMON,);
amsDRVTags[1].TagValue[0]= __GET_VAR(RES0__SQLITE_TAG1,);
amsDRVTags[1].TagStatus[0]= __GET_VAR(RES0__SQLITE_TAG1_STATUS,);
amsDRVTags[1].TagValueDT[0]= __GET_VAR(RES0__SQLITE_TAG1_DT,);
amsDRVTags[1].TagValue[1]= __GET_VAR(RES0__SQLITE_TAG2,);
amsDRVTags[1].TagStatus[1]= __GET_VAR(RES0__SQLITE_TAG2_STATUS,);
amsDRVTags[1].TagValueDT[1]= __GET_VAR(RES0__SQLITE_TAG2_DT,);
amsDRVTags[1].TagValue[2]= __GET_VAR(RES0__SQLITE_TAG3,);
amsDRVTags[1].TagStatus[2]= __GET_VAR(RES0__SQLITE_TAG3_STATUS,);
amsDRVTags[1].TagValueDT[2]= __GET_VAR(RES0__SQLITE_TAG3_DT,);
amsDRVTags[1].TagValue[3]= __GET_VAR(RES0__SQLITE_TAG4,);
amsDRVTags[1].TagStatus[3]= __GET_VAR(RES0__SQLITE_TAG4_STATUS,);
amsDRVTags[1].TagValueDT[3]= __GET_VAR(RES0__SQLITE_TAG4_DT,);
amsDRVTags[1].TagValue[4]= __GET_VAR(RES0__SQLITE_TAG5,);
amsDRVTags[1].TagStatus[4]= __GET_VAR(RES0__SQLITE_TAG5_STATUS,);
amsDRVTags[1].TagValueDT[4]= __GET_VAR(RES0__SQLITE_TAG5_DT,);
amsDRVTags[1].TagValue[5]= __GET_VAR(RES0__SQLITE_TAG6,);
amsDRVTags[1].TagStatus[5]= __GET_VAR(RES0__SQLITE_TAG6_STATUS,);
amsDRVTags[1].TagValueDT[5]= __GET_VAR(RES0__SQLITE_TAG6_DT,);
amsDRVTags[1].TagValue[6]= __GET_VAR(RES0__SQLITE_TAG7,);
amsDRVTags[1].TagStatus[6]= __GET_VAR(RES0__SQLITE_TAG7_STATUS,);
amsDRVTags[1].TagValueDT[6]= __GET_VAR(RES0__SQLITE_TAG7_DT,);
amsDRVTags[1].TagValue[7]= __GET_VAR(RES0__SQLITE_TAG8,);
amsDRVTags[1].TagStatus[7]= __GET_VAR(RES0__SQLITE_TAG8_STATUS,);
amsDRVTags[1].TagValueDT[7]= __GET_VAR(RES0__SQLITE_TAG8_DT,);
amsDRVTags[1].TagValue[8]= __GET_VAR(RES0__SQLITE_TAG9,);
amsDRVTags[1].TagStatus[8]= __GET_VAR(RES0__SQLITE_TAG9_STATUS,);
amsDRVTags[1].TagValueDT[8]= __GET_VAR(RES0__SQLITE_TAG9_DT,);
amsDRVTags[1].TagValue[9]= __GET_VAR(RES0__SQLITE_TAG10,);
amsDRVTags[1].TagStatus[9]= __GET_VAR(RES0__SQLITE_TAG10_STATUS,);
amsDRVTags[1].TagValueDT[9]= __GET_VAR(RES0__SQLITE_TAG10_DT,);
amsDRVTags[1].TagValue[10]= __GET_VAR(RES0__SQLITE_TAG11,);
amsDRVTags[1].TagStatus[10]= __GET_VAR(RES0__SQLITE_TAG11_STATUS,);
amsDRVTags[1].TagValueDT[10]= __GET_VAR(RES0__SQLITE_TAG11_DT,);
amsDRVTags[1].TagValue[12]= __GET_VAR(RES0__SQLITE_TAG13,);
amsDRVTags[1].TagStatus[12]= __GET_VAR(RES0__SQLITE_TAG13_STATUS,);
amsDRVTags[1].TagValueDT[12]= __GET_VAR(RES0__SQLITE_TAG13_DT,);
}
void InitDRVFromRetainVar()
{
}
void SetVarFromDRV()
{
__SET_VAR(,RES0__LIO_DITAG0,,amsDRVTags[0].TagValue[0]);
__SET_VAR(,RES0__LIO_DITAG0_STATUS,,amsDRVTags[0].TagStatus[0]);
__SET_VAR(,RES0__LIO_DITAG0_DT,,amsDRVTags[0].TagValueDT[0]);
__SET_VAR(,RES0__LIO_DITAG1,,amsDRVTags[0].TagValue[1]);
__SET_VAR(,RES0__LIO_DITAG1_STATUS,,amsDRVTags[0].TagStatus[1]);
__SET_VAR(,RES0__LIO_DITAG1_DT,,amsDRVTags[0].TagValueDT[1]);
__SET_VAR(,RES0__LIO_DITAG2,,amsDRVTags[0].TagValue[2]);
__SET_VAR(,RES0__LIO_DITAG2_STATUS,,amsDRVTags[0].TagStatus[2]);
__SET_VAR(,RES0__LIO_DITAG2_DT,,amsDRVTags[0].TagValueDT[2]);
__SET_VAR(,RES0__LIO_DITAG3,,amsDRVTags[0].TagValue[3]);
__SET_VAR(,RES0__LIO_DITAG3_STATUS,,amsDRVTags[0].TagStatus[3]);
__SET_VAR(,RES0__LIO_DITAG3_DT,,amsDRVTags[0].TagValueDT[3]);
__SET_VAR(,RES0__LIO_DITAG4,,amsDRVTags[0].TagValue[4]);
__SET_VAR(,RES0__LIO_DITAG4_STATUS,,amsDRVTags[0].TagStatus[4]);
__SET_VAR(,RES0__LIO_DITAG4_DT,,amsDRVTags[0].TagValueDT[4]);
__SET_VAR(,RES0__LIO_DITAG5,,amsDRVTags[0].TagValue[5]);
__SET_VAR(,RES0__LIO_DITAG5_STATUS,,amsDRVTags[0].TagStatus[5]);
__SET_VAR(,RES0__LIO_DITAG5_DT,,amsDRVTags[0].TagValueDT[5]);
__SET_VAR(,RES0__LIO_DITAG6,,amsDRVTags[0].TagValue[6]);
__SET_VAR(,RES0__LIO_DITAG6_STATUS,,amsDRVTags[0].TagStatus[6]);
__SET_VAR(,RES0__LIO_DITAG6_DT,,amsDRVTags[0].TagValueDT[6]);
__SET_VAR(,RES0__LIO_DITAG7,,amsDRVTags[0].TagValue[7]);
__SET_VAR(,RES0__LIO_DITAG7_STATUS,,amsDRVTags[0].TagStatus[7]);
__SET_VAR(,RES0__LIO_DITAG7_DT,,amsDRVTags[0].TagValueDT[7]);
__SET_VAR(,RES0__LIO_DOTAG0_STATUS,,amsDRVTags[0].TagStatus[8]);
__SET_VAR(,RES0__LIO_DOTAG0_DT,,amsDRVTags[0].TagValueDT[8]);
__SET_VAR(,RES0__LIO_DOTAG1_STATUS,,amsDRVTags[0].TagStatus[9]);
__SET_VAR(,RES0__LIO_DOTAG1_DT,,amsDRVTags[0].TagValueDT[9]);
__SET_VAR(,RES0__LIO_DOTAG2_STATUS,,amsDRVTags[0].TagStatus[10]);
__SET_VAR(,RES0__LIO_DOTAG2_DT,,amsDRVTags[0].TagValueDT[10]);
__SET_VAR(,RES0__LIO_DOTAG3_STATUS,,amsDRVTags[0].TagStatus[11]);
__SET_VAR(,RES0__LIO_DOTAG3_DT,,amsDRVTags[0].TagValueDT[11]);
__SET_VAR(,RES0__LIO_AITAG0,,amsDRVTags[0].TagValue[12]);
__SET_VAR(,RES0__LIO_AITAG0_STATUS,,amsDRVTags[0].TagStatus[12]);
__SET_VAR(,RES0__LIO_AITAG0_DT,,amsDRVTags[0].TagValueDT[12]);
__SET_VAR(,RES0__LIO_AITAG1,,amsDRVTags[0].TagValue[13]);
__SET_VAR(,RES0__LIO_AITAG1_STATUS,,amsDRVTags[0].TagStatus[13]);
__SET_VAR(,RES0__LIO_AITAG1_DT,,amsDRVTags[0].TagValueDT[13]);
__SET_VAR(,RES0__LIO_AITAG2,,amsDRVTags[0].TagValue[14]);
__SET_VAR(,RES0__LIO_AITAG2_STATUS,,amsDRVTags[0].TagStatus[14]);
__SET_VAR(,RES0__LIO_AITAG2_DT,,amsDRVTags[0].TagValueDT[14]);
__SET_VAR(,RES0__LIO_AITAG3,,amsDRVTags[0].TagValue[15]);
__SET_VAR(,RES0__LIO_AITAG3_STATUS,,amsDRVTags[0].TagStatus[15]);
__SET_VAR(,RES0__LIO_AITAG3_DT,,amsDRVTags[0].TagValueDT[15]);
__SET_VAR(,RES0__LIO_AOTAG0_STATUS,,amsDRVTags[0].TagStatus[16]);
__SET_VAR(,RES0__LIO_AOTAG0_DT,,amsDRVTags[0].TagValueDT[16]);
__SET_VAR(,RES0__LIO_CNTTAG0,,amsDRVTags[0].TagValue[17]);
__SET_VAR(,RES0__LIO_CNTTAG0_STATUS,,amsDRVTags[0].TagStatus[17]);
__SET_VAR(,RES0__LIO_CNTTAG0_DT,,amsDRVTags[0].TagValueDT[17]);
__SET_VAR(,RES0__LIO_CNTTAG1,,amsDRVTags[0].TagValue[18]);
__SET_VAR(,RES0__LIO_CNTTAG1_STATUS,,amsDRVTags[0].TagStatus[18]);
__SET_VAR(,RES0__LIO_CNTTAG1_DT,,amsDRVTags[0].TagValueDT[18]);
__SET_VAR(,RES0__LIO_CNTTAG2,,amsDRVTags[0].TagValue[19]);
__SET_VAR(,RES0__LIO_CNTTAG2_STATUS,,amsDRVTags[0].TagStatus[19]);
__SET_VAR(,RES0__LIO_CNTTAG2_DT,,amsDRVTags[0].TagValueDT[19]);
__SET_VAR(,RES0__LIO_CNTTAG3,,amsDRVTags[0].TagValue[20]);
__SET_VAR(,RES0__LIO_CNTTAG3_STATUS,,amsDRVTags[0].TagStatus[20]);
__SET_VAR(,RES0__LIO_CNTTAG3_DT,,amsDRVTags[0].TagValueDT[20]);
__SET_VAR(,RES0__LIO_SENTAG0,,amsDRVTags[0].TagValue[21]);
__SET_VAR(,RES0__LIO_SENTAG0_STATUS,,amsDRVTags[0].TagStatus[21]);
__SET_VAR(,RES0__LIO_SENTAG0_DT,,amsDRVTags[0].TagValueDT[21]);
__SET_VAR(,RES0__LIO_SENTAG1,,amsDRVTags[0].TagValue[22]);
__SET_VAR(,RES0__LIO_SENTAG1_STATUS,,amsDRVTags[0].TagStatus[22]);
__SET_VAR(,RES0__LIO_SENTAG1_DT,,amsDRVTags[0].TagValueDT[22]);
__SET_VAR(,RES0__LIO_RESET_STATUS,,amsDRVTags[0].TagStatus[23]);
__SET_VAR(,RES0__LIO_RESET_DT,,amsDRVTags[0].TagValueDT[23]);
__SET_VAR(,RES0__LIO_CPU_USAGE,,amsDRVTags[0].TagValue[24]);
__SET_VAR(,RES0__LIO_CPU_USAGE_STATUS,,amsDRVTags[0].TagStatus[24]);
__SET_VAR(,RES0__LIO_CPU_USAGE_DT,,amsDRVTags[0].TagValueDT[24]);
__SET_VAR(,RES0__LIO_TOTAL_RAM,,amsDRVTags[0].TagValue[25]);
__SET_VAR(,RES0__LIO_TOTAL_RAM_STATUS,,amsDRVTags[0].TagStatus[25]);
__SET_VAR(,RES0__LIO_TOTAL_RAM_DT,,amsDRVTags[0].TagValueDT[25]);
__SET_VAR(,RES0__LIO_FREESPACE_RAM,,amsDRVTags[0].TagValue[26]);
__SET_VAR(,RES0__LIO_FREESPACE_RAM_STATUS,,amsDRVTags[0].TagStatus[26]);
__SET_VAR(,RES0__LIO_FREESPACE_RAM_DT,,amsDRVTags[0].TagValueDT[26]);
__SET_VAR(,RES0__LIO_USED_RAM,,amsDRVTags[0].TagValue[27]);
__SET_VAR(,RES0__LIO_USED_RAM_STATUS,,amsDRVTags[0].TagStatus[27]);
__SET_VAR(,RES0__LIO_USED_RAM_DT,,amsDRVTags[0].TagValueDT[27]);
__SET_VAR(,RES0__LIO_TOTAL_FLASH,,amsDRVTags[0].TagValue[28]);
__SET_VAR(,RES0__LIO_TOTAL_FLASH_STATUS,,amsDRVTags[0].TagStatus[28]);
__SET_VAR(,RES0__LIO_TOTAL_FLASH_DT,,amsDRVTags[0].TagValueDT[28]);
__SET_VAR(,RES0__LIO_FREESPACE_FLASH,,amsDRVTags[0].TagValue[29]);
__SET_VAR(,RES0__LIO_FREESPACE_FLASH_STATUS,,amsDRVTags[0].TagStatus[29]);
__SET_VAR(,RES0__LIO_FREESPACE_FLASH_DT,,amsDRVTags[0].TagValueDT[29]);
__SET_VAR(,RES0__LIO_USED_FLASH,,amsDRVTags[0].TagValue[30]);
__SET_VAR(,RES0__LIO_USED_FLASH_STATUS,,amsDRVTags[0].TagStatus[30]);
__SET_VAR(,RES0__LIO_USED_FLASH_DT,,amsDRVTags[0].TagValueDT[30]);
__SET_VAR(,RES0__LIO_TOTAL_SDCARD,,amsDRVTags[0].TagValue[31]);
__SET_VAR(,RES0__LIO_TOTAL_SDCARD_STATUS,,amsDRVTags[0].TagStatus[31]);
__SET_VAR(,RES0__LIO_TOTAL_SDCARD_DT,,amsDRVTags[0].TagValueDT[31]);
__SET_VAR(,RES0__LIO_FREESPACE_SDCARD,,amsDRVTags[0].TagValue[32]);
__SET_VAR(,RES0__LIO_FREESPACE_SDCARD_STATUS,,amsDRVTags[0].TagStatus[32]);
__SET_VAR(,RES0__LIO_FREESPACE_SDCARD_DT,,amsDRVTags[0].TagValueDT[32]);
__SET_VAR(,RES0__LIO_USED_SDCARD,,amsDRVTags[0].TagValue[33]);
__SET_VAR(,RES0__LIO_USED_SDCARD_STATUS,,amsDRVTags[0].TagStatus[33]);
__SET_VAR(,RES0__LIO_USED_SDCARD_DT,,amsDRVTags[0].TagValueDT[33]);
__SET_VAR(,RES0__LIO_TOTAL_NVRAM,,amsDRVTags[0].TagValue[34]);
__SET_VAR(,RES0__LIO_TOTAL_NVRAM_STATUS,,amsDRVTags[0].TagStatus[34]);
__SET_VAR(,RES0__LIO_TOTAL_NVRAM_DT,,amsDRVTags[0].TagValueDT[34]);
__SET_VAR(,RES0__LIO_FREESPACE_NVRAM,,amsDRVTags[0].TagValue[35]);
__SET_VAR(,RES0__LIO_FREESPACE_NVRAM_STATUS,,amsDRVTags[0].TagStatus[35]);
__SET_VAR(,RES0__LIO_FREESPACE_NVRAM_DT,,amsDRVTags[0].TagValueDT[35]);
__SET_VAR(,RES0__LIO_USED_NVRAM,,amsDRVTags[0].TagValue[36]);
__SET_VAR(,RES0__LIO_USED_NVRAM_STATUS,,amsDRVTags[0].TagStatus[36]);
__SET_VAR(,RES0__LIO_USED_NVRAM_DT,,amsDRVTags[0].TagValueDT[36]);
__SET_VAR(,RES0__LIO_CANBUS_STATUS,,amsDRVTags[0].TagValue[37]);
__SET_VAR(,RES0__LIO_CANBUS_STATUS_STATUS,,amsDRVTags[0].TagStatus[37]);
__SET_VAR(,RES0__LIO_CANBUS_STATUS_DT,,amsDRVTags[0].TagValueDT[37]);
__SET_VAR(,RES0__LIO_BUZZER_STATUS,,amsDRVTags[0].TagStatus[38]);
__SET_VAR(,RES0__LIO_BUZZER_DT,,amsDRVTags[0].TagValueDT[38]);
__SET_VAR(,RES0__LIO_3GMODEMON_STATUS,,amsDRVTags[0].TagStatus[39]);
__SET_VAR(,RES0__LIO_3GMODEMON_DT,,amsDRVTags[0].TagValueDT[39]);
__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL,,amsDRVTags[0].TagValue[40]);
__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL_STATUS,,amsDRVTags[0].TagStatus[40]);
__SET_VAR(,RES0__LIO_3GMODEMSIGNALLEVEL_DT,,amsDRVTags[0].TagValueDT[40]);
__SET_VAR(,RES0__LIO_3GCONNECTED,,amsDRVTags[0].TagValue[41]);
__SET_VAR(,RES0__LIO_3GCONNECTED_STATUS,,amsDRVTags[0].TagStatus[41]);
__SET_VAR(,RES0__LIO_3GCONNECTED_DT,,amsDRVTags[0].TagValueDT[41]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP1,,amsDRVTags[0].TagValue[42]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP1_STATUS,,amsDRVTags[0].TagStatus[42]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP1_DT,,amsDRVTags[0].TagValueDT[42]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP2,,amsDRVTags[0].TagValue[43]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP2_STATUS,,amsDRVTags[0].TagStatus[43]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP2_DT,,amsDRVTags[0].TagValueDT[43]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP3,,amsDRVTags[0].TagValue[44]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP3_STATUS,,amsDRVTags[0].TagStatus[44]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP3_DT,,amsDRVTags[0].TagValueDT[44]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP4,,amsDRVTags[0].TagValue[45]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP4_STATUS,,amsDRVTags[0].TagStatus[45]);
__SET_VAR(,RES0__LIO_3GMODEMSECIP4_DT,,amsDRVTags[0].TagValueDT[45]);
__SET_VAR(,RES0__SQLITE_TAG12,,amsDRVTags[1].TagValue[11]);
__SET_VAR(,RES0__SQLITE_TAG12_STATUS,,amsDRVTags[1].TagStatus[11]);
__SET_VAR(,RES0__SQLITE_TAG12_DT,,amsDRVTags[1].TagValueDT[11]);
}
void FillTimeVar()
{
PLC_GetTime(&RES0__INSTANCE_2.V_TON1.CURRENT_TIME.value);
}
void InterruptManager()
{
}
